### ISSUE TITLE
An option to sync specific libraries and ignore the others.

### ISSUE THREAD

**Issue by morlanth** [Taxel/PlexTraktSync#39] opened 2020-06-21 12:22 UTC
I have libraries which contain content from YouTube and other sources which I do not want synced to Trakt. 

Is the ability to pick specific libraries a feature that is being considered in future updates?

**Comment by twolaw** [comment] 2020-06-22 13:07
duplicate of #22

**Closed** 2020-06-22 13:20 UTC
