### ISSUE TITLE
astimezone() cannot be applied to a naive client

### ISSUE THREAD

**Issue by montizzl3** [Taxel/PlexTraktSync#37] opened 2020-05-31 23:54 UTC
When I run this sync I get this:

"Processing section Movies
Traceback (most recent call last):
  File ".\main.py", line 324, in <module>
    main()
  File ".\main.py", line 305, in main
    section, trakt_watched_movies, ratings, listutil, trakt_movie_collection)
  File ".\main.py", line 117, in process_movie_section
    m.mark_as_seen(seen_date.astimezone(datetime.timezone.utc))
ValueError: astimezone() cannot be applied to a naive datetime"

Then the script stops.  Any idea what these could mean?

**Comment by twolaw** [comment] 2020-06-01 09:33
duplicate of #34

**Closed by twolaw** 2020-06-01 09:33 UTC
