### ISSUE TITLE
Internal Server Error for plex_trakt_sync.trakt_api.search_by_id()

### ISSUE THREAD

**Issue by CMBoii** [Taxel/PlexTraktSync#318] opened 2021-05-27 15:06 UTC
### The problem

_A description of what the bug is, including a complete traceback (if applicable)_

Trakt will display this issue at the very beginning but then it will scrobble the data successfully

### Expected behavior

_A description of what you expected to happen_

### Steps to reproduce the behavior

_With a complete code example, if possible_

It doesn't matter If I launch the code manually or via a cron job. 

### Workarounds

_Is there an existing workaround for this issue?_

python3 main.py

### Environment

- Version: e.g. `0.7.0` or `main` main
- Python version: e.g. `3.9` 3.8.6
- Platform: e.g. `Debian 10` DSM 6.2.4 (Synology)

```
2021-05-27 17:00:02,952 INFO[PlexTraktSync]:Syncing with Plex - and Trakt 
2021-05-27 17:00:06,623 INFO[PlexTraktSync]:Loaded Trakt lists in 3.7 seconds
2021-05-27 17:00:06,624 INFO[PlexTraktSync]:Downloaded List Trakt Watchlist
2021-05-27 17:00:06,624 INFO[PlexTraktSync]:Server version 1.23.1.4571-6119e8eed updated at: 2021-05-27 16:50:26
2021-05-27 17:00:17,329 WARNING[PlexTraktSync]:Internal Server Error for plex_trakt_sync.trakt_api.search_by_id(), retrying after 1 seconds (try: 1/5)
2021-05-27 17:00:18,847 WARNING[PlexTraktSync]:Internal Server Error for plex_trakt_sync.trakt_api.search_by_id(), retrying after 2 seconds (try: 2/5)
2021-05-27 17:00:21,381 WARNING[PlexTraktSync]:Internal Server Error for plex_trakt_sync.trakt_api.search_by_id(), retrying after 3 seconds (try: 3/5)
2021-05-27 17:00:24,909 WARNING[PlexTraktSync]:Internal Server Error for plex_trakt_sync.trakt_api.search_by_id(), retrying after 4 seconds (try: 4/5)
2021-05-27 17:00:29,437 WARNING[PlexTraktSync]:Internal Server Error for plex_trakt_sync.trakt_api.search_by_id(), retrying after 5 seconds (try: 5/5)
2021-05-27 17:00:34,973 WARNING[PlexTraktSync]:Skipping <tvdb:148286:<Movie:3434:Caught-by-a-Wave>>: Trakt errors: Internal Server Error
2021-05-27 17:01:01,100 INFO[PlexTraktSync]:Películas processed in 54.5 seconds
2021-05-27 17:01:05,725 INFO[PlexTraktSync]:Marking as watched in Trakt: <tvdb:351291/1/1:<Episode:6326:El-descubrimiento-de-s01e01>>
2021-05-27 17:01:17,977 INFO[PlexTraktSync]:To be added to collection: <tvdb:71663/12/17:<Episode:6003:The-Simpsons-s12e17>>
2021-05-27 17:01:18,244 INFO[PlexTraktSync]:Updated Trakt collection: {'added': {'episodes': 1}}
2021-05-27 17:01:18,251 INFO[PlexTraktSync]:To be added to collection: <tvdb:71663/16/7:<Episode:5902:The-Simpsons-s16e07>>
2021-05-27 17:01:19,355 INFO[PlexTraktSync]:Updated Trakt collection: {'added': {'episodes': 1}}
2021-05-27 17:01:24,241 INFO[PlexTraktSync]:Series processed in 23.1 seconds
2021-05-27 17:01:24,248 INFO[PlexTraktSync]:TV programmes processed in 0.0 seconds
2021-05-27 17:01:24,258 INFO[PlexTraktSync]:Updated plex watchlist in 0.0 seconds
2021-05-27 17:01:24,258 INFO[PlexTraktSync]:Completed full sync in 1 min 21.3 seconds
```

**Comment by twolaw** [comment] 2021-05-27 17:23
Duplicate of #313 

Trakt doesn't give a tvdb id for this movie.
The script should fallback to other providers ids to be able to recognize the movie. But it doesn't, so the movie remains unknown and is skipped.

```
"title": "Caught by a Wave",
  "year": 2021,
  "ids": {
    "trakt": 538222,
    "slug": "caught-by-a-wave-2021",
    "imdb": "tt12013758",
    "tmdb": 694256
  }
```

**Comment by CMBoii** [comment] 2021-05-27 17:42
I've read the easiest solution but I'm not sure on which lines I should change. 
Should I change all "0" to "1" in self.guild.split? 

` def provider(self):
        if self.guid_is_imdb_legacy:
            return "imdb"
        x = self.guid.split("://")[0]
        x = x.replace("com.plexapp.agents.", "")
        x = x.replace("tv.plex.agents.", "")
        x = x.replace("themoviedb", "tmdb")
        x = x.replace("thetvdb", "tvdb")
        if x == "xbmcnfo":
            x = CONFIG["xbmc-providers"][self.media_type]`

**Comment by glensc** [comment] 2021-06-05 09:21
@CMBoii as a workaround you can change the preferred order here:
- https://github.com/Taxel/PlexTraktSync/blob/0.10.2/plex_trakt_sync/plex_api.py#L71

**Comment by CMBoii** [comment] 2021-06-05 17:41
> @CMBoii as a workaround you can change the preferred order here:
> 
> * https://github.com/Taxel/PlexTraktSync/blob/0.10.2/plex_trakt_sync/plex_api.py#L71

Thank you. Unfortunately, the error still appears even using the latest version.

**Comment by glensc** [comment] 2021-06-06 07:08
@CMBoii you didn't say to what order you set, neither what is your error now.

**Comment by glensc** [comment] 2021-06-06 09:06
Such errors need to be reported to trakt.tv

Have you reported a problem with `<Movie:3434:Caught-by-a-Wave>` to trakt? Please share their response here as well.

**Comment by CMBoii** [comment] 2021-06-06 09:49
@glensc  I tried with the default order and setting IMDB > TMDB > TVDB. 

Besides, it seems that trakt lists the movie properly. https://trakt.tv/movies/caught-by-a-wave-2021

**Comment by glensc** [comment] 2021-06-06 11:21
@CMBoii 
1. try `./plex_trakt_sync.sh inspect 3434`
2. try removing `trakt_cache.sqlite`

**Comment by CMBoii** [comment] 2021-06-06 11:54
@glensc I see what the problem might be. The script only asks tvdb for the id. 

`CMBoii@server:/volume1/docker/trakt/Trakt$ sh plex_trakt_sync.sh inspect 3434
PlexTraktSync inspect [Unknown version]
Inspecting: <tvdb:148286:<Movie:3434:Caught-by-a-Wave>>
Guid: 'plex://movie/600fefb2433746002c98a042'
Guids: [<Guid:tvdb://148286>]
Audio: '5.1(side)', 'Español (AC3 5.1)'
Video: 'h264'
Provider: tvdb
Id: 148286
WARNING: Internal Server Error for plex_trakt_sync.trakt_api.search_by_id(), retrying after 1 seconds (try: 1/5)
WARNING: Internal Server Error for plex_trakt_sync.trakt_api.search_by_id(), retrying after 2 seconds (try: 2/5)
WARNING: Internal Server Error for plex_trakt_sync.trakt_api.search_by_id(), retrying after 3 seconds (try: 3/5)
WARNING: Internal Server Error for plex_trakt_sync.trakt_api.search_by_id(), retrying after 4 seconds (try: 4/5)
WARNING: Internal Server Error for plex_trakt_sync.trakt_api.search_by_id(), retrying after 5 seconds (try: 5/5)
Error: Internal Server Error`

**Comment by glensc** [comment] 2021-06-07 05:05
@CMBoii you may want to switch to the new Plex Metadata Agent, that has multiple providers.

- https://support.plex.tv/articles/200241558-agents/

**Comment by glensc** [comment] 2021-06-07 05:09
And in any case `Internal Server Error` is a bug in trakt and must be reported to their support.

**Comment by CMBoii** [comment] 2021-06-07 08:46
> And in any case `Internal Server Error` is a bug in trakt and must be reported to their support.

I'll talk to trakt's support.

Thank you.

**Closed** 2021-06-07 08:47 UTC
Labels: bug
