### ISSUE TITLE
Trakt tokens should be displayed prior to expiry

### ISSUE THREAD

**Issue by akshay7394** [Taxel/PlexTraktSync#322] opened 2021-06-02 09:08 UTC
### The problem

_The trakt token is not displayed in the terminal after entering client ID & Secret. Instead, a few minutes later, the token is displayed concurrently with an error stating that the token has already expired and the process has to be restarted._

### Expected behavior

_The activation code should be displayed immediately, instead of only after the expiry duration_

### Steps to reproduce the behavior

Run `python main,py` *for the first time*

```
First run, please follow those configuration instructions.
-- Plex --
Are you logged into this server with a Plex account? (y/n): y
Please enter your Plex username: username
Please enter your Plex password: examplepassword932593
Now enter the server name: servername
ERROR: http://1xx.1xx.57.184:8443: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
ERROR: http://1xx.1xx.112.43:32400: HTTPConnectionPool(host='1xx.1xx.112.43', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F1F86D9340>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
ERROR: https://1xx-1xx-112-43.abced3fefefd845742cca92ca26e558c73e9.plex.direct:32400: HTTPSConnectionPool(host='1xx-1xx-112-43.abced3fefefd8457442cca92ca26e558c73e9.plex.direct', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F1F86F50A0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
Managed user(s) found:
zzz@gmail.com
Guest
abc98
yyy@gmail.com
xxx@gmail.com
If you want to use a managed user enter its username,
if you want to use your main account just press enter:
Plex token and baseurl for xxxxxxhave been added in .env file:
PLEX_TOKEN=abced3fefedSEEWS
PLEX_BASEURL=https://192-168-1-94.abced3fefefd8457422ca26e558c73e9.plex.direct:32400
-- Trakt --
If you do not have a client ID and secret. Please visit the following url to create them.
http://trakt.tv/oauth/applications
Please enter your client id: bbw119461abced3fefefd84574b080a02d4fd952427367e2cdd415fc3227ef
Please enter your client secret: b1194f6abced3fefefd84574d84873841025129554b7588ef1caba198ceafa7c927
```

`<!-- waits for 600seconds here`

After a few minutes, this next wall of text is shown immediately, no wait time between the user code being shown and the tokens expiring:

```Your user code is: B16C9C31, please navigate to https://trakt.tv/activate to authenticate
The tokens have expired, restart the process
Traceback (most recent call last):
  File "C:\Tools\PlexTraktSync-0.9.15\main.py", line 6, in <module>
    cli()
  File "C:\Python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Python39\lib\site-packages\click\core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "C:\Python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Python39\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Tools\PlexTraktSync-0.9.15\plex_trakt_sync\cli.py", line 20, in cli
    sync()
  File "C:\Python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Tools\PlexTraktSync-0.9.15\plex_trakt_sync\commands\sync.py", line 138, in sync
    get_env_data()
  File "C:\Tools\PlexTraktSync-0.9.15\plex_trakt_sync\get_env_data.py", line 62, in get_env_data
    trakt_user = trakt.users.User('me')
  File "C:\Python39\lib\site-packages\trakt\users.py", line 222, in __init__
    self._get()
  File "C:\Python39\lib\site-packages\trakt\core.py", line 547, in inner
    json_data = self._handle_request('get', url)
  File "C:\Python39\lib\site-packages\trakt\core.py", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.OAuthException: Unauthorized - OAuth must be provided
```

### Workarounds

_Is there an existing workaround for this issue?_ **No**

### Environment

- Version: `0.9.15`
- Python version: `3.9.5` | trakt: `3.1.0`
- Platform: e.g. `Windows 10 21H1 | Build 19043.985 | using CMD terminal`

**Comment by akshay7394** [comment] 2021-06-02 09:08
Please let me know in case anyone's faced this issue before, I went through the issues and didn't recognise any as being related to this but I could be wrong. Or I could be doing something wrong that I haven't identified.

**Comment by glensc** [comment] 2021-06-02 12:03
try the new command:

```
./plex_trakt_sync.sh trakt-login
```

the old code will be unsupported once the new login commands have been integrated into the main flow.

also, consider editing your issue body and reformatting your bug report using blockquote to make it more readable:

    ```
    terminal
    output
    here 
    ```

**Comment by akshay7394** [comment] 2021-06-02 12:19
Thank you, I'll try this and report back. I've reformatted the bug report too.

**Comment by akshay7394** [comment] 2021-06-02 12:34
@glensc it seems to be the same issue even when using the new command. It gets stuck at the stage mentioned in my report, and after staying there for a few minutes, it shows this:

```
Your user code is: 4CCE24BC, please navigate to https://trakt.tv/activate to authenticate
The tokens have expired, restart the process
CRITICAL: Trakt authentication error: Unauthorized - OAuth must be provided
Traceback (most recent call last):
  File "C:\Tools\PlexTraktSync-0.9.15\main.py", line 6, in <module>
    cli()
  File "C:\Python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Tools\PlexTraktSync-0.9.15\plex_trakt_sync\commands\trakt_login.py", line 45, in trakt_login
    user = api.me.username
  File "C:\Tools\PlexTraktSync-0.9.15\plex_trakt_sync\decorators\nocache.py", line 10, in inner
    return method(self, *args, **kwargs)
  File "C:\Tools\PlexTraktSync-0.9.15\plex_trakt_sync\decorators\rate_limit.py", line 22, in wrapper
    return fn(*args, **kwargs)
  File "C:\Tools\PlexTraktSync-0.9.15\plex_trakt_sync\trakt_api.py", line 66, in me
    raise e
  File "C:\Tools\PlexTraktSync-0.9.15\plex_trakt_sync\trakt_api.py", line 63, in me
    return trakt.users.User('me')
  File "C:\Python39\lib\site-packages\trakt\users.py", line 222, in __init__
    self._get()
  File "C:\Python39\lib\site-packages\trakt\core.py", line 547, in inner
    json_data = self._handle_request('get', url)
  File "C:\Python39\lib\site-packages\trakt\core.py", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.OAuthException: Unauthorized - OAuth must be provided
```


And just to reiterate - it's not that it showed me the activation link and I waited for it to time out; it didn't show me the link or the activation code _until_ it showed me the error saying that the tokens had timed out.

**Comment by glensc** [comment] 2021-06-02 13:02
@akshay7394 for your safety you must invalidate all the tokens you have posted publicly to this issue. and edit all posts to remove them now. also, your issue body now lacks closing 'tag', ie. run-away code block is there.

anyone can impersonate you with your tokens. that's the point of the tokens.

however, I don't know how to invalidate plex token. chane plex password? delete plex server?

also, you shouldn't leak your plex server-id either.

**Comment by glensc** [comment] 2021-06-02 13:06
@akshay7394 also, please update the second post output to include the complete output of the script (obfuscate some details for privacy).

also, what version of have `trakt` package you installed (`pip3 list`) or you used `pipenv`?

**Comment by akshay7394** [comment] 2021-06-02 13:15
> @akshay7394 for your safety you must invalidate all the tokens you have posted publicly to this issue. and edit all posts to remove them now. also, your issue body now lacks closing 'tag', ie. run-away code block is there.

No problem, the tokens in my first post have all been altered to gibberish for safety, same with any IP Addresses mentioned. Thank you for the warning though, will release any Plex/Trakt tokens just in case, to be safe.

> also, what version of have trakt package you installed (pip3 list) or you used pipenv?

I used `pip3 install -r requirements.txt` when installing.

>@akshay7394 also, please update the second post output to include the complete output of the script (obfuscate some details for privacy).

Done.

**Comment by glensc** [comment] 2021-06-02 13:43
@akshay7394 please try `./plex_trakt_sync.sh trakt-login`, I'm not going to support "the old way", not even looking at that old code. and leave some kind of indication where it waits, like `<!-- waits for 600seconds here`

also, the code expires because you didn't input the code soon enough? or to reproduce need some expired .pytrakt.json file?

**Comment by twolaw** [comment] 2021-06-02 14:05
> also, the code expires because you didn't input the code soon enough? 

The code is not displayed at the beginning of expiration time, so user cannot use it (1st post in Expected behavior)

@akshay7394 you didn't tell `trakt ` package version you used.

**Comment by akshay7394** [comment] 2021-06-02 14:30
> > also, the code expires because you didn't input the code soon enough? 
> 
> The code is not displayed at the beginning of expiration time, so user cannot use it (1st post in Expected behavior)

Yes exactly.


> @akshay7394 you didn't tell `trakt ` package version you used (assuming it's 3.1.0)

I'm unable to identify the version number, could you let me know how? I tried `trakt --version` but no luck.

I have installed all dependencies via `pip install -r requirements.txt`,  I assume `trakt` is installed with this?

**Comment by akshay7394** [comment] 2021-06-02 14:37
> > @akshay7394 please try `./plex_trakt_sync.sh trakt-login`, I'm not going to support "the old way", not even looking at that old code.
> 
> But the second I output that I shared **is** from the new command (i.e. `./plex_trakt_sync.sh trakt-login`). I will run the code again and share the entire output along with the command used, give me a few minutes.
> 
> > also, the code expires because you didn't input the code soon enough? or to reproduce need some expired .pytrakt.json file?
> 
> No, as I said at the end of my second post - it doesn't even display the code that I need to input **until** the error is displayed, both are appearing at the same time.
> 
> > and leave some kind of indication where it waits, like `<!-- waits for 600seconds here`
> > I have added `<!-- waits for 600seconds here` to both code outputs.

```
$ ./plex_trakt_sync.sh trakt-login
Sign in to Trakt
If you do not have a client ID and secret. Please visit the following url to create them.
  https://trakt.tv/oauth/applications

Please enter your client id: bbf||||||||||||||||||||14c8b080a02d4fd952427367e2cdd415fc3227ef
Please enter your client secret: b975||||||||||||||||||||3841025129554b7588ef1caba198ceafa7c927
```


```
Your user code is: 3GGE21IT, please navigate to https://trakt.tv/activate to authenticate
The tokens have expired, restart the process
CRITICAL: Trakt authentication error: Unauthorized - OAuth must be provided
Traceback (most recent call last):
  File "C:\Tools\PlexTraktSync-0.9.15\main.py", line 6, in <module>
    cli()
  File "C:\Python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Tools\PlexTraktSync-0.9.15\plex_trakt_sync\commands\trakt_login.py", line 45, in trakt_login
    user = api.me.username
  File "C:\Tools\PlexTraktSync-0.9.15\plex_trakt_sync\decorators\nocache.py", line 10, in inner
    return method(self, *args, **kwargs)
  File "C:\Tools\PlexTraktSync-0.9.15\plex_trakt_sync\decorators\rate_limit.py", line 22, in wrapper
    return fn(*args, **kwargs)
  File "C:\Tools\PlexTraktSync-0.9.15\plex_trakt_sync\trakt_api.py", line 66, in me
    raise e
  File "C:\Tools\PlexTraktSync-0.9.15\plex_trakt_sync\trakt_api.py", line 63, in me
    return trakt.users.User('me')
  File "C:\Python39\lib\site-packages\trakt\users.py", line 222, in __init__
    self._get()
  File "C:\Python39\lib\site-packages\trakt\core.py", line 547, in inner
    json_data = self._handle_request('get', url)
  File "C:\Python39\lib\site-packages\trakt\core.py", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.OAuthException: Unauthorized - OAuth must be provided
```


@glensc - here's the output, including the command used at the beginning.

**Comment by twolaw** [comment] 2021-06-02 14:55
I cannot reproduce this bug with :
- Windows 10 20H2
- python 3.9
- PlexTraktSync 0.9.15
- trakt 3.0.0

As expected, I get the code as soon as I press Enter.

**Comment by twolaw** [comment] 2021-06-02 15:15
> I used `pip3 install -r requirements.txt` when installing.

I see that you run **pip3** and **python**.

Be aware that on Windows 10, if you run **python** or **python3** it is not the same version.
Make sure that pip3 will install correct dependencies for both the python and python3 commands.

Exemple on my Windows computer :
```
> python --version
Python 3.9.5
> python3 --version
Python 3.8.10
```

Instructions for trakt version check were given by glensc :
> also, what version of have trakt package you installed (**pip3 list**) or you used pipenv?

**Comment by akshay7394** [comment] 2021-06-02 16:34
> > I used `pip3 install -r requirements.txt` when installing.
> 
> I see that you run **pip3** and **python**.
> 
> Be aware that on Windows 10, if you run **python** or **python3** it is not the same version.
> Make sure that pip3 will install correct dependencies for both the python and python3 commands.
> 
> Exemple on my Windows computer :
> 
> ```
> > python --version
> Python 3.9.5
> > python3 --version
> Python 3.8.10
> ```
> 
> Instructions for trakt version check were given by glensc :
> 
> > also, what version of have trakt package you installed (**pip3 list**) or you used pipenv?

Sorry that was a typo for me, i just copy-pasted. I used `pip install -r requirements.txt`. Python3 and pip3 are both not installed on my computer, sorry about the wrong information.

> Instructions for trakt version check were given by glensc :
>
> > also, what version of have trakt package you installed (pip3 list) or you used pipenv?

Oh, I missed that. Here is my trakt version: `trakt              3.1.0`

**Comment by glensc** [comment] 2021-06-05 07:43
I can not reproduce this either. 

```
./plex_trakt_sync.sh trakt-login
```

- Python 3.9 from Brew
- PlexTraktSync 0.9.18
- trakt 3.1.0

Perhaps it's a terminal issue? what is the terminal you use? try other terminals?

**Comment by glensc** [comment] 2021-06-05 07:54
What the login process does, is call `trakt.init`:

what tries to validate the code in the loop:
- https://github.com/moogar0880/PyTrakt/blob/b91d3ed1876f81e849a6331bd28b3c4a6d2d9ddb/trakt/core.py#L327-L343

and the `get_device_code` is what does `print()` it to the screen:
- https://github.com/moogar0880/PyTrakt/blob/b91d3ed1876f81e849a6331bd28b3c4a6d2d9ddb/trakt/core.py#L229-L233

so, seems `print()` is jerky for the OP?

**Comment by glensc** [comment] 2021-06-05 07:58
oh, and terminology wise the user bug report is about that they don't see trakt code (device auth code), not trakt token.

**Comment by glensc** [comment] 2021-06-19 16:29
Since it can't be reproduced, there's nothing to fix.

**Closed by glensc** 2021-06-19 16:29 UTC
Labels: bug
