### ISSUE TITLE
Can't Sync after initial setup

### ISSUE THREAD

**Issue by GingerGuy118** [Taxel/PlexTraktSync#1055] opened 2022-09-12 22:37 UTC
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

I didn't even get to use the Program, after the login when I entered the Plex credentials and the trakt client ID and secret it gives me many errors which I don't really understand
I used pipx to install the program as well as the windows installer and both didn't seem to work

### Error trace / logs

```text
INFO     PlexTraktSync [0.21.4]
WARNING  No response from https://10-100-102-103.a71b8839a77e43018810941ed07b7509.plex.direct:32400, connection using local url http://localhost:32400
INFO     Sync Movie sections: [<PlexLibrarySection:movie:Movies>, <PlexLibrarySection:movie:NotPron>]
INFO     Sync Show sections: [<PlexLibrarySection:show:TV Shows>]
Traceback (most recent call last):
  File "c:\users\ozatt\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ozatt\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\ozatt\.local\bin\plextraktsync.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "C:\Users\ozatt\.local\pipx\venvs\plextraktsync\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ozatt\.local\pipx\venvs\plextraktsync\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\ozatt\.local\pipx\venvs\plextraktsync\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ozatt\.local\pipx\venvs\plextraktsync\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ozatt\.local\pipx\venvs\plextraktsync\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\ozatt\.local\pipx\venvs\plextraktsync\lib\site-packages\plextraktsync\cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "C:\Users\ozatt\.local\pipx\venvs\plextraktsync\lib\site-packages\plextraktsync\commands\sync.py", line 58, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "C:\Users\ozatt\.local\pipx\venvs\plextraktsync\lib\site-packages\plextraktsync\sync.py", line 83, in sync
    listutil.addList(lst["username"], lst["listname"])
  File "C:\Users\ozatt\.local\pipx\venvs\plextraktsync\lib\site-packages\plextraktsync\trakt_list_util.py", line 88, in addList
    self.lists.append(TraktList(username, listname))
  File "C:\Users\ozatt\.local\pipx\venvs\plextraktsync\lib\site-packages\plextraktsync\trakt_list_util.py", line 47, in __init__
    for elem in LazyUserList._get(listname, username)._items
  File "C:\Users\ozatt\.local\pipx\venvs\plextraktsync\lib\site-packages\trakt\core.py", line 554, in inner
    return generator.send(json_data)
  File "C:\Users\ozatt\.local\pipx\venvs\plextraktsync\lib\site-packages\plextraktsync\trakt_list_util.py", line 35, in _get
    ulist = LazyUserList(creator=creator, **data)
TypeError: __new__() got an unexpected keyword argument 'type'
```

### Expected behavior

Should start scanning and syncing my conent from trakt to plex

### Steps to reproduce the behavior

Open CMD
Enter plextraktsync

### Install method

pipx (Recommended)

### Version

0.21.4

### Python Version

3.7.0

### Operating System and Version

Windows-11

**Comment by twolaw** [comment] 2022-09-13 06:52
>I have checked if identical issue already exists

Really?

Duplicate of #941

**Closed by twolaw** 2022-09-13 06:52 UTC
