### ISSUE TITLE
Lists not syncing TV Shows fully

### ISSUE THREAD

**Issue by Macphee** [Taxel/PlexTraktSync#901] opened 2022-05-03 10:48 UTC
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [ ] I have checked if identical issue already exists

### The problem

I'm not sure if this is a PlexTraktSync side issue or just a plex side but I've just noticed that some lists are not getting synced fully.
When syncing lists from trakt.tv to plex, if the list contains complete seasons rather than individue episodes, the complete seasons wont be synced into the playlist. Any individual episodes still get synced.

![Trakt List](https://user-images.githubusercontent.com/5205739/166438814-cf0a664d-bbb2-4294-8efa-a7f750e96c04.png)
![Plex Playlist](https://user-images.githubusercontent.com/5205739/166438809-8ecf5be1-0255-4fe0-b75a-c9da22e93e89.png)

### Error trace / logs

```text
2022-05-03 01:02:24,399 INFO[PlexTraktSync]:Added to list Stargate Canonically Chronological Viewing Order.: <Show:40545:Stargate-Atlantis>: s05e10
2022-05-03 01:02:24,433 INFO[PlexTraktSync]:Added to list Stargate Canonically Chronological Viewing Order.: <Show:40545:Stargate-Atlantis>: s05e11
2022-05-03 01:02:24,466 INFO[PlexTraktSync]:Added to list Stargate Canonically Chronological Viewing Order.: <Show:40545:Stargate-Atlantis>: s05e12
2022-05-03 01:02:24,499 INFO[PlexTraktSync]:Added to list Stargate Canonically Chronological Viewing Order.: <Show:40545:Stargate-Atlantis>: s05e13
2022-05-03 01:02:24,544 INFO[PlexTraktSync]:Added to list Stargate Canonically Chronological Viewing Order.: <Show:40545:Stargate-Atlantis>: s05e14
2022-05-03 01:02:25,131 INFO[PlexTraktSync]:Added to list Stargate Canonically Chronological Viewing Order.: <Show:40545:Stargate-Atlantis>: s05e15
2022-05-03 01:02:25,720 INFO[PlexTraktSync]:Added to list Stargate Canonically Chronological Viewing Order.: <Show:40545:Stargate-Atlantis>: s05e16
2022-05-03 01:02:25,766 INFO[PlexTraktSync]:Added to list Stargate Canonically Chronological Viewing Order.: <Show:40545:Stargate-Atlantis>: s05e17
2022-05-03 01:02:25,801 INFO[PlexTraktSync]:Added to list Stargate Canonically Chronological Viewing Order.: <Show:40545:Stargate-Atlantis>: s05e18
2022-05-03 01:02:25,836 INFO[PlexTraktSync]:Added to list Stargate Canonically Chronological Viewing Order.: <Show:40545:Stargate-Atlantis>: s05e19
2022-05-03 01:02:25,874 INFO[PlexTraktSync]:Added to list Stargate Canonically Chronological Viewing Order.: <Show:40545:Stargate-Atlantis>: s05e20
2022-05-03 01:02:36,518 INFO[PlexTraktSync]:Added to list Stargate Canonically Chronological Viewing Order.: <Show:40656:Stargate-SG-1>: s08e01
2022-05-03 01:02:36,540 INFO[PlexTraktSync]:Added to list Stargate Canonically Chronological Viewing Order.: <Show:40656:Stargate-SG-1>: s08e02
2022-05-03 01:02:36,571 INFO[PlexTraktSync]:Added to list Stargate Canonically Chronological Viewing Order.: <Show:40656:Stargate-SG-1>: s08e03
2022-05-03 01:02:36,609 INFO[PlexTraktSync]:Added to list Stargate Canonically Chronological Viewing Order.: <Show:40656:Stargate-SG-1>: s08e04
2022-05-03 01:02:36,656 INFO[PlexTraktSync]:Added to list Stargate Canonically Chronological Viewing Order.: <Show:40656:Stargate-SG-1>: s08e05
2022-05-03 01:02:36,698 INFO[PlexTraktSync]:Added to list Stargate Canonically Chronological Viewing Order.: <Show:40656:Stargate-SG-1>: s08e06
2022-05-03 01:02:36,730 INFO[PlexTraktSync]:Added to list Stargate Canonically Chronological Viewing Order.: <Show:40656:Stargate-SG-1>: s08e07
2022-05-03 01:02:36,792 INFO[PlexTraktSync]:Added to list Stargate Canonically Chronological Viewing Order.: <Show:40656:Stargate-SG-1>: s08e08
```

### Expected behavior

Complete season in list should be synced to playlist

### Steps to reproduce the behavior

1. Create/find Trakt list that contains full seasons
2. Run python3 -m plextraktsync
3. Check if full season have been synced into play list

### Workarounds

Recreating the list with all individual episodes is all i have been able to get working so far.

### Install method

docker-compose

### Version

0.19.1

### Python Version

3.10.0

### Operating System and Version

Unraid 6.9.2

**Comment by twolaw** [comment] 2022-05-03 13:11
You haven't checked if identical issue already exists.

Duplicate of :
- https://github.com/Taxel/PlexTraktSync/issues/531

**Comment by twolaw** [comment] 2022-05-05 18:05
> As I was sure this use to be a feature I figuered this was best listed as a bug. Though perhaps a feature request would be better?

Yes it's a kind of feature request to flatten any `show` or `season` found in lists instead of skipping them.
My opinion is that maybe the better Plex representation of such (not flat) lists are Plex [Collections](https://github.com/Taxel/PlexTraktSync/discussions/134). But I'm not a Plex expert.

I was just pointing to the subject where we already talked about it.
If someone send a pull request to improve playlists processing in any way, I see no problem to accept it if it's correctly implemented.

**Closed** 2022-06-14 16:02 UTC
