### ISSUE TITLE
Trakt to Plex - Shows rating not working

### ISSUE THREAD

**Issue by Danavans** [Taxel/PlexTraktSync#707] opened 2022-01-10 16:07 UTC
### The problem

Hi,

I love your app, but the shows rating don't work when i try to pull from trakt to plex.
Everything sync perfectly (watched status, movie rating, even episodes rating) but the rating of the overall show don't want to sync.

I tried with pipx and classic windows 10 installation, same problem on both.

I was hoping the new 0.18.3 will fix it, but apparently not.
I am not an expert, so I will not be able to fix it, I just wanted to point out this bug, if someone could fix it it would be great.

Thanks again for your good work :)

### Expected behavior

Shows rating display on plex's show description

### Install method

pipx (Recommended)

### Version

0.18.3

### Python Version

3.9.2

### Operating System and Version

Windows 10

**Comment by glensc** [comment] 2022-01-10 19:35
1. has this ever worked? is such thing implemented?
2. did you try downgrading to see if it works with older versions?

**Comment by glensc** [comment] 2022-01-10 19:37
> I was hoping the new 0.18.3 will fix it, but apparently not.

why it should be fixed? was this even reported/requested? if you have links to issues/discussions/pr's, do share links to them!

**Comment by Danavans** [comment] 2022-01-10 20:40
> 1. has this ever worked? is such thing implemented?
> 
>     2. did you try downgrading to see if it works with older versions?

Tbh I don't know. I just supposed it was a thing as the sync works for everything except tv show rating. It even works for tv episode, but not for the show itself, it was strange to me that you implemented episode rating but not the tv show rating.
If it's not a thing, I would love to be that implemented, if possible.

Like i said I am just a simple user and don't know anything about coding, so I don't know if it was implemented in the first place.

I actually try with an older version, and it didn't works. Maybe I should try with a older one.

But it was odd to me nobody talk about it before, because I didn't see any message about that.
I only use this app to pull data from trakt to plex. I am trakt vip and plex pass user, so the other way i don't need it.
So it would be awesome if someone could implement this in the future.

Thanks for your reply.

**Comment by glensc** [comment] 2022-01-10 21:56
> But it was odd to me nobody talk about it before

they have been talking. I personally have not paid attention as I'm not using ratings.

>  I don't know if it was implemented in the first place.

I don't know either, as I don't know that part of the code. hence the question. it might have worked, but got broken with recent releases. as I repeat: I don't use the feature, so not familiar with it.

**Comment by murmelbahn** [comment] 2022-01-13 13:09
This would be a cool feature! I also would like to have this possible!

**Comment by glensc** [comment] 2022-01-13 15:14
so it's now confirmed it never existed? I don't see reports of testing with older versions here.

**Comment by Danavans** [comment] 2022-01-14 00:43
I tried with the 0.17.0 from the 5 of december, and who is a Verified version apparently, and it's not working.

**Comment by glensc** [comment] 2022-01-14 09:26
Indeed, the code iterates over episodes:
- https://github.com/Taxel/PlexTraktSync/blob/9f88aac4d5554fea7544522292235461faa3711b/plextraktsync/sync.py#L74-L78

so, there's never a `show` object to apply ratings check on.

doesn't seem there's any other way to walk over shows twice, or add own command to sync ratings or own command to sync show ratings. any other ideas?

**Comment by glensc** [comment] 2022-01-14 09:32
also, have you checked (manually) this is actually working as you expect:
- you can rate a show in trakt (rates show and episodes separately)
- you can rate a show in plex (rates show and episodes separately)

perhaps any of the implementations just rather all episodes the same if you rate a show?

**Comment by glensc** [comment] 2022-01-15 08:53
https://github.com/Taxel/PlexTraktSync/pull/720 give feedback

**Comment by Danavans** [comment] 2022-01-15 14:11
> #720 give feedback

Hi  glensc, thanks for taking care of it :)
I tried with the new update 0.18.8, and it still doesn't work, unfortunately.
I update with  "pipx upgrade PlexTraktSync" and even delete the cache files, still no rating of the shows on Plex.

Do have I to do something special to test your new code or is it already part of the new update 0.18.8 ?
Like I told you before, I am not an expert :)

**Comment by glensc** [comment] 2022-01-15 16:24
I asked to give feedback on proposed changes of #720, not 0.18.8

**Comment by Danavans** [comment] 2022-01-15 16:56
OK, then I will not be useful, sorry. But it looks promising ;)

**Comment by glensc** [comment] 2022-01-15 19:41
Well. I won't merge https://github.com/Taxel/PlexTraktSync/pull/720 until someone confirms it works.

**Comment by agneevX** [comment] 2022-02-04 07:17
I can confirm that the linked PR works as intended, the show rating is pulled immediately after the episode ratings are pulled:

```sh
ubuntu@oracle1 ~/scripts [1]> ./trakt_run.sh sync --show "Big Sky (2020)"
INFO: PlexTraktSync [unknown]
WARNING: No response from http://10.0.0.11:32400, fallback to http://falcon.tailnet-d10c.ts.net:32400
Sync Shows: [<Show:58636:Big-Sky-(2020)>]
INFO: Rating <tmdb:3076775:<Episode:79750:Big-Sky-(2020)-s02e01>> with 8 on Plex
INFO: Rating <tmdb:3204871:<Episode:79785:Big-Sky-(2020)-s02e02>> with 8 on Plex
INFO: Rating <tmdb:3245050:<Episode:79954:Big-Sky-(2020)-s02e03>> with 8 on Plex
INFO: Rating <tmdb:3253622:<Episode:80265:Big-Sky-(2020)-s02e04>> with 8 on Plex
INFO: Rating <tmdb:3297277:<Episode:80856:Big-Sky-(2020)-s02e05>> with 8 on Plex
INFO: Rating <tmdb:3329566:<Episode:81022:Big-Sky-(2020)-s02e06>> with 8 on Plex
INFO: Rating <tmdb:3335734:<Episode:95723:Big-Sky-(2020)-s02e07>> with 8 on Plex
INFO: Rating <tmdb:3350389:<Episode:95912:Big-Sky-(2020)-s02e08>> with 7 on Plex
Processing shows 100% ━━━━━━━━━━━━━━━━━━━━━━ 1/1  [ 0:00:07 < 0:00:00 , ? it/s ]
INFO: Rating <tmdb:100010:<Show:58636:Big-Sky-(2020)>> with 8 on Plex
Syncing show ratings 100% ━━━━━━━━━━━━━━━━━━ 1/1  [ 0:00:00 < 0:00:00 , ? it/s ]
INFO: Updated plex watchlist in 0.0 seconds
INFO: Completed full sync in 8.2 seconds
```

**Comment by glensc** [comment] 2022-02-04 09:17
@agneevX: can you test having episodes with different ratings than show?

as I asked this, but nobody confirmed:
- https://github.com/Taxel/PlexTraktSync/issues/707#issuecomment-1012954241

**Comment by agneevX** [comment] 2022-02-04 09:44
> can you test having episodes with different ratings than show?

Do you mean where the show rating is different from the ratings of every episode in the series?

**Comment by glensc** [comment] 2022-02-04 10:54
> > can you test having episodes with different ratings than show?
> 
> Do you mean where the show rating is different from the ratings of every episode in the series?

yes, what I asked in this comment:
- https://github.com/Taxel/PlexTraktSync/issues/707#issuecomment-1012954241

**Comment by agneevX** [comment] 2022-02-04 13:50
Seems to work:

```sh
ubuntu@oracle1 ~> ./scripts/trakt_run.sh sync --show "Dexter: New Blood"
INFO: PlexTraktSync [unknown]
WARNING: No response from http://10.0.0.11:32400, fallback to http://falcon.tailnet-d10c.ts.net:32400
Sync Shows: [<Show:80877:Dexter:-New-Blood>]
INFO: Rating <tmdb:3151078:<Episode:80879:Dexter:-New-Blood-s01e01>> with 8 on Plex
INFO: Rating <tmdb:3253568:<Episode:80925:Dexter:-New-Blood-s01e02>> with 7 on Plex
INFO: Rating <tmdb:3253569:<Episode:81067:Dexter:-New-Blood-s01e03>> with 7 on Plex
INFO: Rating <tmdb:3253570:<Episode:81331:Dexter:-New-Blood-s01e04>> with 7 on Plex
INFO: Rating <tmdb:3319606:<Episode:95629:Dexter:-New-Blood-s01e05>> with 8 on Plex
INFO: Rating <tmdb:3319607:<Episode:95741:Dexter:-New-Blood-s01e06>> with 8 on Plex
INFO: Rating <tmdb:3319608:<Episode:95926:Dexter:-New-Blood-s01e07>> with 8 on Plex
INFO: Rating <tmdb:3319609:<Episode:96047:Dexter:-New-Blood-s01e08>> with 7 on Plex
INFO: Rating <tmdb:3359217:<Episode:96088:Dexter:-New-Blood-s01e09>> with 8 on Plex
INFO: Rating <tmdb:3359218:<Episode:96222:Dexter:-New-Blood-s01e10>> with 4 on Plex
Processing shows 100% ━━━━━━━━━━━━━━━━━━━━━━ 1/1  [ 0:00:05 < 0:00:00 , ? it/s ]
INFO: Rating <tmdb:131927:<Show:80877:Dexter:-New-Blood>> with 6 on Plex
Syncing show ratings 100% ━━━━━━━━━━━━━━━━━━ 1/1  [ 0:00:00 < 0:00:00 , ? it/s ]
INFO: Updated plex watchlist in 0.0 seconds
INFO: Completed full sync in 6.0 seconds
```

However, season ratings do not sync, which I assume is not a feature request yet?

**Closed** 2022-02-04 18:07 UTC

**Comment by glensc** [comment] 2022-02-04 18:08
https://github.com/Taxel/PlexTraktSync/pull/720 as 0.18.17

**Comment by glensc** [comment] 2022-02-04 19:04
Don't forget to submit pull request to document new features.
