### ISSUE TITLE
Can't sync due to UserList.__new__() got an unexpected keyword argument 'type'

### ISSUE THREAD

**Issue by Mirabis** [Taxel/PlexTraktSync#1013] opened 2022-08-25 20:33 UTC
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

After logging in and getting Trakt/Plex tokens I can only use 'plextraktsync watch' but none of the sync options.
I've tried multiple formats:
- plextraktsync sync --sync=shows
- plextraktsync sync --sync=movies
- plextraktsync sync

All of them result into the same error which I pasted at Error trace / logs. 

I'm running it on a Mac M1 (14") ARM machine. plextraktsync info gives:
```text
PlexTraktSync Version: 0.20.10
Python Version: 3.10.6 (main, Aug 11 2022, 13:36:31) [Clang 13.1.6 (clang-1316.0.21.2.5)]
Plex API Version: 4.12.0
Trakt API Version: 3.4.0
Cache Dir: /Users/mirabis/Library/Caches/PlexTraktSync
Config Dir: /Users/mirabis/Library/Application Support/PlexTraktSync
Log Dir: /Users/mirabis/Library/Logs/PlexTraktSync
Plex username: Mirabis
Trakt username: Mirabis
Plex Server version: 1.28.1.6104-788f82488, updated at: 2022-08-25 05:10:07
Enabled 7 libraries in Plex Server: ['4K Movies', 'Kids Movies', 'Movies', '4K Shows', 'Anime', 'Kids TV', 'TV Shows']`
```
### Error trace / logs

```text
Traceback (most recent call last):
  File "/Users/mirabis/.local/bin/plextraktsync", line 8, in <module>
    sys.exit(cli())
  File "/Users/mirabis/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mirabis/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/mirabis/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mirabis/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mirabis/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mirabis/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/plextraktsync/cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "/Users/mirabis/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/plextraktsync/commands/sync.py", line 60, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/Users/mirabis/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/plextraktsync/sync.py", line 64, in sync
    listutil.addList(lst["username"], lst["listname"])
  File "/Users/mirabis/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/plextraktsync/trakt_list_util.py", line 88, in addList
    self.lists.append(TraktList(username, listname))
  File "/Users/mirabis/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/plextraktsync/trakt_list_util.py", line 47, in __init__
    for elem in LazyUserList._get(listname, username)._items
  File "/Users/mirabis/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/trakt/core.py", line 554, in inner
    return generator.send(json_data)
  File "/Users/mirabis/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/plextraktsync/trakt_list_util.py", line 35, in _get
    ulist = LazyUserList(creator=creator, **data)
TypeError: UserList.__new__() got an unexpected keyword argument 'type'
```

### Expected behavior

Expected behaviour would be the start of the synchronisation.

### Steps to reproduce the behavior

1. Install with pipx
2. run plextraktsync and follow wizard for authentication
3. Plex username + password + 2FA token
4. Authenticated, select user (Mirabis)
5. Trakt API set-up (client ID & Secret)
6. Select libraries (default all)
7. run sync

### Workarounds

No workaround but the Plex Server is named "Moreno+" which ('+') might be the root of the issue.

### Install method

pipx (Recommended)

### Version

0.20.10

### Python Version

3.10.6

### Operating System and Version

macOS-12.5.1

**Comment by glensc** [comment] 2022-08-25 20:39
Duplicate of https://github.com/Taxel/PlexTraktSync/issues/941

**Closed by glensc** 2022-08-25 20:39 UTC

**Comment by Mirabis** [comment] 2022-08-25 20:41
I looked at that issue prior to making a new one. Mine specifically lists `UserList.__new__() got an unexpected keyword argument 'type' `while his/her lists `__new__() got an unexpected keyword argument 'type'`
