### ISSUE TITLE
Trakt played status not synced to Plex anymore

### ISSUE THREAD

**Issue by thle** [Taxel/PlexTraktSync#104] opened 2021-01-22 12:56 UTC
Hi,
since some time the information about a movie/episode played already in Trakt.tv is not synchronized to Plex anymore. Maybe some recent Plex version broke this?
How can I debug?

Thanks

**Comment by twolaw** [comment] 2021-01-22 19:23
Hi,
Could you set log_debug_messages to true in config.json, run script and then show content of last_update.log please.

**Comment by thle** [comment] 2021-01-25 21:19
Ok, loading from Trakt seems fine, but then when processing Plex this happens:

```
2021-01-25 21:36:45,221 INFO:Loaded Trakt lists.
2021-01-25 21:36:45,223 DEBUG:Starting new HTTPS connection (1): **-**-**-**.***********************************.plex.direct:32400
2021-01-25 21:37:15,304 DEBUG:Starting new HTTP connection (1): localhost:32400
2021-01-25 21:37:15,310 DEBUG:http://localhost:32400 "GET / HTTP/1.1" 200 3582
2021-01-25 21:37:15,312 WARNING:No response from https://**-**-**-**.***********************************.plex.direct:32400, fallback to http://localhost:32400
2021-01-25 21:37:15,312 INFO:Server version 1.21.1.3876-3c3adfcb4 updated at: 2021-01-25 20:34:14
2021-01-25 21:37:15,316 DEBUG:http://localhost:32400 "GET /library HTTP/1.1" 200 289
...
2021-01-25 21:37:15,989 DEBUG:http://localhost:32400 "GET /library/sections HTTP/1.1" 200 1271
2021-01-25 21:37:18,439 DEBUG:http://localhost:32400 "GET /library/sections/1/all HTTP/1.1" 200 1757985
2021-01-25 21:37:29,170 INFO:Now working on movie section   Filme containing 3173 elements
2021-01-25 21:37:29,170 ERROR:Movie [***** (2009)]: Unrecognized GUID plex://movie/5d77683861141d001fb15f0e
2021-01-25 21:37:29,171 ERROR:Movie [***** (1995)]: Unrecognized GUID plex://movie/5d7768306f4521001ea9b3f4
2021-01-25 21:37:29,171 ERROR:Movie [***** (2003)]: Unrecognized GUID plex://movie/5d7768265af944001f1f6977
2021-01-25 21:37:29,171 ERROR:Movie [***** (2013)]: Unrecognized GUID plex://movie/5d7769a023d5a3001f4fa465
2021-01-25 21:37:29,171 ERROR:Movie [***** (1994)]: Unrecognized GUID plex://movie/5d77683585719b001f3a3cd0
```
and so on. TV shows seem to work fine btw

**Comment by twolaw** [comment] 2021-01-25 21:59
This is a duplicate of #56

**Closed** 2021-01-26 13:35 UTC
