### ISSUE TITLE
Feature request: Hama.Bundle (anidb|tvdb guid) support

### ISSUE THREAD

**Issue by BitterSweetcandyshop** [Taxel/PlexTraktSync#1476] opened 2023-05-05 08:20 UTC
### Feature description
I notice that the moment it hit my anime collections, which I use [Hama](https://github.com/ZeroQI/Hama.bundle) for, due to it being more reliable and feature rich.

### Use case
Anyone else also using hama

### Workarounds
To not use hama

### Plan to implement
I do not plan to implement this myself as I have no time and have my own half baked project I'm working on.
I also have taken no time to look at the code

I'm unsure if this is of help, but here:
```
<Show:55644:.hack//SIGN>: Unable to parse a valid provider from guid<PlexGuid:com.plexapp.agents.hama://anidb-24?lang=da>
```
and the corresponding valid anidb url is:  https://anidb.net/anime/24
then hama also uses tvdb:
```
<Show:14497:Dr.-Stone>: Unable to parse a valid provider from guid <PlexGuid:com.plexapp.agents.hama://tvdb-355774?lang=da>
```
same structure as anidb: http://www.thetvdb.com/?tab=series&id=355774

**Comment by twolaw** [comment] 2023-05-05 08:29
Duplicate of #1018 ?

**Closed** 2023-05-05 12:22 UTC
Labels: enhancement
