### ISSUE TITLE
Receiving Random Internal Server Errors

### ISSUE THREAD

**Issue by dietrichmd** [Taxel/PlexTraktSync#7] opened 2019-11-17 21:50 UTC
The script processes my movies (400) and Documentaries (150) sections just fine, but when it gets to the TV section (about 900 or so) it errors out randomly with Internal Server Error.

I'm assuming this is on Trakat's side, but in case there is a per-call limit, may want to break the query up.

Screenshot of errors:  https://i.imgur.com/mVWlt1A.png
Screenshot of the output of tail last_update.log:  https://i.imgur.com/vls1mYk.png

Cheers

**Comment by Dukko** [comment] 2019-11-17 22:52
Experiencing something similar. I have a feeling it is related to TVDB issues with Plex in the last few weeks, not pulling posters etc.

**Comment by Taxel** [comment] 2019-11-20 00:05
Since [there does not seem to be a call limit](https://github.com/trakt/api-help/issues/39) and if there were, it could (thanks to caching most Trakt API calls) be circumvented by simply running the script multiple times with some time in between runs, I am closing this.
If you can add some information that allows reproducing this issue, it may be reopened.

**Closed by Taxel** 2019-11-20 00:05 UTC
