### ISSUE TITLE
HDR metadata not being sent to Trakt collection

### ISSUE THREAD

**Issue by rfgamaral** [Taxel/PlexTraktSync#572] opened 2021-11-02 19:03 UTC
### The problem

I have lots of HDR movies in my collection, but the HDR information is not being set to Trakt for **any of them**.

Python is not really my thing, but I did a quick debugging and I believe the `hdr` function ([ref](https://github.com/Taxel/PlexTraktSync/blob/1063441838310229d1fee5061500a2069685f4c7/plex_trakt_sync/plex_api.py#L291)) is always returning `None` for all my movies.

### Expected behavior

HDR metadata should be sent with `plex_to_trakt.collection: true`.

### Install method

docker-compose

### Version

0.15.10

### Python Version

3.10.0

### Operating System and Version

GNU/Linux synology_apollolake_918+

**Comment by glensc** [comment] 2021-11-02 19:22
HDR is not my thing, but this is the PR that added the info extraction:
- https://github.com/Taxel/PlexTraktSync/pull/366

maybe there are details on how the extraction was designed.

you probably should come up with a solution yourself, add `pprint` to the function you referred to, and use `inspect` command to call for specific media

```py
    def hdr(self):
        """
        Set to dolby_vision, hdr10, hdr10_plus, or hlg
        """
        from print import pprint
        from sys import exit

        pprint(self.item)
        exit(33)

        try:
            stream = self.item.media[0].parts[0].streams[0]
```

```
./plextraktsync.sh inspect 1234
```

**Comment by glensc** [comment] 2021-11-03 13:18
@rfgamaral it's good info, that allows to investigate this deeper. since the property is only accessed when submitting item to collection, it's probably okay to fetch item fully. but I'm rather surprised why it wasn't autoloader by plexapi in first place.

**Comment by rfgamaral** [comment] 2021-11-03 13:23
I don't know what that means, but I hope you can fix it 😅

**Comment by glensc** [comment] 2021-12-20 17:06
Do you have any sample HDR video to provide? I tried searching with Search Engine but got just HDR images...

**Comment by glensc** [comment] 2021-12-20 17:24
I'm unable to reproduce with latest version, perhaps it was fixed with https://github.com/Taxel/PlexTraktSync/pull/652

In any case, of you have the id that has issues, first run with inspect:

```
./plextraktsync.sh inspect 16284
```

then modify source to print only on that id:

```diff
--- a/plextraktsync/media.py
+++ b/plextraktsync/media.py
@@ -138,6 +138,9 @@ def resolve_any(self, pm: PlexLibraryItem, tm=None):
         return None

     def resolve_guid(self, guid: PlexGuid, tm=None):
+        if guid.id == "16284":
+            print(guid.pm.to_json())
+
         if guid.provider in ["local", "none", "agents.none"]:
             logger.warning(f"{guid.pm.item}: Skipping guid {guid} because provider {guid.provider} has no external Id")
```

for me it prints the same data:

```py
{'collected_at': '2021-12-20:T17:10:56.000Z', 'media_type': 'digital', 'resolution': 'uhd_4k', 'hdr': 'hdr10', 'audio': 'lpcm', 'audio_channels': '2.0'}```

**Comment by M1kep** [comment] 2022-03-30 19:07
It looks like I am also experiencing this issue, could somebody point me in the right direction of to identify the guid/ID of items in my Plex collection so I can try to take a deeper look?

**Comment by glensc** [comment] 2022-03-30 19:39
HDR exists as filter:
- https://support.plex.tv/articles/200392126-using-the-library-view/

**Comment by M1kep** [comment] 2022-03-31 02:01
Adding some information here.
 0/569 HDR movies were marked as HDR during the initial sync. If I run `plextraktsync sync --id <ID Here>` after commenting out the below lines, the HDR flag is properly set.

https://github.com/Taxel/PlexTraktSync/blob/main/plextraktsync/sync.py#L96-L97

**Comment by glensc** [comment] 2022-03-31 03:15
🚧 Never link to branches, share a permalink 🚧
- see https://news.ycombinator.com/item?id=8046710
  and https://help.github.com/articles/getting-permanent-links-to-files/
  and https://docs.gitlab.com/ee/user/shortcuts.html#project-files
- hit `y`
- and perhaps for https://github.com/josephfrazier/octopermalinker (GitHub)

NOTE: edit your post and fix it with a permalink!

**Comment by glensc** [comment] 2022-03-31 03:16
Also, add link to source using markdown list item (put link on it's own line with preceding "`- `" ), then github will render source code inline.

**Comment by M1kep** [comment] 2022-04-01 00:33
@glensc Thanks for the info, I've updated my response

**Comment by glensc** [comment] 2022-04-01 05:07
So the summary is, that somehow the XML from Plex API is different when running update via library vs updating single item

**Comment by M1kep** [comment] 2022-04-03 03:39
Pretty sure it's what was described above already:


From: @rfgamaral 
> @glensc After further debugging with your tips, I've noticed the following:
> 
> * Running the `inspect` commands gives the expected results for HDR streams
>   
>   * The `self.item.media[0].parts[0].streams[0]` in the `def hdr(self)` is a video stream as expected
>     `<AudioStream:27841:Atmos-7.1>,<AudioStream:27842:AC-3-5.1>(...)`
> * Syncing a collection always sends `'hdr': None` for any video file
>   
>   * The `self.item.media[0].parts[0].streams[0]` in the `def hdr(self)` does not exist (i.e., `'streams': []`)
> 
> In other words, when the `def hdr(self)` is called in the context of the `inspect` command, it works because the `streams` property is not empty, and the first item is the expected video stream. When called in the context of the collection sync command, it doesn't work because the `streams` property is an empty array.

Took a look this evening and providing my findings below:

Looking at the code, I'm thinking that when items are fetched from the sections the via `section.fetchItems`(Used for syncs that are item specific such as `plextraktsync sync` or `plextraktsync sync --movies`) it isn't doing to the same query as `library.fetchItem`(Used for `plextraktsync inspect`) or `section.fetchItem`(Used for `plextraksync --id <number>`). Was able to confirm this by making the following changes:

```diff
--- ./plextraktsync/plex_api_orig.py
+++ ./plextraktsync/plex_api.py
@@ -429,7 +429,10 @@
     @nocache
     def find_by_id(self, id: Union[str, int]) -> Optional[Union[Movie, Show, Episode]]:
         try:
-            return self.section.fetchItem(int(id))
+            item = self.section.fetchItem(int(id))
+            if item.key == "/library/metadata/161999":
+                print(f'Streams from section.fetchItem: {item.media[0].parts[0].streams}')
+            return item
         except NotFound:
             return None

@@ -456,6 +459,8 @@

     def items(self, max_items: int):
         for item in self.all(max_items):
+            if item.key == "/library/metadata/161999":
+                print(f'Streams from section.fetchItems: {item.media[0].parts[0].streams}')
             yield PlexLibraryItem(item, plex=self.plex)

     def __repr__(self):
@@ -499,6 +504,9 @@
             media = self.plex.library.fetchItem(key)
         except NotFound:
             return None
+
+        if media.key == "/library/metadata/161999":
+            print(f'Streams from library.fetchItem: {media.media[0].parts[0].streams}')

         return PlexLibraryItem(media)
```

Gives the following output for `plextraktsync sync --id 161999`
```
/app # plextraktsync sync --id 161999
INFO: PlexTraktSync [0.18.24]
<-- See here -->
Streams from section.fetchItem: [<VideoStream:953686>, <AudioStream:953687>, <SubtitleStream:953688:Danish>, <SubtitleStream:953689:English-[CC]>, <SubtitleStream:953690:European-Spanish-[CC>, <SubtitleStream:953691:European-Spanish>, <SubtitleStream:953692:European-Spanish>, <SubtitleStream:953693:Finish>, <SubtitleStream:953694:Norwegian>, <SubtitleStream:953695:Brazilian-Portuguese>, <SubtitleStream:953696:Swedish>]
Sync Movies: [<Movie:161999:8-Bit-Christmas>]
INFO: Downloaded List Trakt Watchlist
INFO: Downloaded List IMDB: Top Rated Movies
Processing movies 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/1  [ 0:00:01 < 0:00:00 , ? it/s ]
INFO: Updated plex watchlist in 0.0 seconds
INFO: Completed full sync in 2.8 seconds
```

Output for `plextraktsync inspect 161999`
```
/app # plextraktsync inspect 161999
PlexTraktSync [0.18.24]
<-- See here -->
Streams from library.fetchItem: [<VideoStream:953686>, <AudioStream:953687>, <SubtitleStream:953688:Danish>, <SubtitleStream:953689:English-[CC]>, <SubtitleStream:953690:European-Spanish-[CC>, <SubtitleStream:953691:European-Spanish>, <SubtitleStream:953692:European-Spanish>, <SubtitleStream:953693:Finish>, <SubtitleStream:953694:Norwegian>, <SubtitleStream:953695:Brazilian-Portuguese>, <SubtitleStream:953696:Swedish>]
Inspecting 161999: <tmdb:802217:<Movie:161999:8-Bit-Christmas>>
... SNIP INSPECT OUTPUT ...
```

Output from `plextraktsync sync --sync movies`
```
/app # plextraktsync sync --sync movies
INFO: PlexTraktSync [0.18.24]
Sync Movie sections: [<PlexLibrarySection:movie:Movies>]
INFO: Downloaded List Trakt Watchlist
INFO: Downloaded List IMDB: Top Rated Movies
<-- See here -->
Streams from section.fetchItems: []
INFO: Added to list IMDB: Top Rated Movies: <Movie:129166:12-Angry-Men>
... snip rest of output ...
```

**Comment by glensc** [comment] 2022-04-03 14:05
This branch should fix it:
- https://github.com/Taxel/PlexTraktSync/pull/870

**Closed** 2022-04-06 14:32 UTC
