### ISSUE TITLE
Marked as watched too early

### ISSUE THREAD

**Issue by agneevX** [Taxel/PlexTraktSync#530] opened 2021-10-09 10:31 UTC
### The problem

An episode was watched 81%, and a routine cron job marked it was watched on both on Plex and Trakt.

### Expected behavior

Don't mark as watched until its watched 95% (or until Plex deems it as watched).

### Steps to reproduce the behavior

_With a complete code example, if possible_

### Workarounds

_Is there an existing workaround for this issue?_

### Environment

- Version: 0.15.0
- Python version: 3.10.0
- Platform: Docker

**Comment by twolaw** [comment] 2021-10-09 10:58
Can you provide logs please.
The script does not mark as watched on both Plex and Trakt by itself.
It compares watch status between Plex and Trakt to make it equal.

**Comment by agneevX** [comment] 2021-10-09 11:10
> Can you provide logs please.

This happened last night as 10. Noticed this today morning, sadly erased, by the `watch` command or some other command execution.

> Do you use watch command too or just sync ?

I use `watch` command as a daemon, while `sync` runs as a cron job.

`0 22 * * * ping -qc 5 1.1.1.1 && docker run --rm -u "1001:1001" -e "TZ=Asia/Kolkata" -v /opt/appdata/plextraktsync:/app/config --name pts-sync ghcr.io/taxel/plextraktsync sync --no-progress-bar > /dev/null 2>&1`

```yml
version: "3.9"
services:
  plextraktsync:
    container_name: plextraktsync
    image: ghcr.io/taxel/plextraktsync
    restart: unless-stopped
    user: "1001:1001"
    command: "watch"
    healthcheck:
      test: ["CMD", "wget", "-nv", "-t1", "--spider", "10.0.0.11:32400/identity"]
    logging: 
      driver: none
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - /opt/appdata/plextraktsync:/app/config
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
```

**Comment by twolaw** [comment] 2021-10-09 11:11
> Once something hits 90%, it’s considered played. It's not configurable at the moment, I'm afraid

source : [Plex employee on reddit ](https://www.reddit.com/r/PleX/comments/n11wdo/how_does_plex_know_when_a_piece_of_media_is/gwaby7v/?context=3)

**Comment by twolaw** [comment] 2021-10-09 11:21
This means the movie was marked as watched in Trakt before the `sync` run.
Probably due to the `watch` command telling trakt your watch progression in real time.

What is the date and time of watched status on trakt.tv ?

**Comment by agneevX** [comment] 2021-10-09 12:42
This is really weird because in the past I've left off at >90% and it completed the scrobble after I resumed playback and finished it. 

So did Trakt mark it as watched after I finished it at 81%, then when the `sync` command ran, it pulled this to the Plex DB?

**Comment by glensc** [comment] 2021-10-10 12:36
Please use the issue template to fill issue

```
Environment

    Version:
    Python version:
    Platform: Docker latest
```

**Comment by agneevX** [comment] 2021-10-10 12:43
Not sure how to get that info, I'm running the latest image of the `latest` tag, as I mentioned.

**Comment by twolaw** [comment] 2021-11-09 20:55
As [said](https://github.com/Taxel/PlexTraktSync/issues/530#issuecomment-939286339), a video scrobbled above 80% of its duration is considered as watched by trakt.
There is no bug, this is the expected behaviour.

**Closed** 2021-11-09 21:09 UTC
