### ISSUE TITLE
Plex Watchlist sync?

### ISSUE THREAD

**Issue by Dukko** [Taxel/PlexTraktSync#876] opened 2022-04-05 14:31 UTC
Hi! Plex just added a watchlist feature, is there a way to sync Trakt's watchlist to this new feature?

I completely understand if this is too early or Plex doesn't expose that.

Thanks!

**Comment by twolaw** [comment] 2022-04-05 15:11
Yes this is very early, I don't know how this will be exposed in Plex API.
Maybe the [python-plexapi](https://github.com/pkkid/python-plexapi) library needs to be updated first.

Refs :
- [End the Streaming Struggle with Plex](https://www.plex.tv/blog/end-the-streaming-struggle-with-plex/) (Plex blog news 5-april-2022)
- [Universal Watchlist (beta)](https://support.plex.tv/articles/universal-watchlist-beta/) support page
- [Plex forum thread](https://forums.plex.tv/t/find-where-to-watch-something-with-discover-and-your-watchlist/782131) about this news

**Comment by Vansmak** [comment] 2022-04-05 17:01
> Hi! Plex just added a watchlist feature, is there a way to sync Trakt's watchlist to this new feature?
> 
> I completely understand if this is too early or Plex doesn't expose that.
> 
> Thanks!

came her to ask the same thing.  there is a beta watchlist sync in the settings oif the plugin, but it doesnt seen to do anything.  Also seems like the watchlist is on the clients, not on the server.

**Comment by Dukko** [comment] 2022-04-05 17:17
> > Plex just added a watchlist feature
> 
> 
> 
> Do share the link. I.e show what and where you obtained the information?

See response above but also [here](https://forums.plex.tv/t/find-where-to-watch-something-with-discover-and-your-watchlist/782131)

**Comment by Beersteddy** [comment] 2022-04-05 21:20
> > Hi! Plex just added a watchlist feature, is there a way to sync Trakt's watchlist to this new feature?
> > I completely understand if this is too early or Plex doesn't expose that.
> > Thanks!
> 
> came her to ask the same thing. there is a beta watchlist sync in the settings oif the plugin, but it doesnt seen to do anything. Also seems like the watchlist is on the clients, not on the server.

The watchlist on Plex works for me right now and is definitely stored on plex server (or account), not the device as I just switched in between them and the list was there.

**Comment by twolaw** [comment] 2022-04-05 21:27
Yes it's linked to plex account. That's why it doesn't work for managed users.

**Comment by Vansmak** [comment] 2022-04-05 22:02
> > > Hi! Plex just added a watchlist feature, is there a way to sync Trakt's watchlist to this new feature?
> > > I completely understand if this is too early or Plex doesn't expose that.
> > > Thanks!
> > 
> > 
> > came her to ask the same thing. there is a beta watchlist sync in the settings oif the plugin, but it doesnt seen to do anything. Also seems like the watchlist is on the clients, not on the server.
> 
> The watchlist on Plex works for me right now and is definitely stored on plex server (or account), not the device as I just switched in between them and the list was there.

Where do you see it in the server please?

**Comment by Beersteddy** [comment] 2022-04-05 22:19
> > > > Hi! Plex just added a watchlist feature, is there a way to sync Trakt's watchlist to this new feature?
> > > > I completely understand if this is too early or Plex doesn't expose that.
> > > > Thanks!
> > > 
> > > 
> > > came her to ask the same thing. there is a beta watchlist sync in the settings oif the plugin, but it doesnt seen to do anything. Also seems like the watchlist is on the clients, not on the server.
> > 
> > 
> > The watchlist on Plex works for me right now and is definitely stored on plex server (or account), not the device as I just switched in between them and the list was there.
> 
> Where do you see it in the server please?

Just go to https://www.plex.tv/ log in to your account and you should see the pop up.  
I did have a pop up on TV, Android app, windows app, literally all over the place. Hard to miss.
Possibly they just adding it slowly to more users.

![image](https://user-images.githubusercontent.com/91010735/161860190-a47043d3-42fb-4afc-86e3-596395287f42.png)

**Comment by Vansmak** [comment] 2022-04-05 23:18
> > > > > Hi! Plex just added a watchlist feature, is there a way to sync Trakt's watchlist to this new feature?
> > > > > I completely understand if this is too early or Plex doesn't expose that.
> > > > > Thanks!
> > > > 
> > > > 
> > > > came her to ask the same thing. there is a beta watchlist sync in the settings oif the plugin, but it doesnt seen to do anything. Also seems like the watchlist is on the clients, not on the server.
> > > 
> > > 
> > > The watchlist on Plex works for me right now and is definitely stored on plex server (or account), not the device as I just switched in between them and the list was there.
> > 
> > 
> > Where do you see it in the server please?
> 
> Just go to https://www.plex.tv/ log in to your account and you should see the pop up. I did have a pop up on TV, Android app, windows app, literally all over the place. Hard to miss. Possibly they just adding it slowly to more users.

well yeah, thats a web client.  not the server

**Comment by glensc** [comment] 2022-04-06 06:26
Submitted ticket for watchlist to plex api:
- https://github.com/pkkid/python-plexapi/issues/923

if such a thing is implemented ever here, it needs to have API there first.

**Comment by technomensch** [comment] 2022-04-11 22:37
If this ever gets implemented, can someone leave a note here too - https://forums.plex.tv/t/sync-watchlist-with-trakt/786101 ??  Thanks in advance.

**Comment by glensc** [comment] 2022-05-18 21:32
FYI: this got merged:
- https://github.com/pkkid/python-plexapi/pull/922

**Comment by twolaw** [comment] 2022-06-29 15:25
Work in progress...
With https://github.com/pkkid/python-plexapi/pull/970 I can perform a watchlist sync on my library 🎉 

I can see that Trakt is far ahead of Plex about indexing futur movies :
```
INFO     Skipping Mission: Impossible - Dead Reckoning Part One from Trakt watchlist because not found in Plex Discover
INFO     Skipping Mission: Impossible - Dead Reckoning Part Two from Trakt watchlist because not found in Plex Discover
INFO     Skipping Avatar: The Way of Water from Trakt watchlist because not found in Plex Discover
INFO     Skipping Dune: Part Two from Trakt watchlist because not found in Plex Discover
INFO     Skipping John Wick: Chapter 4 from Trakt watchlist because not found in Plex Discover
```

**Comment by geogolem** [comment] 2022-07-23 02:46
Can't wait for this to be merged. Awesome work! :)

**Comment by glensc** [comment] 2022-07-23 09:53
What is the "this"? I don't see any PR...

**Comment by twolaw** [comment] 2022-07-30 11:23
You can test this PR :
- https://github.com/Taxel/PlexTraktSync/pull/991

and give feedback here.

**Comment by downey-lv** [comment] 2022-08-19 20:19
Worked great for me, trakt watchlist was successfully added to Plex. 
However, I think duplicate entries shouldn't be marked as ERROR, as there is no real issue.
```
INFO     Adding Django Unchained to Plex watchlist
ERROR    Error when adding Django Unchained to Plex watchlist: "Django Unchained" is already on the watchlist
```

Meanwhile skipping is just treated as INFO
`INFO     Skipping Deadpool 3 from Trakt watchlist because not found in Plex Discover`

Maybe skipping should be as WARNING (used when not found on Trakt), but duplicates should be INFO?

Overall love it, thanks for the hard work!

**Comment by downey-lv** [comment] 2022-08-19 20:30
However, I was unable to set up one-way sync. Maybe something is wrong with my config?

![image](https://user-images.githubusercontent.com/70920705/185702362-d31d71f1-f371-43e4-bc0b-eeb0daf2e5f1.png)

**Comment by twolaw** [comment] 2022-08-20 16:43
You have 2 versions of **Django Unchained** in your Plex library ? In Get Info > View XML, what is the Video guid ?

> However, I was unable to set up one-way sync. Maybe something is wrong with my config?

I can't reproduce. Are you sure you saved config.yml before running sync ?

PR #991 has been updated. You can test again.

**Closed** 2022-08-28 08:39 UTC
Labels: enhancement
