### ISSUE TITLE
movie/episode marked as watched twice on Trakt

### ISSUE THREAD

**Issue by iFonny** [Taxel/PlexTraktSync#865] opened 2022-04-02 10:27 UTC
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

Context: 
- "plextraktsync watch" is always running in the background
- I run  "plextraktsync sync" every day at 00h

If we mark a episode as watched on Trakt, when the sync will run the item will be marked as watched on Plex, this will trigger the watched event in "plextraktsync watch" (I think) and will mark it as watched on Trakt.
So on trakt the episode is marked as seen 2 times :/ 

![image](https://user-images.githubusercontent.com/1491951/161379208-a55066a6-4628-4fb9-827e-4b239ba5adbe.png)

### Expected behavior

The episode/movie should not be marked as seen twice.

Add the possibility to not mark as seen on trakt when clicking on "mark as watch" in plex (to only keep scrobble)?

### Steps to reproduce the behavior

I don't know if this is doing that all the time but:
- run "plextraktsync watch" in the background
- mark episode as watched on trakt
- run "plextraktsync sync"

### Install method

docker-compose

### Version

0.18.21

### Python Version

3.10.0

### Operating System and Version

Synology DSM 6.2.4

**Comment by twolaw** [comment] 2022-04-02 10:46
@glensc isn't the `watch` command supposed to ignore plays identified as [PlexTraktSync platform](https://github.com/Taxel/PlexTraktSync/pull/168) ?

**Comment by glensc** [comment] 2022-04-03 09:18
@twolaw the platform check was never implemented. but at least making them identified is in place for a very long time, so this could work. oh, tomorrow exactly a year ago the PR was created :)

**Comment by iFonny** [comment] 2022-04-16 09:55
Update: 
I found another weird issue on the watch command (I don't know if it's possibly related)

<img width="756" alt="Screenshot 2022-04-16 at 10 52 20" src="https://user-images.githubusercontent.com/1491951/163670023-512e27c9-7f41-4c09-a065-a169dedc6701.png">

Episodes are marked a watched again (In the log `Track: false` is incorrect because it was watched on trakt)
I probably moved the episodes files from one folder to another (but it was in the same library so it probably has nothing to do)

<img width="1188" alt="Screenshot 2022-04-16 at 11 31 54" src="https://user-images.githubusercontent.com/1491951/163670328-cfc4c06a-61b6-4409-9a01-59f1193c5fd2.png">
<img width="1225" alt="Screenshot 2022-04-16 at 11 35 24" src="https://user-images.githubusercontent.com/1491951/163670373-7c77f08b-3f4c-4122-996f-b792082ef06c.png">

My config: 
```JSON
{
    "logging": {
        "debug": false,
        "filename": "plextraktsync.log",
        "append": true
    },
    "cache": {
        "path": "$PTS_CACHE_DIR/trakt_cache"
    },
    "sync": {
        "trakt_to_plex": {
            "watched_status": true,
            "ratings": true,
            "liked_lists": false,
            "watchlist": true
        },
        "plex_to_trakt": {
            "watched_status": false,
            "ratings": true,
            "collection": true
        }
    },
    "watch": {
        "scrobble_threshold": 80,
        "add_collection": false,
        "remove_collection": false,
        "username_filter": true
    },
    "xbmc-providers": {
        "movies": "imdb",
        "shows": "tvdb"
    },
    "excluded-libraries": [
        "Private",
        "Family Holidays"
    ]
}
```

**Comment by EVOTk** [comment] 2022-06-19 13:01
Hello,
I have a similar problem, the episodes marked "Seen" on Trakt are not synchronized with Plex.

For example, I saw episode 1 and 3 of The Boys (on Jellyfin).

This is well recorded on Tratk:

![2022-06-19 14_55_47-The Boys Season 3 - Trakt](https://user-images.githubusercontent.com/45015615/174482023-b76c92cd-b0f4-437f-ab6e-caf3789c65ab.png)

But it doesn't sync with Plex:

![2022-06-19 14_58_06-Plex](https://user-images.githubusercontent.com/45015615/174482118-074d2cc3-00d3-4890-847c-9ace7031f635.png)



In Plextratksync logs :
```
INFO     on_activity: <tmdb:3435042:Episode:363584:The-Boys-s03e03>: Collected: 
         True, Watched: [Plex: False, Trakt: False]
```
                      
INFO     on_activity: <tmdb:3283017:Episode:363582:The-Boys-s03e01>: Collected: 
         True, Watched: [Plex: True, Trakt: True]         
```

Plextratksync config.yml :
```
cache:
  path: $PTS_CACHE_DIR/trakt_cache

excluded-libraries:
  - Musiques

config:
  dotenv_override: true

logging:
  append: true
  debug: false
  filename: plextraktsync.log

sync:
  plex_to_trakt:
    collection: true
    ratings: true
    watched_status: true
  trakt_to_plex:
    liked_lists: true
    ratings: true
    watched_status: true
    watchlist: true

watch:
  add_collection: false
  remove_collection: false
  scrobble_threshold: 80
  username_filter: true

xbmc-providers:
  movies: imdb
  shows: tvdb

# vim:ts=2:sw=2:et
```

**Comment by twolaw** [comment] 2022-06-19 14:34
Comment deleted because off-topic.
Please read title of issue and post only if you experience the same issue or if you can help about it.

**Comment by defhead** [comment] 2022-06-25 18:07
Hello,
I'm having the same issue. But I don't even have to run `plextraktsync sync` for it to happen.

Just having the `watch` command running with docker-compose command is enough. Here are the logs of a case when, once fully watched, the episode 03 was marked as watched twice, with 2 minutes interval, even thought I just let Plex keep playing the next episode.

```
INFO     on_play: <Episode:12597:Gaslit-s01e03>: 95.055617% Watched: False,
         LastViewed: 2022-06-25 16:47:50
INFO     on_play: <Episode:12597:Gaslit-s01e03>: 99.240816% Watched: False,
         LastViewed: 2022-06-25 16:47:50
INFO     on_play: <Episode:12597:Gaslit-s01e03>: 99.842797% Watched: False,
         LastViewed: 2022-06-25 16:47:50
INFO     on_activity: <tmdb:3669035:Episode:12618:Gaslit-s01e04>: Collected:
         True, Watched: [Plex: False, Trakt: False]
INFO     on_activity: <tmdb:3658671:Episode:12597:Gaslit-s01e03>: Collected:
         True, Watched: [Plex: True, Trakt: False]
INFO     
         <tmdb:3658671:Episode:12597:Gaslit-s01e03>
INFO     on_play: <Episode:12618:Gaslit-s01e04>: 0.000000% Watched: False,
         LastViewed: None
INFO     on_play: <Episode:12618:Gaslit-s01e04>: 2.295129% Watched: False,
         LastViewed: None
INFO     on_play: <Episode:12618:Gaslit-s01e04>: 3.318632% Watched: False,

``` 

What is triggering ` on_activity: Marking /library/metadata/12597 as watched in Trakt:` event?
It's when I get this log that I also get the "double watch" in my Trakt.

The most of the time, I don't have this "Marking..." log and that's when everything is OK.

Just in case:
```
services:
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync
    network_mode: "host"
    volumes:
      - /path/to/config:/app/config
```

**Comment by zeroquinc** [comment] 2022-07-24 16:21
Having the same issue still, only running the watch command. Exact same setup as @defhead.

![msedge_hVnNzsQ3zY](https://user-images.githubusercontent.com/39315068/180656556-3f5f9fa4-f76b-4406-917b-d7b19ab213c3.png)

Happens on every play.

**Comment by JourneyOver** [comment] 2022-07-27 10:06
This seems to sadly still be happening, I decided to move away from my previous scrobbler to this due to the fact that I am moving alot of stuff to docker right now and my previous scrobbler is not currently dockerized, but this double scrobble is not fun at all as I have to keep going to trakt and removing a scrobble each time I watch sokmething. :/

Hoping to see a fix to this soon! so I don't have to keep installing nano and removing the lines that @zeroquinc mentioned in the watch.py

**Comment by twolaw** [comment] 2022-07-27 11:24
> I also noticed like @defhead mentioned that whenever I had the message `on_activity: Marking /library/metadata/x as watched in Trakt:` that the double played in Trakt happened. So i went into watch.py and removed these lines as dirty fix:
> 
> ```
>   if m.watched_on_plex and not m.watched_on_trakt:
>             self.logger.info(
>                 f"on_activity: Marking {activity.key} as watched in Trakt: {m}"
>             )
>             m.mark_watched_trakt()
> ```
> 
> Now I don't get the message anymore and all my scrobbles are synced once.

Thank you for your help.
This code was added in https://github.com/Taxel/PlexTraktSync/commit/ecfc7e784b113941457c7273ececf77c2c0c9cd9 (closing (#739) to help when manually select "Mark as Played" in Plex without playing the video.

Did you try to increase the trakt threshold ?
```yaml
watch:
  scrobble_threshold: 90
```

I think the problem is the thresholds of Plex and Trakt interfering.

**Comment by JourneyOver** [comment] 2022-07-27 11:28
> > I also noticed like @defhead mentioned that whenever I had the message `on_activity: Marking /library/metadata/x as watched in Trakt:` that the double played in Trakt happened. So i went into watch.py and removed these lines as dirty fix:
> > ```
> >   if m.watched_on_plex and not m.watched_on_trakt:
> >             self.logger.info(
> >                 f"on_activity: Marking {activity.key} as watched in Trakt: {m}"
> >             )
> >             m.mark_watched_trakt()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Now I don't get the message anymore and all my scrobbles are synced once.
> 
> Thank you for your help. This code was added in [ecfc7e7](https://github.com/Taxel/PlexTraktSync/commit/ecfc7e784b113941457c7273ececf77c2c0c9cd9) (closing (#739) to help when manually select "Mark as Played" in Plex without playing the video.
> 
> Did you try to increase the trakt threshold ? to 90 ? to 100 ?
> 
> ```yaml
> watch:
>   scrobble_threshold: 90
> ```
> 
> I think the problem is the thresholds of Plex and Trakt interfering.

I can say that I tried messing with the trakt threshold before moving onto removing those lines of code and it didn't seem to make any different at all.

**Comment by JourneyOver** [comment] 2022-07-27 11:53
@twolaw if you need help testing anything let me know, I will gladly be of service when I can. ^^

**Comment by zeroquinc** [comment] 2022-07-27 12:27
> > I also noticed like @defhead mentioned that whenever I had the message `on_activity: Marking /library/metadata/x as watched in Trakt:` that the double played in Trakt happened. So i went into watch.py and removed these lines as dirty fix:
> > ```
> >   if m.watched_on_plex and not m.watched_on_trakt:
> >             self.logger.info(
> >                 f"on_activity: Marking {activity.key} as watched in Trakt: {m}"
> >             )
> >             m.mark_watched_trakt()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Now I don't get the message anymore and all my scrobbles are synced once.
> 
> Thank you for your help. This code was added in [ecfc7e7](https://github.com/Taxel/PlexTraktSync/commit/ecfc7e784b113941457c7273ececf77c2c0c9cd9) (closing (#739) to help when manually select "Mark as Played" in Plex without playing the video.
> 
> Did you try to increase the trakt threshold ? to 90 ? to 100 ?
> 
> ```yaml
> watch:
>   scrobble_threshold: 90
> ```
> 
> I think the problem is the thresholds of Plex and Trakt interfering.

Hey, no problem.

I tried every value possible I think, it still didn't fix it. Also increasing the threshold to 100 wouldn't work because that would mean you have to watch the credits on every movie for it to sync to Trakt.

Great to hear there are people looking into it. Let me know if you need any help with testing.

**Comment by glensc** [comment] 2022-07-27 12:44
Perhaps just revert https://github.com/Taxel/PlexTraktSync/commit/ecfc7e784b113941457c7273ececf77c2c0c9cd9

I had doubts about it already when adding it:
- https://github.com/Taxel/PlexTraktSync/pull/739#issuecomment-1020178761

**Comment by twolaw** [comment] 2022-07-27 12:44
> @twolaw if you need help testing anything let me know, I will gladly be of service when I can. ^^

Can you try with threshold at 100. Then at 105.

> Also increasing the threshold to 100 wouldn't work 

That's precisely what we want, to pretend it's a pause, not a stop.
https://github.com/Taxel/PlexTraktSync/blob/85ee369fdbe2a5e5ee19de14101988583086b85c/plextraktsync/trakt_api.py#L47-L53

**Comment by twolaw** [comment] 2022-07-27 12:54
I already said that 1 hour ago.

I suggest to remove the `scrobble_threshold` setting and to always post "pause" to trakt api.

**Comment by JourneyOver** [comment] 2022-07-27 12:58
> Can you try with threshold at 100. Then at 105.

@twolaw give me about an hour - hour and a half and I'll report back with if either of these worked or not, as the highest that I had actually tried before removing those lines was around 95.

**Comment by JourneyOver** [comment] 2022-07-27 13:52
@twolaw so having the threshold at either 100 or 105 works, but it does seem to report the wrong time to trakt by several minutes. 

Tested at 100: Finished episode at 08:24 (my time), trakt is reporting it at 8:21.

Tested at 105: Finished episode at 08:48, trakt is reporting it at 8:46.

**Comment by twolaw** [comment] 2022-07-27 13:58
It depends of what you mean by `finished`.
With this solution, the **Plex standard threshold** of 90% of video length is used.
If you watch until 100% of video length, it's normal there is a few minutes offset (10% of video).

**Comment by JourneyOver** [comment] 2022-07-27 14:01
Finished as in watched all the way through till end of credits. Yea I don't like this solution at all as it irks me when the time reports wrong. (literally went in and fixed it on trakt and removed the scrobbles that PTS did)

**Comment by twolaw** [comment] 2022-07-28 18:40
2 solutions :
- (A) remove ability to instantly sync a manual "_mark as watched_" from Plex to Trakt (a full sync will be needed)

- (B) remove ability to choose the `scrobble_threshold` and then watched state will always be sent to Trakt when you reach 90% of video watch

I think (A) is the best.

Temporary workaround : 
- set `scrobble_threshold` to `100` in config file

**Comment by JourneyOver** [comment] 2022-07-28 23:20
I honestly vote for solution A as I never mark things manually in plex as watched anyways.

**Comment by JourneyOver** [comment] 2022-08-02 03:50
any updates on this?

**Comment by twolaw** [comment] 2022-08-02 06:40
PR #992 fixes this issue with solution (A) being :
- (A) remove ability to instantly sync a manual "mark as watched" from Plex to Trakt (a full sync will be needed)

**Closed** 2022-08-02 06:40 UTC
