### ISSUE TITLE
Feature request: Add one way watched synching

### ISSUE THREAD

**Issue by trex005** [Taxel/PlexTraktSync#460] opened 2021-08-29 18:02 UTC
### Feature description
Add one way watched synching:
I would like the option to only "sync" watch history from plex to trakt, but I imagine that there are others that would benifit from the other direction as well.

### Use case
I often rewatch shows and the way I do that is to unmark the show watched in plex so I can track where I am.  Then on next sync, everything is marked watched again.

### Workarounds
 an option would be to mark the shows unwatched in trakt too, however that looses data that I would rather leave in tact.

### Plan to implement
I am not a python developer, however I could take a crack at submitting a PR, but I find my likelihood of success insufficient.

**Comment by glensc** [comment] 2021-08-29 18:43
Btw, the sync script is unable to track rewatches. i.e if it's watched on plex, then the second watch will not be counted for.

however the workaround you use circumvents that problem :D

**Comment by twolaw** [comment] 2021-08-29 18:52
Duplicate of :
- https://github.com/Taxel/PlexTraktSync/issues/4

A branch named `new-features` was created with the solution. But it has not been merged.
Closing this.

**Closed by twolaw** 2021-08-29 18:52 UTC
Labels: enhancement

**Comment by glensc** [comment] 2021-08-29 19:30
Such branch does not exist:
- https://github.com/Taxel/PlexTraktSync/issues/4#issuecomment-766525941
