### ISSUE TITLE
WARNING: Can't use the AlertListener without websocket

### ISSUE THREAD

**Issue by five2seven** [Taxel/PlexTraktSync#319] opened 2021-05-27 18:27 UTC
### The problem
Running sync with `watch ` switch gives error about AlertListener and websocket.
`WARNING: Can't use the AlertListener without websocket`

### Expected behavior
Expected to scrobble Plex plays. 

### Steps to reproduce the behavior
Run `./plex_trakt_sync.sh watch`

### Workarounds
None that I have found. 

### Environment
- Version: 0.9.15
- Python version: 3.7.3
- Platform: Debian 10 - Plex in a Docker container on OMV

**Comment by glensc** [comment] 2021-05-28 22:31
duplicate of https://github.com/Taxel/PlexTraktSync/issues/312

**Closed by glensc** 2021-05-28 22:31 UTC
Labels: bug
