### ISSUE TITLE
trakt.errors.TraktInternalException: Internal Server Error

### ISSUE THREAD

**Issue by Rouzax** [Taxel/PlexTraktSync#80] opened 2020-10-19 08:45 UTC
Updated to the latest git version and was able to run it once but after it fails with the following error

```
PS C:\GitHub\PlexTraktSync> python .\main.py
Starting sync Plex USERNAME and Trakt USERNAME
Processing section Kids Movies
Processing section Movies
Processing section TV Shows
Completed full sync in 6 min 24.3 seconds
PS C:\GitHub\PlexTraktSync> python .\main.py
Starting sync Plex USERNAME and Trakt USERNAME
Traceback (most recent call last):
  File ".\main.py", line 355, in <module>
    main()
  File ".\main.py", line 291, in main
    trakt_watched_shows = pytrakt_extensions.allwatched()
  File "C:\Python38\lib\site-packages\trakt\core.py", line 539, in inner
    json_data = self._handle_request('get', url)
  File "C:\Python38\lib\site-packages\trakt\core.py", line 516, in _handle_request
    raise self.error_map[response.status_code]()
trakt.errors.TraktInternalException: Internal Server Error
PS C:\GitHub\PlexTraktSync> python .\main.py
Starting sync Plex USERNAME and Trakt USERNAME
Traceback (most recent call last):
  File ".\main.py", line 355, in <module>
    main()
  File ".\main.py", line 291, in main
    trakt_watched_shows = pytrakt_extensions.allwatched()
  File "C:\Python38\lib\site-packages\trakt\core.py", line 539, in inner
    json_data = self._handle_request('get', url)
  File "C:\Python38\lib\site-packages\trakt\core.py", line 516, in _handle_request
    raise self.error_map[response.status_code]()
trakt.errors.TraktInternalException: Internal Server Error
PS C:\GitHub\PlexTraktSync> python .\main.py
Starting sync Plex USERNAME and Trakt USERNAME
Traceback (most recent call last):
  File ".\main.py", line 355, in <module>
    main()
  File ".\main.py", line 291, in main
    trakt_watched_shows = pytrakt_extensions.allwatched()
  File "C:\Python38\lib\site-packages\trakt\core.py", line 539, in inner
    json_data = self._handle_request('get', url)
  File "C:\Python38\lib\site-packages\trakt\core.py", line 516, in _handle_request
    raise self.error_map[response.status_code]()
trakt.errors.TraktInternalException: Internal Server Error
PS C:\GitHub\PlexTraktSync>
```

Debug log
```
2020-10-19 10:46:29,502 INFO:Starting sync Plex USERNAME and Trakt USERNAME
2020-10-19 10:46:29,502 DEBUG:get: https://api-v2launch.trakt.tv/users/me
2020-10-19 10:46:29,502 DEBUG:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'APIKEY', 'Authorization': 'Bearer BEARER'}
2020-10-19 10:46:29,502 DEBUG:method, url :: get, https://api-v2launch.trakt.tv/users/me
2020-10-19 10:46:29,502 DEBUG:Starting new HTTPS connection (1): api-v2launch.trakt.tv:443
2020-10-19 10:46:29,740 DEBUG:https://api-v2launch.trakt.tv:443 "GET /users/me HTTP/1.1" 200 94
2020-10-19 10:46:29,747 DEBUG:RESPONSE [get] (https://api-v2launch.trakt.tv/users/me): <Response [200]>
2020-10-19 10:46:29,747 DEBUG:get: https://api-v2launch.trakt.tv/users/USERNAME/watched/movies
2020-10-19 10:46:29,748 DEBUG:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'APIKEY', 'Authorization': 'Bearer BEARER'}
2020-10-19 10:46:29,748 DEBUG:method, url :: get, https://api-v2launch.trakt.tv/users/USERNAME/watched/movies
2020-10-19 10:46:29,752 DEBUG:Starting new HTTPS connection (1): api-v2launch.trakt.tv:443
2020-10-19 10:46:30,339 DEBUG:https://api-v2launch.trakt.tv:443 "GET /users/USERNAME/watched/movies HTTP/1.1" 200 51866
2020-10-19 10:46:30,346 DEBUG:RESPONSE [get] (https://api-v2launch.trakt.tv/users/USERNAME/watched/movies): <Response [200]>
2020-10-19 10:46:30,387 DEBUG:Watched movies from trakt: {139264, 7, 8, 9, 10, 8202, 14, 268305, 18, 19, 77846, 24602, 28, 29, 223262, 31, 253980, 34, 120866, 36, 149544, 96298, 43, 163882, 196651, 372779, 47, 34864, 48, 4146, 24627, 149556, 4149, 54, 4151, 56, 79928, 58, 59, 92214, 315447, 4158, 4159, 64, 77888, 92226, 66, 67, 69, 70, 92230, 92232, 72, 303178, 74, 75, 76, 36940, 243783, 213072, 2128, 80, 10322, 84, 86, 87, 88, 89, 90, 73817, 92252, 292956, 370774, 428130, 103, 6248, 34924, 239730, 209011, 157811, 313464, 120, 30842, 4219, 6268, 126, 108671, 127, 128, 130, 4225, 174212, 284803, 36998, 135, 149640, 202888, 268427, 141, 53390, 43151, 53392, 145, 4242, 16529, 30866, 149, 150, 151, 152, 239768, 190618, 387139, 157, 22685, 159, 160, 10401, 139432, 4267, 106668, 106667, 139438, 161967, 174, 176, 177, 317619, 161972, 229556, 4278, 30905, 264623, 24763, 360637, 235711, 370883, 196, 24772, 198, 377030, 57544, 313547, 6350, 12496, 212, 223444, 108758, 188631, 121049, 65754, 69850, 149723, 295134, 69855, 224, 225505, 133346, 196835, 228, 230, 231, 6375, 233, 234, 24811, 236, 4335, 239, 225520, 200946, 4339, 4340, 178423, 249, 251, 26876, 71938, 4355, 261, 190727, 51342, 139532, 273, 6418, 6419, 276, 277, 6422, 16662, 301334, 219417, 262425, 254235, 8476, 8477, 147742, 305444, 295, 4392, 219433, 57642, 57643, 300, 12589, 4398, 145711, 304, 190767, 219436, 358698, 308, 254263, 6456, 313, 12601, 119098, 57660, 57661, 268719, 57663, 8513, 371013, 326, 205127, 329, 330, 4428, 4429, 233805, 205135, 336, 337, 287057, 258387, 344, 346, 41309, 295265, 192866, 358, 166247, 2408, 59753, 76136, 51563, 14701, 4470, 268663, 4472, 268664, 2427, 100732, 6525, 254332, 383, 6527, 190847, 2434, 348923, 254340, 389, 390, 35207, 392, 65935, 400, 8594, 12693, 59799, 117143, 61849, 410, 188825, 413, 414, 415, 416, 417, 10655, 61856, 168349, 207269, 192932, 166311, 61864, 205219, 205222, 427, 61867, 4527, 432, 61873, 61874, 31151, 6580, 180661, 438, 439, 440, 442, 242107, 443, 444, 445, 2494, 448, 197050, 211394, 213443, 211396, 285120, 383430, 213447, 457, 55753, 451100, 460, 174540, 462, 25039, 464, 463, 322000, 340430, 469, 59861, 472, 4568, 475, 478, 479, 480, 6625, 481, 482, 483, 485, 486, 82405, 240099, 301543, 55786, 492, 47598, 495, 496, 47601, 98799, 8691, 149999, 503, 504, 505, 131577, 25084, 10752, 516, 517, 328196, 521, 33289, 59534, 102924, 256522, 4622, 527, 531, 532, 4629, 96790, 534, 4632, 4633, 4634, 191003, 35353, 541, 35355, 96797, 27168, 545, 546, 547, 548, 549, 55841, 270885, 338466, 553, 554, 371243, 203309, 236077, 31279, 334304, 242226, 10803, 21043, 565, 566, 8759, 119348, 193081, 242227, 4667, 276911, 178749, 168510, 4677, 589, 62030, 590, 592, 242257, 242258, 595, 293456, 597, 205398, 598, 599, 205401, 4697, 16981, 205404, 605, 4700, 16982, 16984, 16985, 610, 463454, 612, 614, 205415, 615, 6761, 616, 72297, 35436, 264821, 630, 2679, 307829, 401889, 635, 55894, 217731, 650, 651, 652, 653, 225931, 655, 172687, 438927, 295570, 659, 172692, 660, 661, 277139, 172700, 4765, 4767, 184992, 4771, 29348, 677, 4773, 273065, 4778, 293547, 41645, 6830, 4783, 297647, 283316, 4789, 98998, 305845, 697, 698, 4793, 700, 86717, 704, 705, 706, 4800, 219842, 221890, 277187, 361154, 498373, 4810, 23244, 722, 242386, 244436, 4821, 135898, 219867, 219869, 451298, 90856, 363240, 39659, 99062, 6904, 762, 174842, 90875, 2813, 23293, 23294, 201238, 769, 256765, 2819, 23299, 23300, 346883, 146185, 224010, 23308, 782, 783, 784, 785, 224015, 350990, 269076, 789, 790, 70421, 792, 351001, 793, 794, 795, 796, 4891, 353053, 39712, 357152, 13093, 2857, 54066, 9010, 170802, 9013, 226105, 4923, 123707, 41789, 226108, 4929, 52036, 6983, 6986, 396109, 127824, 2897, 217936, 851, 27476, 27477, 127828, 4951, 260951, 363355, 9055, 2913, 7010, 232291, 156518, 308070, 195432, 123759, 299887, 881, 4977, 303985, 884, 222071, 270869, 4989, 306046, 258947, 217987, 334724, 322439, 5001, 905, 906, 5003, 5004, 25482, 911, 199563, 5013, 299929, 330651, 31645, 7070, 56223, 11165, 84894, 224157, 226209, 234398, 933, 7077, 138149, 21418, 166828, 11181, 127923, 54196, 41908, 269236, 952, 154554, 7104, 5057, 5058, 27584, 35776, 5061, 3014, 5063, 158661, 5065, 222153, 293826, 385988, 222160, 50131, 7125, 981, 50134, 985, 50139, 7132, 50140, 50141, 7135, 3039, 50145, 84956, 5091, 293862, 271335, 7144, 328678, 7146, 3051, 93163, 340974, 168946, 5107, 82938, 363514, 242684, 1021, 203775, 1028, 1029, 1030, 164868, 1032, 1033, 5128, 27656, 177157, 181256, 222216, 1039, 72719, 209935, 336912, 1048, 103449, 117784, 1052, 7198, 35873, 320546, 107556, 300068, 56358, 56360, 5161, 310313, 375853, 222254, 109615, 1071, 80948, 5174, 7223, 1080, 1081, 5178, 1083, 7228, 7229, 238651, 181311, 181312, 181313, 3138, 293955, 277572, 3144, 183371, 293963, 363597, 308302, 5203, 1111, 277019, 5209, 29789, 83040, 5218, 5220, 25703, 25704, 222316, 255088, 5234, 5235, 1138, 25724, 5245, 23678, 273537, 435331, 1155, 1157, 179334, 304261, 1163, 302219, 171149, 343180, 78993, 1170, 304278, 294039, 230554, 29851, 23708, 23709, 230555, 324762, 337055, 429212, 97444, 101542, 40108, 56494, 1199, 56495, 298164, 81077, 1206, 23734, 1210, 31930, 62655, 283849, 66764, 304332, 68817, 5329, 359635, 140500, 1237, 87254, 310488, 156890, 1244, 9437, 169180, 296164, 238823, 238824, 238825, 5355, 349419, 1261, 5357, 91374, 5360, 29936, 1266, 1267, 1268, 1269, 1270, 5363, 193776, 265465, 277750, 167163, 226556, 265469, 113917, 265470, 107776, 269568, 337145, 369915, 214279, 269578, 52492, 11534, 34064, 257298, 343315, 5398, 195864, 34073, 410908, 5405, 5406, 5407, 5408, 29981, 220447, 5411, 36131, 56612, 5414, 1319, 1320, 11558, 214309, 1323, 329002, 34093, 34095, 410927, 130355, 87348, 191797, 191798, 226615, 237986, 44345, 193850, 290103, 333115, 1343, 156997, 417095, 449866, 36171, 1356, 1357, 99663, 212307, 15709, 42338, 296293, 296295, 224616, 171369, 212330, 46448, 7537, 175475, 394612, 374133, 128378, 148859, 1406, 318851, 1413, 56709, 1416, 222605, 214415, 220563, 13716, 1430, 234907, 118174, 364601, 5539, 157093, 146856, 353704, 193963, 322988, 7597, 1454, 325036, 193968, 1458, 5554, 38322, 243128, 7609, 1466, 347587, 89542, 89543, 5580, 347603, 241110, 241112, 159200, 355809, 167397, 216553, 271850, 314865, 396788, 5621, 374263, 216570, 189952, 165377, 81411, 181765, 241162, 204300, 77325, 241168, 75285, 13845, 81433, 77338, 81435, 249372, 13852, 382491, 169506, 77348, 77349, 177700, 54823, 296488, 77353, 247337, 22059, 292395, 114222, 163375, 7729, 5684, 355892, 149047, 3640, 3642, 132669, 1599, 7751, 194119, 5705, 5706, 5708, 1615, 7759, 77394, 1621, 5723, 46685, 36449, 56931, 5732, 13926, 44653, 71277, 5744, 13937, 13939, 196213, 24185, 134783, 34431, 5765, 3717, 34439, 44679, 44680, 44681, 216715, 46734, 24207, 13968, 46736, 239250, 99984, 300686, 331407, 216727, 114333, 24221, 83614, 114335, 360095, 175781, 24230, 138919, 3753, 93870, 439986, 405173, 333499, 7869, 3774, 218815, 298686, 222913, 3778, 1735, 52936, 34505, 1736, 1737, 14027, 34503, 34507, 73425, 34515, 34516, 34517, 3798, 7895, 5846, 24279, 91859, 91866, 5853, 93923, 57060, 370404, 5864, 22248, 7917, 243438, 311024, 3825, 24307, 349939, 3832, 225019, 1789, 5887, 220927, 16129, 159491, 30474, 53002, 102156, 235276, 53007, 30479, 112404, 286484, 147225, 65316, 3879, 268072, 165674, 3887, 10041, 1851, 112447, 356159, 102209, 3907, 30533, 1863, 94024, 1865, 3914, 22351, 14160, 300880, 14162, 108370, 3924, 3925, 30549, 225109, 57181, 186208, 3942, 292712, 5994, 3948, 30573, 73582, 266092, 153456, 225136, 307054, 210803, 3956, 10101, 307062, 128888, 225146, 40834, 126852, 6022, 231303, 159626, 159627, 42891, 42892, 202637, 40847, 382862, 42897, 53139, 225172, 8085, 348052, 6039, 352153, 130970, 14234, 14236, 92063, 6049, 313251, 294821, 1967, 8112, 221103, 235441, 24500, 57270, 24505, 202681, 225212, 266173, 12222, 4032, 292801, 303043, 196549, 75724, 4044, 6096, 301009, 10197, 432086, 75735, 12248, 6105, 34777, 301015, 190430, 4065, 223202, 65508, 100325, 8166, 192487, 301030, 315368, 2026, 12269, 172017, 4088, 210942}
2020-10-19 10:46:30,387 DEBUG:get: https://api-v2launch.trakt.tv/users/USERNAME/collection/movies?extended=metadata
2020-10-19 10:46:30,387 DEBUG:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'APIKEY', 'Authorization': 'Bearer BEARER'}
2020-10-19 10:46:30,388 DEBUG:method, url :: get, https://api-v2launch.trakt.tv/users/USERNAME/collection/movies?extended=metadata
2020-10-19 10:46:30,391 DEBUG:Starting new HTTPS connection (1): api-v2launch.trakt.tv:443
2020-10-19 10:46:30,624 DEBUG:https://api-v2launch.trakt.tv:443 "GET /users/USERNAME/collection/movies?extended=metadata HTTP/1.1" 200 16533
2020-10-19 10:46:30,633 DEBUG:RESPONSE [get] (https://api-v2launch.trakt.tv/users/USERNAME/collection/movies?extended=metadata): <Response [200]>
2020-10-19 10:46:30,643 DEBUG:get: https://api-v2launch.trakt.tv/sync/watched/shows
2020-10-19 10:46:30,643 DEBUG:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'APIKEY', 'Authorization': 'Bearer BEARER'}
2020-10-19 10:46:30,643 DEBUG:method, url :: get, https://api-v2launch.trakt.tv/sync/watched/shows
2020-10-19 10:46:30,645 DEBUG:Starting new HTTPS connection (1): api-v2launch.trakt.tv:443
2020-10-19 10:46:31,148 DEBUG:https://api-v2launch.trakt.tv:443 "GET /sync/watched/shows HTTP/1.1" 500 20
2020-10-19 10:46:31,154 DEBUG:RESPONSE [get] (https://api-v2launch.trakt.tv/sync/watched/shows): <Response [500]>
```

**Comment by twolaw** [comment] 2020-10-19 13:29
It's an trakt server issue : https://twitter.com/trakt/status/1317933680988364801

**Comment by Rouzax** [comment] 2020-10-19 15:06
That is almost timed perfect that I can run it once and the second time over Trakt breaks 😄

**Comment by twolaw** [comment] 2020-10-19 15:47
Trakt is back online. 👍 

With this kind of connection problem, you should at least wait 24h before (1) checking if same issue already exists on github and (2) creating a new issue only if needed.

duplicate of #35 😉

**Closed** 2020-11-18 16:11 UTC
