### ISSUE TITLE
add_to_collection : Plex ReadTimeout

### ISSUE THREAD

**Issue by steve1977** [Taxel/PlexTraktSync#1455] opened 2023-04-16 05:19 UTC
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [x] I have tried downgrading to find version that can be used as a workaround

### The problem

Subject says it all. It syncs well for a few hundred movies, but then just stops. Error log below.

### Error trace / logs

```text
File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/plextraktsync/__main__.py", line 18, in <module>
    cli()
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/cli.py", line 69, in cli
    sync()
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/cli.py", line 25, in wrap
    cmd(*args, **kwargs)
  File "/app/plextraktsync/commands/sync.py", line 68, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/app/plextraktsync/sync.py", line 66, in sync
    self.sync_collection(movie, dry_run=dry_run)
  File "/app/plextraktsync/sync.py", line 127, in sync_collection
    m.add_to_collection()
  File "/app/plextraktsync/media.py", line 127, in add_to_collection
    self.trakt_api.add_to_collection(self.trakt, self.plex)
  File "/app/plextraktsync/trakt/TraktApi.py", line 182, in add_to_collection
    **pm.to_json(),
      ^^^^^^^^^^^^
  File "/app/plextraktsync/plex/PlexLibraryItem.py", line 325, in to_json
    "resolution": self.resolution,
                  ^^^^^^^^^^^^^^^
  File "/app/plextraktsync/plex/PlexLibraryItem.py", line 209, in resolution
    stream = self.video_streams[0]
             ^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/plex/PlexLibraryItem.py", line 161, in video_streams
    return self.item.videoStreams()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/video.py", line 105, in videoStreams
    self.reload()
  File "/usr/local/lib/python3.11/site-packages/plexapi/base.py", line 368, in reload
    return self._reload(key=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/base.py", line 377, in _reload
    data = self._server.query(key)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/server.py", line 745, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests_cache/session.py", line 103, in get
    return self.request('GET', url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests_cache/session.py", line 159, in request
    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests_cache/session.py", line 206, in send
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests_cache/session.py", line 230, in _send_and_cache
    response = super().send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.11.120', port=32400): Read timed out. (read timeout=30)
```

### Expected behavior

Finish the sync

### Steps to reproduce the behavior

Restarted a few times. Re-run. Same prob happens every time

### Install method

docker-compose

### Version

0.25.17

### Python Version

Don't know

### Operating System and Version

Unraid docker container

**Comment by twolaw** [comment] 2023-04-16 09:59
Duplicate of #956

add_to_collection() requires item resolution and it fails to reload Plex item to get the `video_streams`

**Comment by twolaw** [comment] 2023-04-16 10:04
@steve1977 can you try to disable `collection` :

```yaml
sync:
  plex_to_trakt:
    collection: false
```

**Comment by glensc** [comment] 2023-04-16 19:27
or set bigger plex timeout:

```yml
plex:
  timeout: 300
```

is the crash every time the same item? progressbar number could indicate that.

**Comment by steve1977** [comment] 2023-04-17 15:23
> @steve1977 can you try to disable `collection` :
> 
> ```yaml
> sync:
>   plex_to_trakt:
>     collection: false
> ```

This works in the way that it runs through and completes the sync.

However, the sync doesn't seem to work. Not all my Plex movies are marked as "collected" in Trakt. Not sure how to best troubleshoot what is working / not working. Any suggestions?

**Comment by twolaw** [comment] 2023-04-17 17:29
> Not all my Plex movies are marked as "collected" in Trakt.

Of course, is was just for the test. We're trying to narrow down the problem. Seems to be related to _collection_.

Enable `debug`, run a sync, then read the lines before the crash to find the problematic movie and `inspect` it.

**Comment by steve1977** [comment] 2023-04-18 15:34
I changed collection back to true and also set debug log to true. Unfortunately, now it doesn't work anymore. Log below:

2023-04-18 23:31:56,350 DEBUG[trakt.core]:RESPONSE [get] (https://api-v2launch.trakt.tv/users/likes/lists?limit=1000): <Response [200]>
2023-04-18 23:31:56,351 DEBUG[trakt.core]:get: https://api-v2launch.trakt.tv/lists/6167922
2023-04-18 23:31:56,351 DEBUG[trakt.core]:method, url :: get, https://api-v2launch.trakt.tv/lists/6167922
2023-04-18 23:31:56,353 DEBUG[requests_cache.policy.actions]:Cache directives from request headers: CacheDirectives()
2023-04-18 23:31:56,354 DEBUG[requests_cache.policy.actions]:Pre-read cache checks: Passed
2023-04-18 23:31:56,362 DEBUG[requests_cache.policy.actions]:Post-read cache actions: CacheActions(expire_after=-1)
2023-04-18 23:31:56,363 DEBUG[trakt.core]:RESPONSE [get] (https://api-v2launch.trakt.tv/lists/6167922): <CachedResponse [200]: created: 2023-01-26 12:39:23 CST, expires: N/A (fresh), size: 437 bytes, request: GET https://api-v2launch.trakt.tv/lists/6167922>
2023-04-18 23:31:56,364 ERROR[PlexTraktSync]:UserList.__new__() missing 1 required positional argument: 'share_link'
Traceback (most recent call last):
  File "/app/plextraktsync/cli.py", line 25, in wrap
    cmd(*args, **kwargs)
  File "/app/plextraktsync/commands/sync.py", line 68, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/app/plextraktsync/sync.py", line 61, in sync
    listutil.addList(lst["listid"], lst["listname"])
  File "/app/plextraktsync/trakt_list_util.py", line 95, in addList
    self.lists.append(TraktList(listid, listname))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/trakt_list_util.py", line 40, in __init__
    userlist = LazyUserList._get(listname, listid)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/trakt/core.py", line 558, in inner
    return generator.send(json_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/trakt_list_util.py", line 29, in _get
    ulist = cls(creator=data['user']['username'], **data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: UserList.__new__() missing 1 required positional argument: 'share_link'

**Comment by glensc** [comment] 2023-04-18 17:13
doh! use the serach luke!
- https://github.com/Taxel/PlexTraktSync/search?q=%22share_link%22

**Comment by glensc** [comment] 2023-04-18 17:14
also, edit your post and put log pastes between code fence blocks:
- https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by twolaw** [comment] 2023-04-18 19:50
>  now it doesn't work anymore

update to `0.26.1` and try again

**Comment by steve1977** [comment] 2023-04-23 00:20
I had changed the timeout from 30 to 300, but it didn't seem to work. In the log, it still seems to apply 30 timeout although the config files reflects my change to 30.

Deleting the cache makes it run again, but it still gets stuck and stops after a few movies. Let me attach an updated log that may help troubleshooting. Thanks for your help!

https://pastebin.com/miV4XJe0

**Comment by twolaw** [comment] 2023-04-23 09:48
https://github.com/adamus1red/PlexTraktSync/pull/1

**Comment by twolaw** [comment] 2023-04-23 09:51
Can you show output of:
`plextraktsync inspect 1042314`

**Comment by steve1977** [comment] 2023-04-23 10:07
Here we go: https://pastebin.com/f368jp2S

**Comment by twolaw** [comment] 2023-04-24 09:50
Can you try https://github.com/Taxel/PlexTraktSync/pull/1466 with a 300 timeout

how-to : https://github.com/Taxel/PlexTraktSync/blob/main/CONTRIBUTING.md#install-code-from-pull-request

**Comment by steve1977** [comment] 2023-04-24 11:07
Thanks. I checked out the "how-to", but not sure how to do within an unraid docker container. Not sure how to access docker compose?

**Comment by twolaw** [comment] 2023-04-24 12:16
We don't support Unraid or any special OS. Ask on their forums.

**Comment by glensc** [comment] 2023-04-25 08:00
@steve1977 ignored:
- https://github.com/Taxel/PlexTraktSync/issues/1455#issuecomment-1513528825

**Comment by steve1977** [comment] 2023-05-06 01:30
Sorry, I had been on holidays.

Unfortunately, I still cannot finish the sync. Updated debug log is attached.

https://pastebin.com/xy9YZC4v

I didn't ignore, but not sure how I select the code blocks in pastebin?

**Comment by glensc** [comment] 2023-05-06 18:50
1. unclear what is in that paste? what version? what is config?
2. you select Edit to your post (three dots of your comment) and do as written in the documentation: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks

**Comment by steve1977** [comment] 2023-05-06 23:31
PlexTraktSync [0.26.4]
Config: https://pastebin.com/XhZ4DVV0

I'll try to make the edit above.

**Comment by glensc** [comment] 2023-07-31 23:19
paste expired. post to github instead of third party site. (it accepts .txt extension files. just drag them to text area)

Try to update to last version 0.26.10 and set plex timeout to 300, then give full log.

**Comment by steve1977** [comment] 2023-08-05 12:02
[plextraktsync.log](https://github.com/Taxel/PlexTraktSync/files/12266991/plextraktsync.log)

Thanks. Deleted the cache and updated the docker container. Unfortunately, it seems not to connect. I think I need to wipe some more cache somewhere?

**Comment by codevski** [comment] 2023-08-18 12:26
keeping an eye out on this, seems like having add_collection false it works fine but times out when having it on true... Happy to also share the logs from the last adding to collection... config also has it set to 300

[logs.txt](https://github.com/Taxel/PlexTraktSync/files/12379185/logs.txt)

**Comment by steve1977** [comment] 2023-08-19 12:03
I wiped the contgainer and reinstalled. Increased timeout to 300. Unfortunately, still not working. Log attached.
[2023-08-19 195555,680 INFO[PlexTrak.txt](https://github.com/Taxel/PlexTraktSync/files/12385789/2023-08-19.195555.680.INFO.PlexTrak.txt)

**Comment by glensc** [comment] 2023-08-23 20:49
The log shows your timeout is still 30s:

```
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.11.120', port=32400): Read timed out. (read timeout=30)
```

Refer to python-plex documentation how to change defaults, if plextraktsync config is not working:
- https://python-plexapi.readthedocs.io/en/latest/configuration.html

**Comment by glensc** [comment] 2023-08-23 20:53
Seems the problem is that each query method takes own timeout paratmer, or uses global:
- https://github.com/pkkid/python-plexapi/blob/a7d29a3638bdbec6e223c373a47aeb36a2e60bd5/plexapi/server.py

and the global comes from config:
- https://github.com/pkkid/python-plexapi/blob/a7d29a3638bdbec6e223c373a47aeb36a2e60bd5/plexapi/__init__.py#L20

**Comment by glensc** [comment] 2023-08-23 20:59
Actually, we patch the global `TIMEOUT`:
- https://github.com/Taxel/PlexTraktSync/blob/53be5b84b793c557da784c44119319d918d907a8/plextraktsync/plex/PlexServerConnection.py#L33

so, it should have worked...

**Comment by steve1977** [comment] 2023-08-25 01:23
I double-checked and yet again made sure the timeout has been set to 300. I re-ran and it still errors our and says timeout is 30. See below. What else can I provide to trouble-shoot?

ReadTimeout: HTTPConnectionPool(host='192.168.11.120', port=32400): Read timed out. (read timeout=30)                                    
Error: Error running sync command: HTTPConnectionPool(host='192.168.11.120', port=32400): Read timed out. (read timeout=30)

**Comment by glensc** [comment] 2023-08-28 02:20
I already wrote how:
- https://github.com/Taxel/PlexTraktSync/issues/1455#issuecomment-1690619597

or modify plexapi `__init.py__` manualy

**Comment by cenunix** [comment] 2023-08-29 13:34
hey @glensc how can i get around this when using docker? it doesnt seem to read .config/plexapi even when passing the environment variable for PLEXAPI_CONFIG_PATH in the docker-compose file. Any help would be appreciated, thanks

**Comment by cenunix** [comment] 2023-08-29 21:44
update:  environment:
      - PLEXAPI_PLEXAPI_TIMEOUT=300

**Comment by glensc** [comment] 2023-08-30 20:03
Since workaround is found, closing.

**Closed by glensc** 2023-08-30 20:03 UTC
Labels: bug

**Comment by steve1977** [comment] 2023-08-31 03:53
It still does not work for me as I am using Unraid docker (as many of us), where the work-around does not apply :-( Docker compose cannot be edited.

**Comment by cenunix** [comment] 2023-08-31 04:52
> It still does not work for me as I am using Unraid docker (as many of us), where the work-around does not apply :-( Docker compose cannot be edited.

I'm unfamiliar with unraid, @glensc why is this issue getting closed when the timeout configuration value is still bugged? Surely fixing that is more relevant to this issue.

**Comment by glensc** [comment] 2023-08-31 17:21
@cenunix workaround is to add env variable. I'm sure you can still do the same for Unraid

**Comment by glensc** [comment] 2023-08-31 17:21
plexapi fix merged to this repo: 
- https://github.com/Taxel/PlexTraktSync/pull/1564

**Comment by glensc** [comment] 2023-08-31 17:25
it's included in 0.27.1 release

**Comment by glensc** [comment] 2023-08-31 17:26
And in any case:
> HTTPConnectionPool(host='192.168.11.120', port=32400): Read timed out.

is error from plex server. check plex media server logs.

**Comment by steve1977** [comment] 2023-09-02 05:20
Very cool, working now, thanks for the fix!

**Comment by danielsteiner** [comment] 2023-11-29 13:12
> update, this inside my docker compose seems to have done the trick
> 
> ```yaml
> environment:
>       - PLEXAPI_PLEXAPI_TIMEOUT=300
> ```

Neither this nor setting the timeout to 300 in my config.yml had any effect, in both cases, the timeout occurs after 30 seconds when I am syncing my collection. 

Only syncing the watched items seems to work.
