### ISSUE TITLE
Plex Discover Service Error: Missing required param searchProviders

### ISSUE THREAD

**Issue by TDWillingham** [Taxel/PlexTraktSync#2002] opened 2024-06-26 00:22 UTC
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

I have Plex Discover turned off on my server.  Is there a way to disable this part of the program?  I am getting this error currently:

`2024-06-25 19:06:07,840 INFO[plextraktsync.sync.WatchListPlugin]:Skipping xxxxxxxx from Trakt watchlist because not found in Plex Discover
2024-06-25 19:06:08,058 ERROR[plextraktsync.plex.PlexApi]:xxxxxxxx: Searching Plex Discover error: (400) bad_request; https://discover.provider.plex.tv/library/search?query=xxxxxxxxxxd&limit=30&searchTypes=tv&includeMetadata=1 {"Error":{"error":"Bad Request","message":"Missing required param searchProviders!","statusCode":400}}
`

Or am I misunderstanding what is going on here?

### Steps to reproduce the behavior

1. plextraktsync sync

### Expected behavior

Skip using Plex Disoverer

### Install method

docker-compose

### Version

0.31.4

### Python Version

3.12.4

### Plex Server Version

4.15.14

### Operating System and Version

Unraid

**Comment by glensc** [comment] 2024-06-26 03:59
The Error comes from WatchListPlugin.

You can try to disable it, i.e disable watchlist cloud syncing, i.e use playlists, or disable it completely.

- https://github.com/Taxel/PlexTraktSync/blob/2ef3d440a0ae3af838224005c8e7e9e52244ff59/plextraktsync/sync/WatchListPlugin.py#L27
- https://github.com/Taxel/PlexTraktSync/blob/2ef3d440a0ae3af838224005c8e7e9e52244ff59/plextraktsync/config/SyncConfig.py#L104-L111

**Comment by glensc** [comment] 2024-06-26 04:00
> I have Plex Discover turned off on my server

how it's done?

**Comment by TDWillingham** [comment] 2024-06-26 04:17
> > I have Plex Discover turned off on my server
> 
> how it's done?

Settings -> Online Media Sources -> Disable all of them

I'm still not exactly sure what this setting is doing.  My fault for sure.  Is it something I actually need to keep things in sync with Trakt?  Because the error message makes me thing it's related to the Discover service, which I don't like/need.  It's part of Plex's monetization efforts, which I understand, just don't like it cluttering it up on the server for inexperienced users.

**Comment by glensc** [comment] 2024-06-26 15:20
> Settings -> Online Media Sources -> Disable all of them

Not related to syncing of PlexTraktSync. Did enabling prove your otherwise? You didn't respond to other workaround either.

**Comment by glensc** [comment] 2024-06-26 15:23
Above settings link:
- https://app.plex.tv/desktop/#!/settings/online-media-sources

**Comment by TDWillingham** [comment] 2024-06-26 15:23
I'm not sure how to edit the script inside of a container.  I'd have to fork it and change it there, wouldn't I?  Then pull it again?

If the error isn't related to those settings, wonder why mine is having the error?  That was all I could think of causing it.

**Comment by glensc** [comment] 2024-06-26 15:27
1. edit what script? why?
2. read readme and contributing, describe how to build, including how to use version from pr
3. make the changes and re-run, only you can confirm that (not reproducible)

**Comment by TDWillingham** [comment] 2024-06-26 15:36
Well that's the strangest thing.  I just ran it again a few times to see if it was still occurring and it's not having any errors now.  Guess I can mark it as closed now unless you have any more thoughts.  No idea what was causing it, that's frustrating.

**Comment by glensc** [comment] 2024-06-26 15:39
Since it's third party site, it could be anything ranging from they deployed new code and it was broken or some other temporary anomaly. But since you obfuscated the URL, it's impossible to say what the required parameter might had been. or what there actual query was. From PlexTraktSync debug log might find more details. you need to enable debug logging first.

**Comment by TDWillingham** [comment] 2024-06-26 15:43
It was just the file names that I obfuscated.  I'll keep an eye on it and see if it pops up again.  I'll close it for now.  Thanks for your help!

**Comment by TDWillingham** [comment] 2024-06-26 15:43
Error resolved itself.  Will monitor for further developments.

**Comment by glensc** [comment] 2024-06-26 15:50
This url (literal) still gives 400:
- https://discover.provider.plex.tv/library/search?query=xxxxxxxxxxd&limit=30&searchTypes=tv&includeMetadata=1

**Comment by jakeclements** [comment] 2024-07-02 01:16
@glensc, not sure if this helps but it looks like it's missing `searchProviders=discover` as a required param.

`https://discover.provider.plex.tv/library/search?query=test&limit=30&searchTypes=tv&includeMetadata=1&searchProviders=discover` is returning a 200 and data for me. I checked this through the plex watchlist UI and `discovery` is the same searchProviders value they're using there.

**Comment by jakeclements** [comment] 2024-07-02 06:38
Looks like there's a PR open to fix it in python-plexapi already over here: https://github.com/pkkid/python-plexapi/pull/1437.

**Comment by HomerBeer** [comment] 2024-07-03 19:31
Is this problem solved with a new update?

**Comment by jakeclements** [comment] 2024-07-03 21:56
I expect it will be once that PR is merged and a new version published. Looks like it's yet to be merged currently.

**Comment by glensc** [comment] 2024-07-04 12:17
@HomerBeer what new update? add references to your claims.

**Comment by glensc** [comment] 2024-07-04 12:18
Reproduced myself too

```
WARNING  HTTPSConnectionPool(host='metadata.provider.plex.tv', port=443): Read timed out. (read timeout=30) for                                        
         plextraktsync.plex.PlexLibraryItem.get_guids(), retrying after 1 seconds (try: 1/5)                                                           
Processing Plex watchlist 100% ERROR    Freeway: Searching Plex Discover error: (400) bad_request;                                                                                    
         https://discover.provider.plex.tv/library/search?query=Freeway&limit=30&searchTypes=movies&includeMetadata=1 {"Error":{"error":"Bad           
         Request","message":"Missing required param searchProviders!","statusCode":400}}                                                               
INFO     Skipping Freeway (1996) from Trakt watchlist because not found in Plex Discover    
```

**Closed** 2024-07-08 12:20 UTC
