### ISSUE TITLE
pipx permission denied

### ISSUE THREAD

**Issue by G4Zz0L1** [Taxel/PlexTraktSync#1223] opened 2022-11-23 22:35 UTC
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

I've updated my docker-compose like I always do, but the plextraktsync container keeps restarting, showing the error below in the docker-compose logs.
This is my container config, I just use the watch function, and it has worked fine until now.

```yml
plextraktsync:
      image: ghcr.io/taxel/plextraktsync:latest
      container_name: plextraktsync
      restart: unless-stopped
      network_mode: host
      user: "1000:100"
      volumes:
         - ./PlexTraktSync/config:/app/config
      command: watch
      environment:
         - PGID=1000
         - PUID=100
         - TZ=Europe/Rome
```

### Error trace / logs

```text
plextraktsync  | Traceback (most recent call last):
plextraktsync  |   File "<frozen runpy>", line 198, in _run_module_as_main
plextraktsync  |   File "<frozen runpy>", line 88, in _run_code
plextraktsync  |   File "/app/plextraktsync/__main__.py", line 16, in <module>
plextraktsync  |     from plextraktsync.cli import cli
plextraktsync  |   File "/app/plextraktsync/cli.py", line 317, in <module>
plextraktsync  |     if enable_self_update():
plextraktsync  |        ^^^^^^^^^^^^^^^^^^^^
plextraktsync  |   File "/app/plextraktsync/commands/self_update.py", line 11, in enable_self_update
plextraktsync  |     package = pipx_installed(program_name())
plextraktsync  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
plextraktsync  |   File "/app/plextraktsync/util/packaging.py", line 41, in pipx_installed
plextraktsync  |     output = execx("pipx list --json")
plextraktsync  |              ^^^^^^^^^^^^^^^^^^^^^^^^^
plextraktsync  |   File "/app/plextraktsync/util/execx.py", line 9, in execx
plextraktsync  |     process = subprocess.Popen(
plextraktsync  |               ^^^^^^^^^^^^^^^^^
plextraktsync  |   File "/usr/local/lib/python3.11/subprocess.py", line 1022, in __init__
plextraktsync  |     self._execute_child(args, executable, preexec_fn, close_fds,
plextraktsync  |   File "/usr/local/lib/python3.11/subprocess.py", line 1899, in _execute_child
plextraktsync  |     raise child_exception_type(errno_num, err_msg, err_filename)
plextraktsync  | PermissionError: [Errno 13] Permission denied: 'pipx'
```

### Expected behavior

I'll expect the program to run like always

### Steps to reproduce the behavior

1. use the config above in an empty docker-compose.yml file
2. do `docker-compose up -d`
3. do `docker-compose logs -f`

### Install method

docker-compose

### Config file contents

```yaml
cache:
  path: $PTS_CACHE_DIR/trakt_cache
plex:
  timeout: 30
logging:
  append: true
  console_time: true
  debug: false
  filename: plextraktsync.log
sync:
  plex_to_trakt:
    collection: false
    ratings: false
    watched_status: true
    watchlist: false
  trakt_to_plex:
    liked_lists: false
    ratings: false
    watched_status: true
    watchlist: false
    watchlist_as_playlist: false
watch:
  add_collection: false
  remove_collection: false
  scrobble_threshold: 80
  username_filter: true
xbmc-providers:
  movies: tmdb
  shows: tvdb
```

### Version

:latest on the docker-compose, so the packaged one

### Python Version

the version inside the docker image

### Operating System and Version

Arch Linux

**Comment by glensc** [comment] 2022-11-23 22:41
> Workarounds
>
> No response

you can always downgrade!

> Version
> `:latest` on the docker-compose, so the packaged one

don't cheat. say out the version!

**Comment by glensc** [comment] 2022-11-23 22:44
there's no `pipx` installed in official docker image:

```
➜ docker run --entrypoint sh --rm -it ghcr.io/taxel/plextraktsync:0.24.1
/app # which pipx
/app # plextraktsync --version
PlexTraktSync 0.24.1
```

and why would you get permission error? docker runs with some selinux or AppArmor?

**Comment by G4Zz0L1** [comment] 2022-11-23 22:53
I honestly couldn't tell, if I go with `docker run` it works like yours above, but if I use `docker-compose run` leaving the rest, it gives the error like before.
Docker it's installed like every other program here on Arch, from the repo, without any particular restriction (like selinux or apparmor).
I've also cleared all the plextraktsync images, redownloaded, and same thing happens.

```
❯ docker run --entrypoint sh --rm -it ghcr.io/taxel/plextraktsync:latest
/app # plextraktsync --version
PlexTraktSync 0.24.1
/app # exit
❯ docker-compose run --entrypoint sh --rm -it plextraktsync
/app $ plextraktsync --version
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/plextraktsync/__main__.py", line 16, in <module>
    from plextraktsync.cli import cli
  File "/app/plextraktsync/cli.py", line 317, in <module>
    if enable_self_update():
       ^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/commands/self_update.py", line 11, in enable_self_update
    package = pipx_installed(program_name())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/util/packaging.py", line 41, in pipx_installed
    output = execx("pipx list --json")
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/util/execx.py", line 9, in execx
    process = subprocess.Popen(
              ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1899, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'pipx'
/app $ 
```

**Comment by glensc** [comment] 2022-11-24 07:25
you don't happen to have `docker-composer.override.yml` adding extra "volumes"?

and what about downgrading? since what version the problem starts?

**Comment by glensc** [comment] 2022-11-24 07:26
share `docker-compose config` output, it should print all merged config

**Comment by glensc** [comment] 2022-11-24 07:37
btw, unrelated to your problem, but these have no effect:

```yml
      environment:
         - PGID=1000
         - PUID=100
```

**Comment by G4Zz0L1** [comment] 2022-11-24 09:08
No extra docker-compose.override, or anything fancy, just the config posted above.
Removing only other containers, the `docker-compose config` output:

```
❯ docker-compose config
name: docker-services
services:
[...]
  plextraktsync:
    command:
    - watch
    container_name: plextraktsync
    environment:
      PGID: "1000"
      PUID: "100"
      TZ: Europe/Rome
    image: ghcr.io/taxel/plextraktsync:latest
    network_mode: host
    restart: unless-stopped
    user: 1000:100
    volumes:
    - type: bind
      source: ./PlexTraktSync/config
      target: /app/config
      bind:
        create_host_path: true
[...]
networks:
  default:
    name: docker-services_default
```

> btw, unrelated to your problem, but these have no effect:
> 
> ```yaml
>       environment:
>          - PGID=1000
>          - PUID=100
> ```

Good to know, I'll remove them, and leave only the `user` key, thanks.

**Comment by glensc** [comment] 2022-11-24 09:36
well, I hope you're good with UNIX (since you're Arch user already :D), enter the container with docker compose and poke around, what `which pipx` returns? what's `$PATH`, maybe something esoteric there, maybe run `strace` and see what it tries to open and where the `EPERM` comes from. for `strace` you may need to use `--privileged` flag.

I also wonder can you run other programs?:

```

/app # python -c 'import subprocess; print(subprocess.Popen("date", stdout=subprocess.PIPE, stderr=subprocess.DEVNULL).communicate()[0])'
b'Thu Nov 24 11:36:08 EET 2022\n'
```

**Comment by keldian** [comment] 2022-11-24 10:14
This is the bit that's causing the issue:
> ```yaml
>     user: 1000:100
As of around 0.23.10 or 0.23.11, I had to remove that bit to get back to a working state. Container needs to run as root or it will fail to start, printing the pipx error.

**Comment by glensc** [comment] 2022-11-24 10:15
also, since you change user, `user: 1000:100` could be your problem. you didn't specify that when you used plain docker command. and you still didn't reply did you try downgrading, since what version the problem appears?

**Comment by G4Zz0L1** [comment] 2022-11-24 10:24
I was trying to get strace to work, to post the output you requested, but it seems that's not the problem.
If the problem is the user key, how can i edit the configs without root on the host?

Below some of the things you asked.
```
❯ docker-compose run --entrypoint sh --rm -it plextraktsync
/app $ which pipx
/app $ echo $PATH
/root/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/app $ python -c 'import subprocess; print(subprocess.Popen("date", stdout=subprocess.PIPE, stderr=subprocess.DEVNULL).communicate())'
(b'Thu Nov 24 10:58:49 CET 2022\n', None)
/app $ 
```

**Comment by keldian** [comment] 2022-11-24 10:29
> I was trying to get strace to work, to post the output you requested, but it seems that's not the problem. If the problem is the user key, how can i edit the configs without root on the host?

I believe the image doesn't overwrite the config nor chowns it, so it will still be owned by your user.

**Comment by glensc** [comment] 2022-11-24 10:33
overiding user is not supported. you may workaround with overriding path as well to remove `/root/.local/bin` from it:
```
-e PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by G4Zz0L1** [comment] 2022-11-24 10:33
I'll try to recreate the image without the user key ASAP, and report the results, thanks for now!

**Closed by glensc** 2022-11-24 10:33 UTC

**Comment by glensc** [comment] 2022-11-24 10:49
shorter reproducer:

```sh
docker run -e PATH=/root/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --user=10:10 --rm -it python:3.11-alpine3.16 python -c 'import subprocess as p; print(p.Popen("pipx").communicate())'
```

**Comment by glensc** [comment] 2022-11-24 10:55
happens on macOS as well. the requirement is that the PATH element's first dir (or leading dirs) must exist and be inaccessible. A test with `/root/.bin` would not trigger the error on this system:

```
➜ LC_ALL=C ls -ld /.fseventsd /root
ls: cannot access '/root': No such file or directory
drwx------ 57 root admin 1824 Sep  5 15:05 /.fseventsd/
```

```
➜ PATH=/root/bin:$PATH python -c 'import subprocess as p; print(p.Popen("pipxx").communicate())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pipxx'

➜ PATH=/.fseventsd/bin:$PATH python -c 'import subprocess as p; print(p.Popen("pipxx").communicate())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'pipxx'
```

**Comment by glensc** [comment] 2022-11-24 10:58
This is unexpected behavior from Python, POSIX shell has no problem with such path:

```
➜ PATH=/.fseventsd/bin:$PATH sh -c 'pipxx'
sh: pipxx: command not found
➜ PATH=/.fseventsd/bin:$PATH zsh -c 'pipxx'
zsh:1: command not found: pipxx
➜ PATH=/.fseventsd/bin:$PATH bash -c 'pipxx'
bash: line 1: pipxx: command not found
```

**Comment by glensc** [comment] 2022-11-24 11:02
It's bug from 2005 and still not resolved:
- https://github.com/python/cpython/issues/69667

**Comment by keldian** [comment] 2022-11-24 11:27
Does this mean the Docker `user` parameter will now be supported, or still not?

**Comment by glensc** [comment] 2022-11-24 12:54
Still not supported. But it doesn't mean it wouldn't work.

**Comment by glensc** [comment] 2022-11-24 13:05
Fixed in 0.24.2

**Comment by G4Zz0L1** [comment] 2022-11-24 13:39
> but still, multiple times have I asked you to downgrade, and you ignored it disappointed would have found the commit sooner!

Sorry, I can't stop the compose right now, there are other jobs running that can't be stopped.
Glad to read that's fixed, thanks a lot!

**Comment by gitthangbaby** [comment] 2024-05-18 04:34
this error is also produced when not commenting this
```
#if factory.enable_self_update:
#    cli.add_command(self_update)
```
on synology, no pipx.

**Comment by glensc** [comment] 2024-05-18 12:24
closing old issue. a lot has changed, so new issue with appropriate if that's still an issue
