### ISSUE TITLE
"watch" does not respect excluded libraries

### ISSUE THREAD

**Issue by Fribb** [Taxel/PlexTraktSync#1070] opened 2022-09-25 07:46 UTC
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

I have my plextraktsync running in "watch" mode to scrobble my watched videos to Trakt.

The issue I have is that I have libraries that are running with 3rd Party Metadata Agents and therefore won't be able to scrobble to Trakt.tv.

While watching only a 15-minute Youtube video on my Plex Server there were 139 Errors being logged of the same error in the "Error trace / logs" sections.

I have those libraries listed in the `excluded-libraries` section in the config which is respected by the normal sync.

### Error trace / logs

```text
2022-09-25 09:10:52,537 ERROR[PlexTraktSync]:<Movie:108452:I-can't-believe-the->: Unable to parse a valid provider from guid <PlexGuid:com.plexapp.agents.youtube://youtube|mtch8B0_gKQ|I_can_t_believe_the_price [mtch8B0_gKQ]?lang=xn>
2022-09-25 09:10:52,538 ERROR[PlexTraktSync.WatchStateUpdater]:on_play: Not found: /library/metadata/108452
```

### Expected behavior

"watch" mode should also respect excluded libraries or the Error might be better as "debug" to not excessively generate log output where it is expected to "not work".

### Steps to reproduce the behavior

1. Add youtube library with [Youtube Metadata Agent](https://github.com/ZeroQI/YouTube-Agent.bundle)
2. Download youtube video
3. Add youtube video to library
4. play video in youtube library

### Workarounds

None

### Install method

docker-compose

### Version

0.21.5

### Python Version

3.10.7

### Operating System and Version

Linux-5.15.46-Unraid-x86_64-with

**Comment by twolaw** [comment] 2022-10-29 18:17
duplicate of #877

**Closed by twolaw** 2022-10-29 18:17 UTC
