### ISSUE TITLE
Duplicate watch history

### ISSUE THREAD

**Issue by pkmetski** [Taxel/PlexTraktSync#918] opened 2022-05-18 20:32 UTC
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

I am running plextrakt sync on Ubuntu as following:
- with a systemd service for the `plextraktsync watch` command
- with a cron job running every 2 hours with the `plextraktsync` command

My Trakt account got locked recently and I just learned why: I had around 200K play history items. Most of them duplicates.

### Expected behavior

Play history is not duplicated.

### Steps to reproduce the behavior

1. Run `plextraktsync` on a library with watched items. Wait for the operation to finish.
2. Note the watched history reported to Trakt
3. Run `plextraktsync` again
4. Note the watched history on Trakt - it contains duplicate items

### Workarounds

Remove the cronjob that runs `plextraktsync`
(this stops syncing the collection)

### Install method

pipx (Recommended)

### Version

0.19.2

### Python Version

3.8.10

### Operating System and Version

Ubuntu 20.04

**Comment by twolaw** [comment] 2022-05-23 11:29
Duplicate of #820 #865

**Closed** 2022-05-23 11:29 UTC
Labels: bug, duplicate
