### ISSUE TITLE
increasing memory usage - potentially leak?

### ISSUE THREAD

**Issue by kimpenhaus** [Taxel/PlexTraktSync#431] opened 2021-08-09 05:56 UTC
### The problem

While I am facing an OAuth problem on my main machine (see: #392) I switched to the [docker image](https://ghcr.io/taxel/plextraktsync:latest) which started to be published couple of days ago. I have two libraries to be synchronized (movies, tv-shows) of mid size (~ 4.5k movies and ~ 324 tv-shows). Normally when building up new docker images I restrict them to ensure the docker host isn't affected. So I gave that docker 256MB memory - as I think that synchronizing from plex to trakt shouldn't be a memory consuming task. I then faced several restarts because memory went out. To have a complete run I needed to give that docker  2GB memory.

The memory chart for a complete run looks like:

<img width="579" alt="image" src="https://user-images.githubusercontent.com/575109/128664563-14001699-af0f-49e0-8c2d-cfcf842b4bed.png">

First I thought this might because of building up the cache but another run with complete cache looks quite similar:

<img width="575" alt="image" src="https://user-images.githubusercontent.com/575109/128664624-37804a1d-325c-4f73-a41e-17c5985d22b0.png">

You can see the drop after the first run and then increasing memory usage again.

The docker image used - is tagged latest and was of version 0.13.12 during the run.

### Expected behavior

I am not sure if this is by design but I would assume a synchronizing task to consume less and more constant memory. Main problem I see is with increasing library size memory consumption would also increase during synchronization, so that a docker image can't be restricted (otherwise would start to fail at some point)

### Steps to reproduce the behavior

I would think just start synchronizing a library and see memory consumption and which objects are not garbage collected after usage... 

### Workarounds

- increase memory

### Environment

- Version: 0.13.12
- Python version: 3.9.6
- Platform: docker

**Comment by mcdallas** [comment] 2021-08-10 15:20
It’s probably the unbound lru_cache on the @memoize decorator. This project is fixated on sync speed and pretty much every single function call is cached either in memory or on disk

**Comment by glensc** [comment] 2021-08-11 05:05
you can clear the cache, like this:
- https://github.com/Taxel/PlexTraktSync/blob/0.13.14/plex_trakt_sync/plex_api.py#L414

but it's tricky to figure when to call and how on what objects.


also, it's worth reviewing not to call memorize on things only called once:
- https://github.com/Taxel/PlexTraktSync/blob/0.13.14/plex_trakt_sync/plex_api.py#L251

**Comment by glensc** [comment] 2021-08-11 15:40
Some blog post about memory usage measurements:
- https://www.geeksforgeeks.org/monitoring-memory-usage-of-a-running-python-program/

**Comment by glensc** [comment] 2021-08-11 17:27
I don't know how to measure process memory usage, but this should fix the obvious problem that all movies are loaded to memory at once:
- https://github.com/Taxel/PlexTraktSync/pull/436

**Comment by glensc** [comment] 2021-08-13 21:27
@kimpenhaus please post new graphs when using the mentioned branch.

**Comment by kimpenhaus** [comment] 2021-08-14 19:19
@glensc thanks for investigating and pushing changes to a feature branch!
I just tried the new code but am afraid there is no change in behavior.

This is what it looks like:

<img width="783" alt="image" src="https://user-images.githubusercontent.com/575109/129457745-2b39de85-8ce6-41d1-a618-aebfd956dc88.png">

What I did:

- checked out FB: `all-yield` from your fork

<img width="440" alt="image" src="https://user-images.githubusercontent.com/575109/129457813-1362543c-6ed0-4784-9445-b7d1d171aabc.png">

- built docker image

<img width="983" alt="image" src="https://user-images.githubusercontent.com/575109/129457788-c1cea693-1fb3-4b52-bd43-f13ecbd73031.png">

- pushed image to local registry

<img width="810" alt="image" src="https://user-images.githubusercontent.com/575109/129457805-3643727e-9a03-4e9b-91ac-6fc932e25192.png">

- ran new docker from that image

One thing I saw - and that covers pretty much your measuring in the PR:

<img width="511" alt="image" src="https://user-images.githubusercontent.com/575109/129457925-59cfb371-68ca-4f73-af19-e5df5dc876a3.png">

is that it seems to be faster than that build on main:

FB all-yield:

<img width="356" alt="image" src="https://user-images.githubusercontent.com/575109/129457939-cc520a5d-1bec-464d-8cc6-a62b03644a62.png">

main:

<img width="366" alt="image" src="https://user-images.githubusercontent.com/575109/129457948-60e4df63-5c5d-42b2-8ba1-524d2520d56b.png">

**Comment by glensc** [comment] 2021-08-15 11:23
@kimpenhaus can you post details how did you made those graphs? might help to experiment with some other code to see what code leaks memory. for example, turning off requests_cache, does it affect in any way.

**Comment by kimpenhaus** [comment] 2021-08-18 08:12
@glensc sorry for late reply - I tried to add the memory profiler you mentioned in https://github.com/Taxel/PlexTraktSync/issues/431#issuecomment-896934086 but been struggeling to get any output...

but first things first...

> @kimpenhaus can you post details how did you made those graphs? might help to experiment with some other code to see what code leaks memory. for example, turning off requests_cache, does it affect in any way.

thats nothing special - its the [docker stats](https://documentation.portainer.io/v2.0/containers/stats/) from portainer which states it shows the real-time stats of a running container

regarding the memory profiler ... I patched `main.py` with a wrapper and anotated with the profiler

![image](https://user-images.githubusercontent.com/575109/129862019-ac60eae0-aa4b-4302-a05b-0ebf27ea463f.png)

updated the docker file ... to install the necessary dependencies and changed teh entrypoint to run the wrapper

![image](https://user-images.githubusercontent.com/575109/129862152-96e4b154-de18-4234-8bcc-110b77e0da65.png)

I guess it is profiling as each run is much more time consuming...

![image](https://user-images.githubusercontent.com/575109/129862330-db4dc870-c5c2-46f6-b667-ad1e877251fd.png)

but... the problem is - I can't see any output... the log file is 0 bytes...

![image](https://user-images.githubusercontent.com/575109/129862470-c27fe9d6-f8d0-48f4-8538-b193492432d4.png)

**Comment by glensc** [comment] 2021-08-18 10:31
I thought to figure out the memory leak by elimination process. eliminate parts of code until it's clear which code leaks.

**Comment by sebastianarena** [comment] 2021-12-07 15:06
Very sorry to have submitted a duplicate issue, I searched by "RAM" and didn't find any, and didn't look for "memory". My bad. If I can test something let me know.

**Comment by weirdcrap** [comment] 2021-12-12 15:03
Just wanted to add my own data point (I'm not a programmer so I can't help solve it unfortunately). For a relatively large library (~5000 movies ~1000 tv shows) a 20 minute run consumes 8GB of RAM. As my run times grow with my library I'm sure the RAM usage will only increase.

![image](https://user-images.githubusercontent.com/22824785/145717535-787d217e-1d9a-47f5-83ae-3889f9a3a08f.png)

I'll be following this to see if a resolution is reached.

**Comment by sebastianarena** [comment] 2021-12-20 19:49
@glensc I see 0.18.1 has been released, does it make sense to retry and see if the memory usage has been improved? I have a fairly large library to test

**Comment by glensc** [comment] 2021-12-20 20:00
@sebastianarena just try it. no need to ask permission from developers.

**Comment by sebastianarena** [comment] 2021-12-20 20:02
@glensc wow man, it's a constant attitude with you... we are trying to help. I'm asking because my time is not free the same as yours. Testing this takes time. And if this didn't change anything there's no need to try. Can't understand your rudeness.

**Comment by weirdcrap** [comment] 2021-12-20 20:25
I don't think he had an attitude.

Either way, @glensc this is a vast improvement memory wise. I was able to fully complete a run without crashing and the memory usage stayed under 2.5GB.

**Comment by glensc** [comment] 2021-12-20 20:32
@sebastianarena but asking such useless questions, which you could just test solo and report back, that you create ping pong and wasting again time because I have to respond or you consider it rude that no reply. and not sure whom you are trying to help here, I don't have the memory leak problem. and neither I know how to measure it.

**Comment by sebastianarena** [comment] 2021-12-20 20:36
@glensc let's leave it at that then, we are probably not understanding each other, which is fine. Will test. And report back. Or not, maybe you find that useless as well.

**Comment by glensc** [comment] 2021-12-20 20:52
@weirdcrap you can try to remove more `@memoize` lines, and see which of them has a bigger impact on memory usage. but it's good progress to know it is related to `@memoize` decorator. I was suspecting plexapi collecting objects in memory.

**Comment by weirdcrap** [comment] 2021-12-21 13:23
> @weirdcrap you can try to remove more `@memoize` lines, and see which of them has a bigger impact on memory usage. but it's good progress to know it is related to `@memoize` decorator. I was suspecting plexapi collecting objects in memory.

I really don't know much about python but I can try and take a look. The memory usage is negligible during the movie sync (in my testing it only uses 200MB). The TV show sync is where things take off and by the end its using 2-3GB of RAM so I guess that's where additional tweaks could be made IMO.

**Comment by sebastianarena** [comment] 2021-12-21 13:50
After running some tests yesterday, it seemed at first at the RAM usage was better, however the end result was worse. Previously I could leave the container running and it would eat up the entire ram available and sync up to about 60% of my library. But the last test fail about 30% in.

Running watch, instead of sync, reduced the allocated memory from about 300mb to 30mb now, so that is better.

**Comment by weirdcrap** [comment] 2021-12-21 13:57
@sebastianarena You mentioned in #628 that you were running only a library at a time to keep RAM usage down/prevent crashing of the container. Is your RAM usage out of control for both Movie and TV libraries? 

You're libraries sound much larger than mine (I only have ~1000 TV Shows) but I'm noticing my RAM only gets out of control during the TV library sync. The movie sync uses barely any RAM at all.

If we can narrow it down to a single library type it may be easier to track down the issue.

**Comment by sebastianarena** [comment] 2021-12-21 14:04
@weirdcrap yes, I have been able to sync my Movie library (~30k movies) correctly, but fail to sync my TV Shows Library (~10k shows). I probably think that since the script needs to check episode by episode, then the TV Shows library would make thousands of requests to figure out what to do, thus creating this problem.

I haven't dug deep in the code. But it seems the script does not pre-cache the library nor the trakt information, to then try to pair it up. But to continuously query both things which takes a look of time and leads to the crash. Maybe it just a perception.

Other python+plex scripts like Plex Meta Manager pre-cache the entire library and then figure out what to do. Granted, that script doesn't need to go deep into each episode like this one.

So, I believe with a sufficient big Movie library, it would be the same problem. I think somehow everything that gets downloaded, is stored in RAM for some reason.

I searched the code and found 7 more instances of @memoize usage. I haven't coded Python in a long time. But if we can just remove them and not brake any code, is it there just for speed improvements?

**Comment by weirdcrap** [comment] 2021-12-21 14:44
> @weirdcrap yes, I have been able to sync my Movie library (~30k movies) correctly, but fail to sync my TV Shows Library (~10k shows). I probably think that since the script needs to check episode by episode, then the TV Shows library would make thousands of requests to figure out what to do, thus creating this problem.

I concur it is most likely the shear volume of episodes that have to be processed that leads to the ballooning RAM usage. 

> I haven't dug deep in the code. But it seems the script does not pre-cache the library nor the trakt information, to then try to pair it up. But to continuously query both things which takes a look of time and leads to the crash. Maybe it just a perception.

I believe it does at least cache responses from trakt, isn't that what the trakt_cache.sqlite file is? A quick poke around in the sqlite file in a text editor shows TV show and movie names and corresponding trakt API calls.

I haven't programmed in any language since college but I've been meaning to learn python, so this might be as good a place as any to start.

Could RAM usage be better brought under control for the TV library sync by batching shows into groups, processing them fully, then garbage collecting before loading the next batch? I'd be willing to sacrifice some speed for further RAM improvements. Though with a library as big as yours further sacrificing speed could mean each run will take many hours.

**Comment by twolaw** [comment] 2021-12-21 15:18
The "_when I sync my library_" phrase is not precise enough because it doens't tell if watched status, ratings, lists, collections are sync or not.
You can narrow by syncing only watched status, then only ratings, then only liked lists, etc...
Also tell if using old or new Plex agent, because it's not the same process.

**Comment by sebastianarena** [comment] 2021-12-21 15:47
Personally I'm only trying to sync watch status from Trakt to Plex. Nothing else. If I add any other thing, it just takes forever or crashes sooner. I'm using the Plex Server 1.25.2.5319. I do not know how to tell if the agent is the new or old.

**Comment by twolaw** [comment] 2021-12-21 15:53
Find agent in your library settings :
![image](https://user-images.githubusercontent.com/10365746/146959422-16f96863-434f-4c3c-8098-30ce1012247d.png)


Maybe we should remove each show synced from memory before syncing the next one.
@glensc : https://stackoverflow.com/questions/7133179/python-yield-and-delete

**Comment by sebastianarena** [comment] 2021-12-21 15:59
@twolaw it shows exactly as your screenshots, and movies pretty much the same (the 'legacy' option is not selected), so I believe I'm on the new one. 

If you are storing each show synced in memory, then that is it for sure.

I personally don't mind a long sync process, I just want to run it at least once to import all my trakt watches to plex.

thanks!

**Comment by weirdcrap** [comment] 2021-12-21 17:12
> The "_when I sync my library_" phrase is not precise enough because it doens't tell if watched status, ratings, lists, collections are sync or not. You can narrow by syncing only watched status, then only ratings, then only liked lists, etc... Also tell if using old or new Plex agent, because it's not the same process.

Apologies for being unclear. When I start the docker container it is automatically launching the script so I assume its defaulting to the sync command with all the defaults on:
`    "sync": {
        "trakt_to_plex": {
            "watched_status": true,
            "ratings": true,
            "liked_lists": true,
            "watchlist": true
        },
        "plex_to_trakt": {
            "watched_status": true,
            "ratings": true,
            "collection": true
        }
    },`

I am using the new library agents for both Movies and TV Shows.

I will do some test runs with only one function at a time and see if I can narrow it down further.

**Comment by weirdcrap** [comment] 2022-01-05 14:05
Now that the holidays are over I've had a chance to mess with this some more. 

Regardless of whether I leave all sync options enabled or turn everything off but one sync option (doesn't matter if its watched status, ratings, collections, or playlists/watchlists from plex to trakt or trakt to plex) my RAM usage always ends up right around 2.5GB at the end of the run.

for my use case and RAM availability this isn't a huge deal but for others like Sebastian who want to run this on something like a synology NAS I could see this being a problem still.

**Comment by glensc** [comment] 2022-01-14 10:49
> https://github.com/Taxel/PlexTraktSync/issues/431#issuecomment-998775989

There's no Python knowledge needed to remove lines with `@memoize` on them. and to figure out which one of them has the most impact, also no Python knowledge is needed.

**Comment by mcdallas** [comment] 2022-01-14 11:47
A quick and dirty way to limit memory usage is to set a maxsize in the lru_cache decorator here https://github.com/Taxel/PlexTraktSync/blob/64aac62fa64a2825354ab4d3984ec3191fbfed10/plextraktsync/decorators/memoize.py#L10 however the unit in this is not bytes but function calls so some tweaking might be needed

**Comment by glensc** [comment] 2022-01-14 12:05
@mcdallas are you just guessing or you have actually tried that? Also. The python version reported here does not use the fallback you referred in code for older python version but python built-in imported beginning of the file.

Also, the cache store is per object. So the used cache is always 0 or 1. I might be wing here, but looking the built in python code over and over I've come to that conclusion.

And so far nobody has reported that removing all memorize decorators solves the high memory usage

**Comment by sebastianarena** [comment] 2022-01-14 13:50
Being that I'm on of the most affected by this, I'm re-running the latest patch.
So far, syncing ~1800 movies, ate up 100MB of RAM.
At this rate, syncing the full ~31000 movies will consume 1.8GB of RAM
And then collapse when it gets to syncing ~10000 shows with probably millions of episodes
Will report back in a few hours

**Comment by weirdcrap** [comment] 2022-01-14 14:17
@glensc your latest commit made a massive difference in memory usage. I finished a full sync in 16 minutes and it only used 300MB of RAM.

I could try removing memoize lines in the code still if you think that has the potential to further improve the RAM usage.

@sebastianarena I'm curious to see how your RAM usage will turn out, mine is fantastic after the latest commit.

**Comment by glensc** [comment] 2022-01-14 14:31
for posterity, include a link what is in your opinion "latest".

**Comment by glensc** [comment] 2022-01-14 14:35
also, I'm sick of you people waiting for my approval to test things. you either test or you don't test. you don't need my approval on anything. it's your interest to test, not mine.

**Comment by weirdcrap** [comment] 2022-01-14 14:49
> for posterity, include a link what is in your opinion "latest".

https://github.com/Taxel/PlexTraktSync/releases/tag/0.18.7

Is what I pulled. I'll remove memoize lines one by one and see if improvements are made.

**Comment by glensc** [comment] 2022-01-14 15:10
so far I can tell that, don't remove any `@memoize` from `factory.py`, application expects identical values from repetitive calls in there. you can start with `trakt_api.py` and `plex_api.py`.

**Comment by sebastianarena** [comment] 2022-01-14 17:31
Running version 0.18.7
Synced ~32k movies and ended up with almost 1GB of used RAM
So far, I think the latest patch reduced memory consumption to half or even more
Great to run so far
Probably the best version so far in terms of memory usage

**Comment by sebastianarena** [comment] 2022-01-14 20:06
Version 0.18.7 has been running for some hours, syncing the content, library by library.
I'm excluding all my Plex libraries but one in each iteration, so I can track the usage in each case.
What I find very interesting is that syncing Movies consumed a lot of RAM, like I said, almost 1GB for 30k movies.
But syncing Anime, or TV Shows is proving to consume next to nothing... the RAM keeps steady below the 100mb mark.
I'll keep running this until it finishes, but TV Shows in previous versions would consume tons of RAM.

**Comment by weirdcrap** [comment] 2022-01-14 20:15
> so far I can tell that, don't remove any `@memoize` from `factory.py`, application expects identical values from repetitive calls in there. you can start with `trakt_api.py` and `plex_api.py`.

In my testing so far removing memoize from plex_api.py seems to have minimal/zero effect on RAM usage or execution time.

Commenting out every instance of memoize in trakt_api.py further reduced RAM usage from 300MB to >100MB. The downside is that slows the TV library run times down to a crawl.  

With memoize on in trakt_api a run on my libraries takes about 20 minutes. With all lines commented out it took  over 3 hours before I finally got tired of waiting and stopped the docker.

with only the first memoize line enabled the speed is a little better, it only took 40 minutes. Ram was >100MB

With just the second line speed is pretty bad but RAM is >100MB

With just the third line enabled speed is several hours. RAM is around ~225MB

with the first & second memoize line enabled the speed was actually a bit faster than my previous best run, coming in at right around 15 minutes. RAM usage was a bit higher, around ~150MB.

So there's some more testing to do but different combinations seem to improve the RAM usage a bit more without changing runtime all that much. The RAM savings for me were negligible but it may make a bigger difference for those with larger libraries than mine.

**Comment by glensc** [comment] 2022-01-14 21:55
please fix (edit) your post to link to actual code, the "first, third, fourth" have no value over time if the code changes. and even now need to do some mind mapping!

example link pointing to line 25 on tag 0.18.7:
- https://github.com/Taxel/PlexTraktSync/blob/0.18.7/plextraktsync/trakt_api.py#L25

or at least describe what method name was on each of them

**Comment by weirdcrap** [comment] 2022-01-14 22:06
> please fix (edit) your post to link to actual code, the "first, third, fourth" have no value over time if the code changes. and even now need to do some mind mapping!
> 
> example link pointing to line 25 on tag 0.18.7:
> 
> * https://github.com/Taxel/PlexTraktSync/blob/0.18.7/plextraktsync/trakt_api.py#L25
> 
> or at least describe what method name was on each of them

Sorry about that I'm not super familiar with github. Added links to the trakt_api.py file in the 0.18.7 blob

**Comment by glensc** [comment] 2022-01-14 22:08
The links are off, they point to random code. plz recheck that links to the proper line you intended to. each `@memoize` corresponds to a method, include method names?

**Comment by weirdcrap** [comment] 2022-01-14 22:09
> The links are off, they point to random code. plz recheck that links to the proper line you intended to. each `@memoize` corresponds to a method, include method names?

yeah sorry about that, I'll take another crack at it.

**Comment by weirdcrap** [comment] 2022-01-14 22:13
> The links are off, they point to random code. plz recheck that links to the proper line you intended to. each `@memoize` corresponds to a method, include method names?

OK, I made sure they actually point to the right lines and added the method names.

**Comment by glensc** [comment] 2022-01-14 23:21
one more: "enabled speed is several hours" could improve those sentence to include to the sentence compared to what. as is that several hours good or bad thing I can't figure it out.

**Comment by glensc** [comment] 2022-01-14 23:27
the that memoize per method analyze, actually makes sense. `@memoize` on trakt_api lives the long as trakt_api class. so the cache needs to be moved to PlexLibraryItem or Media classes as those live for the duration of episode/movie, rather the whole sync process. so once episode is processed, cache is discarded with episode object as well.

so, made a pull request removing from collected and lookup:
- https://github.com/Taxel/PlexTraktSync/pull/726

since can't figure out from the report `@memoize` for `find_by_guid` is good or bad thing. I would drop it, as it should be called once for every item processed, no cache needed.

**Comment by weirdcrap** [comment] 2022-01-14 23:34
> one more: "enabled speed is several hours" could improve those sentence to include to the sentence compared to what. as is that several hours good or bad thing I can't figure it out.
Sorry about that, thought it was clear. Before messing with memoize in trakt_api.py my typical runtime for a full sync was roughly 20 minutes. So I consider anything that increases my runtime but does not yield significant RAM usage improvements as "bad". I'll update my comment.

**Comment by weirdcrap** [comment] 2022-01-14 23:35
> one more: "enabled speed is several hours" could improve those sentence to include to the sentence compared to what. as is that several hours good or bad thing I can't figure it out.

Sorry about that, thought it was clear. Before messing with memoize in trakt_api.py my typical runtime for a full sync was roughly 20 minutes. So I consider anything that increases my runtime but does not yield significant RAM usage improvements as "bad". I'll update my comment.

**Comment by glensc** [comment] 2022-01-15 08:57
Please re-test 0.18.8 (includes https://github.com/Taxel/PlexTraktSync/pull/726), also test with memoize removed from `find_by_guid`. to me it doesn't make sense to cache it, as I explained earlier.

it's last memoize that can be removed

**Comment by weirdcrap** [comment] 2022-01-15 13:42
> Please re-test 0.18.8 (includes #726), also test with memoize removed from `find_by_guid`. to me it doesn't make sense to cache it, as I explained earlier.
> 
> it's last memoize that can be removed

With 0.18.8 ram usage is around 250MB and took 18 minutes to complete a full sync.

With memoize commented out for 'find_by_guid' the docker crashes at a random point during the TV show sync. The first time I ran it it crashed almost immediately once TV shows started syncing.

The second run I got a few minutes in before it crashed again.

I'm going to have to find a better way to capture the trace log as UnRAID's web console weirdly cuts off the first couple letters of each line:

```
ceback (most recent call last):
sr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
run_code(code, main_globals, None,
sr/local/lib/python3.10/runpy.py", line 86, in _run_code
e, run_globals)
pp/plextraktsync/__main__.py", line 16, in <module>

sr/local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
elf.main(*args, **kwargs)
sr/local/lib/python3.10/site-packages/click/core.py", line 1053, in main
f.invoke(ctx)
sr/local/lib/python3.10/site-packages/click/core.py", line 1637, in invoke
invoke(ctx)
sr/local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
tx.invoke(self.callback, **ctx.params)
sr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
_callback(*args, **kwargs)
sr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
(get_current_context(), *args, **kwargs)
pp/plextraktsync/cli.py", line 24, in cli

sr/local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
elf.main(*args, **kwargs)
sr/local/lib/python3.10/site-packages/click/core.py", line 1053, in main
f.invoke(ctx)
sr/local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
tx.invoke(self.callback, **ctx.params)
sr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
_callback(*args, **kwargs)
pp/plextraktsync/commands/sync.py", line 110, in sync
ync(walker=w, dry_run=config.dry_run)
pp/plextraktsync/sync.py", line 71, in sync
c_collection(episode, dry_run=dry_run)
pp/plextraktsync/sync.py", line 87, in sync_collection
collected:
pp/plextraktsync/media.py", line 71, in is_collected
d = self.show.collected
sr/local/lib/python3.10/functools.py", line 970, in __get__
lf.func(instance)
pp/plextraktsync/media.py", line 79, in collected
elf.trakt_api.collected(self.trakt)
pp/plextraktsync/decorators/nocache.py", line 12, in inner
ethod(*args, **kwargs)
pp/plextraktsync/decorators/rate_limit.py", line 24, in wrapper
n(*args, **kwargs)
pp/plextraktsync/trakt_api.py", line 232, in collected
ytrakt_extensions.collected(tm.trakt)
sr/local/lib/python3.10/site-packages/trakt/core.py", line 552, in inner
a = self._handle_request('get', url)
sr/local/lib/python3.10/site-packages/trakt/core.py", line 532, in _handle_request
a = json.loads(response.content.decode('UTF-8', 'ignore'))
sr/local/lib/python3.10/json/__init__.py", line 346, in loads
default_decoder.decode(s)
sr/local/lib/python3.10/json/decoder.py", line 337, in decode
= self.raw_decode(s, idx=_w(s, 0).end())
sr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
ONDecodeError("Expecting value", s, err.value) from None
oder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by glensc** [comment] 2022-01-15 16:02
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

this is an error from trakt.tv side, need to know what request was and what status code.

see previous issues the same problem, but none of them got back with the details, because "now it works for me", which is pretty obvious if trakt had temporary errors

- https://github.com/Taxel/PlexTraktSync/search?q=JSONDecodeError+is%3Aissue&type=issues

**Comment by glensc** [comment] 2022-01-15 16:05
> With 0.18.8 ram usage is around 250MB and took 18 minutes to complete a full sync.

those numbers give me nothing. is it good? bad? no change? compare it with the previous run, like: uses 200mb less, complex 19 minutes slower...

**Comment by weirdcrap** [comment] 2022-01-15 16:09
> > With 0.18.8 ram usage is around 250MB and took 18 minutes to complete a full sync.
> 
> those numbers give me nothing. is it good? bad? no change? compare it with the previous run, like: uses 200mb less, complex 19 minutes slower...

It's good, slightly better than previous version RAM usage wise.

With memoize off it's even better.

**Comment by glensc** [comment] 2022-01-15 16:16
retry the find_by_guid memoize being off and on and count trakt.tv requests from log. they should be the same.

```
$ > plextraktsync.log
$ plextraktsync sync --sync=moviles
$ grep -c RESPONSE.*https://api-v2launch.trakt.tv plextraktsync.log
1318
```

if the number is the same, the memorize has no effect (cached only once).

**Comment by weirdcrap** [comment] 2022-01-15 17:03
> retry the find_by_guid memoize being off and on and count trakt.tv requests from log. they should be the same.
> 
> ```
> $ > plextraktsync.log
> $ plextraktsync sync --sync=moviles
> $ grep -c RESPONSE.*https://api-v2launch.trakt.tv plextraktsync.log
> 1318
> ```
> 
> if the number is the same, the memorize has no effect (cached only once).

So to make sure I'm clear, start a sync and then grep the plextraktsync.log file for api responses using: `grep -c RESPONSE.*https://api-v2launch.trakt.tv plextraktsync.log` ?

I checked my log file with that command and I don't have any lines matching lines. Could this be because of how the docker does logging?

![image](https://user-images.githubusercontent.com/22824785/149630699-f04afb6b-33cd-4238-9949-573fbe072f5e.png)

**Comment by glensc** [comment] 2022-01-15 19:14
Seems you didn't read any of the previous issue where same thing was requested. "see previous issues the same problem" usually means you click and read them. those RESPONSE lines are debug logs. debug logging needs to be enabled

**Comment by weirdcrap** [comment] 2022-01-15 19:20
> Seems you didn't read any of the previous issue where same thing was requested. "see previous issues the same problem" usually means you click and read them. those RESPONSE lines are debug logs. debug logging needs to be enabled

No I didn't read it. You made it sound like it was a transient issue with the trakt web response that was unrelated to the memoize conversation we've been having so I didn't think it  was relevant to this discussion. I'll look over the issues you linked and get debugging turned on.

**Comment by glensc** [comment] 2022-01-15 19:54
If you want to get the bottom of the JSONDecodeError,  I need more details.

**Comment by weirdcrap** [comment] 2022-01-15 20:06
> retry the find_by_guid memoize being off and on and count trakt.tv requests from log. they should be the same.
> 
> ```
> $ > plextraktsync.log
> $ plextraktsync sync --sync=moviles
> $ grep -c RESPONSE.*https://api-v2launch.trakt.tv plextraktsync.log
> 1318
> ```
> 
> if the number is the same, the memorize has no effect (cached only once).

memoize OFF: 8366

memoize ON: 8362


> If you want to get the bottom of the JSONDecodeError, I need more details.

If it's a transient error that can be fixed by just waiting a while I'm not terribly concerned about it. I can try to get more details next time it happens but right now I'm unable to reproduce. Whatever the issue was on trakt's end resolved itself.

**Closed** 2022-01-15 22:33 UTC
Labels: bug, help wanted
