### ISSUE TITLE
Initial sync fails with timeout errors

### ISSUE THREAD

**Issue by BEisem** [Taxel/PlexTraktSync#161] opened 2021-04-04 16:48 UTC
I've been trying for the last couple days to do an initial sync. I have a very large library, and apparently Plex sometimes stops responding for a period of time during the initial sync. When I restart `python3 main.py`, it starts from the beginning again.

It would be great if PlextraktSync could either recover from these connection errors, or at the least, start up where it left off on the previous attempt.

```Traceback (most recent call last):
  File "/home/bink/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/bink/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bink/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/bink/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/bink/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/bink/.local/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/home/bink/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/bink/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/bink/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='***REDACTED***', port=32400): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    main()
  File "/home/bink/scripts/PlexTraktSync/plex_trakt_sync/main.py", line 451, in main
    process_movie_section(
  File "/home/bink/scripts/PlexTraktSync/plex_trakt_sync/main.py", line 38, in process_movie_section
    if len(movie.guids) > 0:
  File "/home/bink/.local/lib/python3.8/site-packages/plexapi/base.py", line 441, in __getattribute__
    self.reload()
  File "/home/bink/.local/lib/python3.8/site-packages/plexapi/base.py", line 323, in reload
    data = self._server.query(key)
  File "/home/bink/.local/lib/python3.8/site-packages/plexapi/server.py", line 523, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/home/bink/.local/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/bink/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bink/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/bink/.local/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='***REDACTED***', port=32400): Read timed out. (read timeout=30)```

**Comment by glensc** [comment] 2021-04-04 17:35
This is expected behavior described in the readme. And it does not request everything again, as `request_cache` library caches some requests.

**Comment by BEisem** [comment] 2021-04-04 18:11
Ok, thanks. I read the reame a dozen times and didn't see anything about crashiing being expected behavior. But with that in mind, I have some questions...

The readme says that after the initial pass, the second pass should go a lot quicker. The author states the first pass 1228 seconds, and the second takes 111 seconds. I'm assuming he must have a very small library.

Even after a crash, when I run it again, it starts again at the beginning but I see items in the log indicating `Finished sync.` I'm assuming those are being read from the `request_cache` since they have already been added to Trakt? Is this the speed of things I can expect once the first pass has been completed? I'm averaging about 2-4 items per second, but at that rate, even after the first pass, each run will take several hours on my library. I was hoping for something much quicker after the first run has completed.

**Comment by glensc** [comment] 2021-04-04 18:14
http requests, like "adding" are not cached, but requests like fetch movie details are cached. You can as workaround increase timeout to be 300s instead of 30s.

You need to look plexapi documentation how to do that:
- https://python-plexapi.readthedocs.io/en/latest/

**Comment by glensc** [comment] 2021-04-08 18:42
closing since reporter does not reply, so apparently it solved their problem or they moved on

**Comment by twolaw** [comment] 2021-04-09 09:08
@glensc you're such in a hurry, please calm down.

A crash because of Plex timeout should be fixed, I reopen.

**Comment by BEisem** [comment] 2021-04-09 13:14
I didn't realize the above required a reply, since it seemed like a workaround instead of a fix. II never changed the timeout in plexapi, but I got through the initial scan by repeatedly restarting the script whenever it would crash.

I agree, it shouldn't crash when Plex times out, there should be a more elegant solution.

**Comment by glensc** [comment] 2021-04-09 14:06
This might help: https://github.com/Taxel/PlexTraktSync/pull/210

**Comment by Jacob-Lasky** [comment] 2021-04-14 19:37
I am having the same timeout issue, but my traceback mentioned different line numbers. I'm not sure if this is from the same problem.

```
Starting sync Plex ** and Trakt **

Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib64/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib64/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib64/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host=**, port=32400): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    main()
  File "/mnt/user/misc/trakt_plex_sync/plex_trakt_sync/main.py", line 440, in main
    plex.library.recentlyAdded()[:5]))
  File "/usr/lib64/python3.8/site-packages/plexapi/library.py", line 87, in recentlyAdded
    return self.fetchItems('/library/recentlyAdded')
  File "/usr/lib64/python3.8/site-packages/plexapi/base.py", line 243, in fetchItems
    data = self._server.query(ekey, params=url_kw)
  File "/usr/lib64/python3.8/site-packages/plexapi/server.py", line 523, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/usr/lib64/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib64/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib64/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib64/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host=**, port=32400): Read timed out. (read timeout=30)

```

I'm happy to try the other branch, but it's a huge number of commits ahead so I'm not sure if that's the recommended thing to try right now.

**Comment by glensc** [comment] 2021-04-14 20:26
@Jacob-Lasky: Use the latest release (not some branch). and always include version info when reporting your bug.

**Comment by Jacob-Lasky** [comment] 2021-04-14 20:47
@glensc , apologies the "some branch" was from whatever branch #210 is on. It's the issue that you mentioned in the comment above, meant to put that in there.

Version is whatever is currently in the master branch, as of 12pm MT 4/14/21. I can try the latest release (0.7.9) if that's different than master and will work, though.

**Comment by glensc** [comment] 2021-04-15 02:34
@Jacob-Lasky yes, you better comment in PR itself, and with the code from the branch. if you get the error, include your trace.

**Comment by Jacob-Lasky** [comment] 2021-04-15 17:50
@glensc - thanks for the guidance on this, I should've grabbed the 0.7.9 release (now 0.7.10) at first. Things are working great for me now!

**Closed** 2021-04-19 05:25 UTC
