### ISSUE TITLE
plextraktsync crashes when syncing to a very large Plex library

### ISSUE THREAD

**Issue by jwm-evans** [Taxel/PlexTraktSync#606] opened 2021-11-12 09:50 UTC
### The problem

I am attempting to sync my Trakt "watched" status to a Plex server. It runs for several hours and then crashes with a traceback that suggests that a read timeout is not being handled gracefully. Running the command again, will start the process all over again, and then crash again, usually at a different point

### Error trace

```text
Traceback (most recent call last):
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='plex.server', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/james/.local/bin/plextraktsync", line 8, in <module>
    sys.exit(cli())
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/plextraktsync/commands/sync.py", line 111, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/plextraktsync/sync.py", line 80, in sync
    self.sync_watched(episode, dry_run=dry_run)
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/plextraktsync/sync.py", line 140, in sync_watched
    m.mark_watched_plex()
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/plextraktsync/media.py", line 84, in mark_watched_plex
    self.plex_api.mark_watched(self.plex.item)
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/plextraktsync/decorators/nocache.py", line 12, in inner
    return method(*args, **kwargs)
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/plextraktsync/plex_api.py", line 522, in mark_watched    m.markWatched()
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/plexapi/video.py", line 81, in markWatched
    self._server.query(key)
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/plexapi/server.py", line 659, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/requests_cache/session.py", line 116, in request
    return super().request(
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/requests_cache/session.py", line 148, in send
    response = self._send_and_cache(request, actions, **kwargs)
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/requests_cache/session.py", line 178, in _send_and_cache
    response = super().send(request, **kwargs)
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/james/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='plex.server', port=443): Read timed out. (read timeout=30)
```

### Expected behavior

The program should run successfully. If it does experience an unrecoverable timeout, it should save its progress and resume from that point when the command is next run

### Steps to reproduce the behavior

.config/PlexTraktSync/config.json:
```
{
    "log_debug_messages": false,
    "logging": {
        "append": false
    },
    "cache": {
        "path": "$PTS_CACHE_DIR/trakt_cache"
    },
    "sync": {
        "trakt_to_plex": {
            "watched_status": true,
            "ratings": false,
            "liked_lists": false,
            "watchlist": false
        },
        "plex_to_trakt": {
            "watched_status": true,
            "ratings": false,
            "collection": false
        }
    },
    "watch": {
        "username_filter": false
    },
    "xbmc-providers": {
        "movies": "imdb",
        "shows": "tvdb"
    },
    "excluded-libraries": [
        "AudioBooks",
        "Courses",
        "Fitness",
        "Movies",
        "Movies - 4K",
        "Movies - 4K DV",
        "Movies - Alternate Cut",
        "Movies - Anime",
        "Music",
        "Sports",
        "TV Show - Anime",
        "UFC-WWE Events"
    ]
}
```

```
❯ plextraktsync info
PlexTraktSync Version: 0.16.4
Python Version: 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
Plex API Version: 4.7.2
Trakt API Version: 3.2.2
Cache Dir: /home/user/.cache/PlexTraktSync
Config Dir: /home/user/.config/PlexTraktSync
Log Dir: /home/user/.cache/PlexTraktSync/log
Plex username: plexuser
Trakt username: traktuser
Plex Server version: 1.24.5.5173-8dcc73a59, updated at: 2021-11-11 23:27:45
Enabled 4 libraries in Plex Server: ['UFC-WWE Events', 'TV Shows', 'TV Shows - 4K', 'TV Shows - Anime']

```
Commandline:
```
> plextraktsync sync --sync tv
```

### Workarounds

I am not aware of any workarounds

### Install method

pipx (Recommended)

### Version

 0.16.4

### Python Version

3.8.10

### Operating System and Version

Ubuntu 20.04 (WSL)

**Comment by glensc** [comment] 2021-11-12 11:53
this may help for this particular exception:
- https://github.com/Taxel/PlexTraktSync/pull/607

**Comment by glensc** [comment] 2021-11-20 18:24
@jwm-evans you have not confirmed the fix. why? shall I just close the issue since you're not interested?

**Comment by adolwyn** [comment] 2021-11-23 06:04
I'm not sure if this is the right place to add on, but I am having this identical issue today. I only installed things yesterday, so the #607 thing linked above doesn't appear to have fixed it.

I am using the recommended pipx install method, python 3.8.10, but am running it on a Mac Mini using MacOS Monterey. 

My config file is virtually the same as above, but I have all plex_to_trakt set to false right now (I'm only interested in syncing from Trakt to Plex right now). 

I am also just using the plextraktsync command, nothing else added. 

The crash only seems to happen when Sonarr is syncing a file to the Plex server that the sync is running, and I can't usually restart things until the file has cleared and been added to Plex. I'm not sure if that's what's causing the problem or not. 

Again, sorry if this isn't the right place to add to this issue - I'm not really a Git user.

**Comment by adolwyn** [comment] 2021-11-23 06:06
Here are my errors when it times out:
`INFO: PlexTraktSync [0.16.5]
Sync Movie sections: [<PlexLibrarySection:movie:Movies>]
Sync Show sections: [<PlexLibrarySection:show:TV Shows>]
Traceback (most recent call last):
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1368, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 317, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 278, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1273, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1129, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='192-168-1-12.b6701d40ea0a404c8103aca75257dff9.plex.direct', port=32400): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/theimacofawesome/.local/bin/plextraktsync", line 8, in <module>
    sys.exit(cli())
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/click/core.py", line 1637, in invoke
    super().invoke(ctx)
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/plextraktsync/cli.py", line 23, in cli
    sync()
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/plextraktsync/commands/sync.py", line 111, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/plextraktsync/sync.py", line 71, in sync
    for movie in walker.find_movies():
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/plextraktsync/walker.py", line 224, in find_movies
    for plex in self.get_plex_movies():
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/plextraktsync/walker.py", line 221, in get_plex_movies
    yield from movies
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/plextraktsync/walker.py", line 271, in media_from_sections
    total = len(section)
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/plextraktsync/decorators/nocache.py", line 12, in inner
    return method(*args, **kwargs)
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/plextraktsync/plex_api.py", line 343, in __len__
    return self.section.totalSize
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/plexapi/library.py", line 397, in totalSize
    return self.totalViewSize(includeCollections=False)
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/plexapi/library.py", line 422, in totalViewSize
    data = self._server.query(part)
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/plexapi/server.py", line 659, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/requests_cache/session.py", line 116, in request
    return super().request(
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/requests_cache/session.py", line 148, in send
    response = self._send_and_cache(request, actions, **kwargs)
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/requests_cache/session.py", line 178, in _send_and_cache
    response = super().send(request, **kwargs)
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/theimacofawesome/.local/pipx/venvs/plextraktsync/lib/python3.10/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='192-168-1-12.b6701d40ea0a404c8103aca75257dff9.plex.direct', port=32400): Read timed out. (read timeout=30)`

**Comment by glensc** [comment] 2021-11-23 19:00
@adolwyn if you don't know it's the same issue, create a new issue (and delete comments from here)

**Comment by adolwyn** [comment] 2021-11-25 16:58
@glensc Thanks for reminding me of the difference. I know like 0.1% about scripting. :) I *believe* it's the same issue. 

It's basically the same error message as the first person when syncing a very large plex library, which seems to be the same thing. Thanks!

**Closed** 2021-12-05 23:27 UTC
