### ISSUE TITLE
Docker Doesn't Update Trakt

### ISSUE THREAD

**Issue by jeremehancock** [Taxel/PlexTraktSync#766] opened 2022-01-31 18:04 UTC
### The problem

If I run Plextraktsync using Docker shows that have been watched do not update as watched in Trakt. I have tried the pipx method and all works as expected.

### Expected behavior

Docker version should work the same as the pipx installed version.

### Install method

docker-compose

### Version

0.18.15

### Python Version

3.10.0

### Operating System and Version

Ubuntu 20.04

**Comment by simonk83** [comment] 2022-02-01 11:37
hmm, I just installed this tonight (with docker) and while I could see the progress in trakt while I was watching, it doesn't show on Trakt in the history. There's nothing in the log about scrobbling either (unless that's in a different log verbosity?)

`INFO: <Episode:52568:The-Sinner-s04e05>: 78.203231% Watched: True, LastViewed: 2022-02-01 11:21:05
INFO: <Episode:52568:The-Sinner-s04e05>: 99.282556% Watched: True, LastViewed: 2022-02-01 11:21:05
INFO: <Episode:52568:The-Sinner-s04e05>: 99.282556% Watched: True, LastViewed: 2022-02-01 11:21:05
INFO: Activity: <tmdb:3175128:<Episode:52376:The-Sinner-s04e01>>: Collected: True, Watched: [Plex: True, Trakt: True]
INFO: <Episode:52568:The-Sinner-s04e05>: 0.000000% Watched: True, LastViewed: 2022-02-01 11:21:05
INFO: <Episode:52568:The-Sinner-s04e05>: 0.319922% Watched: True, LastViewed: 2022-02-01 11:21:05
INFO: <Episode:52568:The-Sinner-s04e05>: 0.675392% Watched: True, LastViewed: 2022-02-01 11:21:05
INFO: <Episode:52568:The-Sinner-s04e05>: 99.211463% Watched: True, LastViewed: 2022-02-01 11:21:05
INFO: <Episode:52568:The-Sinner-s04e05>: 99.211463% Watched: True, LastViewed: 2022-02-01 11:21:05
INFO: Activity: <tmdb:3175128:<Episode:52376:The-Sinner-s04e01>>: Collected: True, Watched: [Plex: True, Trakt: True]
INFO: <Episode:52640:The-Sinner-s04e06>: 0.000000% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 66.380503% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 66.748670% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 71.166673% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 72.528891% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 72.897058% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 74.332909% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 75.805577% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 78.345929% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 78.714096% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 78.750913% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 79.082263% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 79.450430% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 79.818597% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 80.186764% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 80.554931% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 80.923098% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 81.291265% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 81.659432% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 82.027599% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 82.395765% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 82.763932% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 83.132099% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 83.500266% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 86.924219% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 87.071486% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 87.439653% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 90.016822% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 92.557174% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 97.269711% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 97.637878% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 99.073729% Watched: False, LastViewed: None
INFO: <Episode:52640:The-Sinner-s04e06>: 99.184179% Watched: False, LastViewed: None
INFO: Activity: <tmdb:3175128:<Episode:52376:The-Sinner-s04e01>>: Collected: True, Watched: [Plex: True, Trakt: True]
`

Also, why is it talking about Episode 1 of that show when I'm watching ep 5 or 6?

**Comment by simonk83** [comment] 2022-02-01 21:22
Interesting. Pretty certain I didn't but I guess it doesn't really matter

**Comment by glensc** [comment] 2022-02-01 21:32
Well. I know. And you can test that yourself if you open things (not play), the Activity entry appears. You don't have to personally open things, it may be done by your player.

**Comment by simonk83** [comment] 2022-02-01 21:33
Yep gotcha. No problem, it's probably because I had the season open in plex web and then chose a file to play, so it plex was probably doing something in the background to make that appear. No worries, just curious :)

**Comment by jeremehancock** [comment] 2022-02-01 22:16
Yeah I have way episodes all the way through with no skipping and the Docker "version" runs but doesn't update. If I sync with the pipx install  it works great.

**Comment by glensc** [comment] 2022-02-01 22:53
Enable debug log and see what gets logged there. Those "me too" are not helping to identify the problem. you can then compare what docker and pipx log differently. 

also, AlertListener Msg Errors are something with trakt.tv site rejecting requests. the same, debug log could help.

**Comment by simonk83** [comment] 2022-02-02 09:30
hmm, well I've set debug to true but I still seem to be only getting INFO messages in the log. I'll keep messing around I guess

**Comment by simonk83** [comment] 2022-02-02 09:36
Alright, well that JSON body sure is invalid. The log is just full of this:

> 2022-02-02 09:31:16,217 DEBUG[requests_cache.cache_control]:Cache directives from request headers: {}
> 2022-02-02 09:31:16,218 DEBUG[trakt.core]:RESPONSE [get] (https://api-v2launch.trakt.tv/search/tmdb/2373603?type=episode): request: GET https://api-v2launch.trakt.tv/search/tmdb/2373603?type=episode, response: 200 (329 bytes), created: 2022-02->
> 2022-02-02 09:31:16,218 DEBUG[trakt.core]:get: https://api-v2launch.trakt.tv/search/tmdb/73586?type=show
> 2022-02-02 09:31:16,218 DEBUG[trakt.core]:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'xxx', 'Authorization': 'Bearer xxx>
> 2022-02-02 09:31:16,218 DEBUG[trakt.core]:method, url :: get, https://api-v2launch.trakt.tv/search/tmdb/73586?type=show
> 2022-02-02 09:31:16,218 DEBUG[requests_cache.cache_keys]:Invalid JSON body:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/requests_cache/cache_keys.py", line 165, in normalize_json_body
>     body = json.loads(decode(original_body))
>   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 2022-02-02 09:31:16,219 DEBUG[requests_cache.cache_control]:Cache directives from request headers: {}
> 2022-02-02 09:31:16,219 DEBUG[trakt.core]:RESPONSE [get] (https://api-v2launch.trakt.tv/search/tmdb/73586?type=show): request: GET https://api-v2launch.trakt.tv/search/tmdb/73586?type=show, response: 200 (182 bytes), created: 2022-02-01 11:14:2>
> 2022-02-02 09:31:16,219 INFO[PlexTraktSync.WatchStateUpdater]:<Episode:52747:Yellowstone-(2018)-s03e07>: 38.473263% Watched: False, LastViewed: 2022-02-02 09:29:28
> 2022-02-02 09:31:16,219 DEBUG[PlexTraktSync]:Sleeping for 0.563 seconds
> 2022-02-02 09:31:16,783 DEBUG[trakt.core]:post: https://api-v2launch.trakt.tv/scrobble/start
> 2022-02-02 09:31:16,784 DEBUG[trakt.core]:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'xxx', 'Authorization': 'Bearer xxx>
> 2022-02-02 09:31:16,787 DEBUG[trakt.core]:method, url :: post, https://api-v2launch.trakt.tv/scrobble/start
> 2022-02-02 09:31:16,790 DEBUG[requests_cache.cache_control]:Cache directives from request headers: {}
> 2022-02-02 09:31:17,112 DEBUG[urllib3.connectionpool]:https://api-v2launch.trakt.tv:443 "POST /scrobble/start HTTP/1.1" 201 None
> 2022-02-02 09:31:17,114 DEBUG[requests_cache.session]:Pre-cache checks for response from https://api-v2launch.trakt.tv/scrobble/start: {'disabled cache': True, 'disabled method': True, 'disabled status': True, 'disabled by filter': False, 'disa>
> 2022-02-02 09:31:17,114 DEBUG[requests_cache.session]:Skipping cache write for URL: https://api-v2launch.trakt.tv/scrobble/start
> 2022-02-02 09:31:17,114 DEBUG[trakt.core]:RESPONSE [post] (https://api-v2launch.trakt.tv/scrobble/start): <Response [201]>
> 2022-02-02 09:31:17,116 DEBUG[plexapi]:Alert: type size PlaySessionStateNotification
> 2022-02-02 09:31:17,116 DEBUG[PlexTraktSync.EventDispatcher]:{'type': 'playing', 'size': 1, 'PlaySessionStateNotification': [{'sessionKey': '167', 'clientIdentifier': 'xxx', 'guid': 'plex://episode/5f277d8ed7ad8>
> 2022-02-02 09:31:17,116 DEBUG[trakt.core]:get: https://api-v2launch.trakt.tv/search/tmdb/2373603?type=episode
> 2022-02-02 09:31:17,116 DEBUG[trakt.core]:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'xxx', 'Authorization': 'Bearer xxx>
> 2022-02-02 09:31:17,116 DEBUG[trakt.core]:method, url :: get, https://api-v2launch.trakt.tv/search/tmdb/2373603?type=episode
> 2022-02-02 09:31:17,119 DEBUG[requests_cache.cache_keys]:Invalid JSON body:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/requests_cache/cache_keys.py", line 165, in normalize_json_body
>     body = json.loads(decode(original_body))
>   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 2022-02-02 09:31:17,119 DEBUG[requests_cache.cache_control]:Cache directives from request headers: {}
> 2022-02-02 09:31:17,121 DEBUG[trakt.core]:RESPONSE [get] (https://api-v2launch.trakt.tv/search/tmdb/2373603?type=episode): request: GET https://api-v2launch.trakt.tv/search/tmdb/2373603?type=episode, response: 200 (329 bytes), created: 2022-02->
> 2022-02-02 09:31:17,121 DEBUG[trakt.core]:get: https://api-v2launch.trakt.tv/search/tmdb/73586?type=show
> 2022-02-02 09:31:17,121 DEBUG[trakt.core]:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'xxx', 'Authorization': 'Bearer xxx>
> 2022-02-02 09:31:17,121 DEBUG[trakt.core]:method, url :: get, https://api-v2launch.trakt.tv/search/tmdb/73586?type=show
> 2022-02-02 09:31:17,124 DEBUG[requests_cache.cache_keys]:Invalid JSON body:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/requests_cache/cache_keys.py", line 165, in normalize_json_body
>     body = json.loads(decode(original_body))
>   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 2022-02-02 09:31:17,124 DEBUG[requests_cache.cache_control]:Cache directives from request headers: {}
> 2022-02-02 09:31:17,125 DEBUG[trakt.core]:RESPONSE [get] (https://api-v2launch.trakt.tv/search/tmdb/73586?type=show): request: GET https://api-v2launch.trakt.tv/search/tmdb/73586?type=show, response: 200 (182 bytes), created: 2022-02-01 11:14:2>
> 2022-02-02 09:31:17,126 INFO[PlexTraktSync.WatchStateUpdater]:<Episode:52747:Yellowstone-(2018)-s03e07>: 38.520138% Watched: False, LastViewed: 2022-02-02 09:29:28
> 2022-02-02 09:31:17,126 DEBUG[PlexTraktSync]:Sleeping for 0.757 seconds

**Comment by simonk83** [comment] 2022-02-03 06:37
Here's the section where it tries to scrobble (but nothing ever ends up on Trakt):

> 2022-02-02 10:37:47,244 DEBUG[requests_cache.cache_control]:Cache directives from request headers: {}
> 2022-02-02 10:37:47,244 DEBUG[trakt.core]:RESPONSE [get] (https://api-v2launch.trakt.tv/search/tmdb/73586?type=show): request: GET https://api-v2launch.trakt.tv/search/tmdb/73586?type=show, response: 200 (182 bytes), created: 2022-02-01 11:14:2>
> 2022-02-02 10:37:47,244 INFO[PlexTraktSync.WatchStateUpdater]:<Episode:52748:Yellowstone-(2018)-s03e08>: 80.049596% Watched: False, LastViewed: None
> 2022-02-02 10:37:47,244 DEBUG[PlexTraktSync]:Sleeping for 0.720 seconds
> 2022-02-02 10:37:47,965 DEBUG[trakt.core]:post: https://api-v2launch.trakt.tv/scrobble/start
> 2022-02-02 10:37:47,966 DEBUG[trakt.core]:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'xxx', 'Authorization': 'Bearer xxx>
> 2022-02-02 10:37:47,966 DEBUG[trakt.core]:method, url :: post, https://api-v2launch.trakt.tv/scrobble/start
> 2022-02-02 10:37:47,968 DEBUG[requests_cache.cache_control]:Cache directives from request headers: {}
> 2022-02-02 10:37:48,310 DEBUG[urllib3.connectionpool]:https://api-v2launch.trakt.tv:443 "POST /scrobble/start HTTP/1.1" 201 None
> 2022-02-02 10:37:48,311 DEBUG[requests_cache.session]:Pre-cache checks for response from https://api-v2launch.trakt.tv/scrobble/start: {'disabled cache': True, 'disabled method': True, 'disabled status': True, 'disabled by filter': False, 'disa>
> 2022-02-02 10:37:48,312 DEBUG[requests_cache.session]:Skipping cache write for URL: https://api-v2launch.trakt.tv/scrobble/start
> 2022-02-02 10:37:48,312 DEBUG[trakt.core]:RESPONSE [post] (https://api-v2launch.trakt.tv/scrobble/start): <Response [201]>
> 2022-02-02 10:37:48,313 DEBUG[plexapi]:Alert: type size PlaySessionStateNotification
> 2022-02-02 10:37:48,313 DEBUG[PlexTraktSync.EventDispatcher]:{'type': 'playing', 'size': 1, 'PlaySessionStateNotification': [{'sessionKey': '170', 'clientIdentifier': 'xxx', 'guid': 'plex://episode/5f1d2ad3c406e>
> 2022-02-02 10:37:48,314 DEBUG[trakt.core]:get: https://api-v2launch.trakt.tv/search/tmdb/2376529?type=episode
> 2022-02-02 10:37:48,314 DEBUG[trakt.core]:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'xxx', 'Authorization': 'Bearer xxx>
> 2022-02-02 10:37:48,314 DEBUG[trakt.core]:method, url :: get, https://api-v2launch.trakt.tv/search/tmdb/2376529?type=episode
> 2022-02-02 10:37:48,315 DEBUG[requests_cache.cache_keys]:Invalid JSON body:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/requests_cache/cache_keys.py", line 165, in normalize_json_body
>     body = json.loads(decode(original_body))
>   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 2022-02-02 10:37:48,315 DEBUG[requests_cache.cache_control]:Cache directives from request headers: {}
> 2022-02-02 10:37:48,315 DEBUG[trakt.core]:RESPONSE [get] (https://api-v2launch.trakt.tv/search/tmdb/2376529?type=episode): request: GET https://api-v2launch.trakt.tv/search/tmdb/2376529?type=episode, response: 200 (338 bytes), created: 2022-02->
> 2022-02-02 10:37:48,315 DEBUG[trakt.core]:get: https://api-v2launch.trakt.tv/search/tmdb/73586?type=show
> 2022-02-02 10:37:48,315 DEBUG[trakt.core]:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'xxx', 'Authorization': 'Bearer xxx>
> 2022-02-02 10:37:48,315 DEBUG[trakt.core]:method, url :: get, https://api-v2launch.trakt.tv/search/tmdb/73586?type=show
> 2022-02-02 10:37:48,316 DEBUG[requests_cache.cache_keys]:Invalid JSON body:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/requests_cache/cache_keys.py", line 165, in normalize_json_body
>     body = json.loads(decode(original_body))
>   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>

**Comment by glensc** [comment] 2022-02-03 21:11
Duplicate of https://github.com/Taxel/PlexTraktSync/issues/758

**Closed by glensc** 2022-02-03 21:11 UTC
