### ISSUE TITLE
"--show=" does not allow for multiple shows with the same title

### ISSUE THREAD

**Issue by BEisem** [Taxel/PlexTraktSync#272] opened 2021-04-18 17:20 UTC
### The problem

Doing the command, for example `./plex_trakt_sync.sh sync --show="Charlie's Angels"` will run the command on the show "Charlie's Angels (2011)" ... but I can't find a way to sync the original show, "Charlie's Angels (1976)". I think we need a way of differentiating or at least being able to scan a show based on some other differentiating factor.

This is why I thought the episode was being skipped in this bug report: https://github.com/Taxel/PlexTraktSync/issues/268#issuecomment-822018901

It turns out I was expecting the script to sync Charlie's Angels (1976) but instead it was syncing Charlie's Angels (2011).

**Comment by glensc** [comment] 2021-04-18 17:25
You already requested `--show` to accept id, can you link it?

I also think the `--show` could be repeated.

**Comment by glensc** [comment] 2021-04-18 17:30
You are wrong, it finds and iterates both shows. Closing the bug report.

```diff
diff --git a/plex_trakt_sync/commands/sync.py b/plex_trakt_sync/commands/sync.py
index 0eec81d..ab768e0 100644
--- a/plex_trakt_sync/commands/sync.py
+++ b/plex_trakt_sync/commands/sync.py
@@ -134,6 +134,8 @@ def for_each_episode(sections, trakt: TraktApi):
 def find_show_episodes(show, plex: PlexApi, trakt: TraktApi):
     search = plex.search(show, libtype='show')
     for pm in search:
+        print(f"Found: {pm}")
+        continue
         tm = trakt.find_by_media(pm)
         # timeit
         for tm, pe, te in for_each_show_episode(pm, tm, trakt):
```


```
➔ ./plex_trakt_sync.sh sync --show="Charlie's Angels"
INFO: Syncing Show: Charlie's Angels
Found: <imdb:tt0073972:<Show:12330:Charlie's-Angels>>
Found: <imdb:tt1760943:<Show:12454:Charlie's-Angels>>
INFO: Completed full sync in 1.1 seconds
```

**Closed by glensc** 2021-04-18 17:30 UTC
Labels: bug

**Comment by BEisem** [comment] 2021-04-18 17:51
I'm not getting the same response when I run the same exact command. Why is yours showing two "found" lines, and mine is showing something completely different when I run the same exact command?

```
% ./plex_trakt_sync.sh sync --show="Charlie's Angels"
INFO: Syncing with Plex BlaEis and Trakt binkatl
INFO: Syncing Show: Charlie's Angels
INFO: Loaded Trakt lists in 3.3 seconds
INFO: Server version 1.22.2.4282-a97b03fad updated at: 2021-04-18 13:29:11
INFO: Recently added: [<Season:380942:Leonardo-s1>, <Movie:380934:Rocky-IV>, <Movie:380931:Right-in-Front-of-Me>, <Movie:380929:American-Dream>, <Season:380924:Godfather-of-Harlem-s2>]
ERROR: Skipping <local:280773:<Episode:280773:Charlie's-Angels-s01e08>>: Provider local not supported
INFO: Updated plex watchlist in 0.0 seconds
INFO: Completed full sync in 7.2 seconds
```

**Comment by glensc** [comment] 2021-04-18 17:52
@BEisem did you read the message I posted? it shows code modification.

**Comment by BEisem** [comment] 2021-04-18 17:53
I did read it but I didn't realize this was a change in a version that I don't have access to yet.

**Comment by glensc** [comment] 2021-04-18 17:55
There's no version, it only shows the changes I made to make it print. It's not committed and will not be committed. Printing added to show that both shows are processed. so this bug report is invalid.

**Comment by BEisem** [comment] 2021-04-18 17:56
Ok, so if this isn't committed, it's just going to remain confusing for end users and even though it's not a bug, it will continue to be a problem. Gotcha.

**Comment by glensc** [comment] 2021-04-18 18:05
The bug you reported is not there. So the issue is closed.

Better filtering is planned anyway. Keeping issue open because some comment had idea for feature request, is confusing for maintainers and to users. 

I have an idea to make the items on screen clickable using rich: https://github.com/Taxel/PlexTraktSync/pull/271. That should solve usability issues. subscribe there to follow on updates. Maybe will use some other library.
