### ISSUE TITLE
Problem sync

### ISSUE THREAD

**Issue by WONTTED** [Taxel/PlexTraktSync#959] opened 2022-06-30 20:35 UTC
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

I have this error TypeError: __new__() got an unexpected keyword argument 'type'

### Error trace / logs

```text
INFO     PlexTraktSync [0.20.2]                                                 
Sync Movie sections: [<PlexLibrarySection:movie:4K Movies>, <PlexLibrarySection:movie:Movies>]
Sync Show sections: [<PlexLibrarySection:show:4K TV shows>, <PlexLibrarySection:show:Anime>, <PlexLibrarySection:show:Kids TV>, <PlexLibrarySection:show:TV Shows>]
INFO     Downloaded List Trakt Watchlist                                        
Traceback (most recent call last):
  File "/Users/tomascastillo/.local/bin/plextraktsync", line 8, in <module>
    sys.exit(cli())
  File "/Users/tomascastillo/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tomascastillo/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/tomascastillo/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tomascastillo/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tomascastillo/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/tomascastillo/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/plextraktsync/cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "/Users/tomascastillo/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/plextraktsync/commands/sync.py", line 60, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/Users/tomascastillo/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/plextraktsync/sync.py", line 64, in sync
    listutil.addList(lst["username"], lst["listname"])
  File "/Users/tomascastillo/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/plextraktsync/trakt_list_util.py", line 88, in addList
    self.lists.append(TraktList(username, listname))
  File "/Users/tomascastillo/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/plextraktsync/trakt_list_util.py", line 47, in __init__
    for elem in LazyUserList._get(listname, username)._items
  File "/Users/tomascastillo/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/trakt/core.py", line 554, in inner
    return generator.send(json_data)
  File "/Users/tomascastillo/.local/pipx/venvs/plextraktsync/lib/python3.8/site-packages/plextraktsync/trakt_list_util.py", line 35, in _get
    ulist = LazyUserList(creator=creator, **data)
TypeError: __new__() got an unexpected keyword argument 'type'
```

### Expected behavior

Sync complete

### Steps to reproduce the behavior

Just use plextraktsync sync command

### Install method

pipx (Recommended)

### Version

0.20.2

### Python Version

Python 3.8.9

### Operating System and Version

Mac OS

**Comment by twolaw** [comment] 2022-07-01 06:29
You lied about checking if identical issue already exists
Duplicate of #941

**Closed** 2022-07-01 06:31 UTC
