### ISSUE TITLE
Can't enter Plex Password

### ISSUE THREAD

**Issue by tallinex** [Taxel/PlexTraktSync#2089] opened 2024-10-23 11:24 UTC
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

I have installed PlexTraktSync using Docker fine but when I try to run the command plextraktsync sync it askes me for my Plex username which i can type in. I then press enter and it asks for my Plex password, this is where I have a problem. 
It will not allow me to type anything, the only thing I can do is press enter which takes me to the 2FA input.

### Steps to reproduce the behavior

```
INFO     PlexTraktSync [0.32.0]                                                                                                                                               
Please enter your Plex username or e-mail (): [my username]
Please enter your Plex password: **_CANNOT TYPE HERE_**
Enter a 2FA code if enabled, or leave blank otherwise: [left blank]
Log in to Plex failed: '(401) unauthorized; https://plex.tv/api/v2/users/signin <?xml version="1.0" encoding="UTF-8"?> <errors>   <error code="1031" message="User could 
not be authenticated. This IP appears to be having trouble signing in to an account (detected repeated failures)" status="401"/> </errors> ', Try again.
```

### Expected behavior

it would let me type my password

### Install method

docker-compose

### Version

0.32.0

### Python Version

3.13.0

### Plex Server Version

4.15.16

### Operating System and Version

Synology NAS Docker

**Comment by simonc56** [comment] 2024-10-23 11:40
I'm sure you can type. What you're saying is that nothing appear on screen while you type.
That's by [design](https://unix.stackexchange.com/questions/268006/why-is-the-password-i-entered-not-visible), the keystrokes are received but not printed.


Duplicate of :
- https://github.com/Taxel/PlexTraktSync/issues/1039

**Comment by tallinex** [comment] 2024-10-24 23:45
I have tried typing my password in the event that was the case but it still didn't work

**Comment by glensc** [comment] 2024-10-27 21:44
you can also use command line argument:
- https://github.com/Taxel/PlexTraktSync/issues/1039#issuecomment-1237433628

**Comment by Naebun** [comment] 2024-11-24 14:57
Hmm i have the same issue and tried to use plextracksync sync -password ******** and it didn't recognise the command

**Comment by Naebun** [comment] 2024-11-24 15:07
Nevermind, i'm not sure if it was a coincidence or not. But i removed all the symbols in my password other then an ! and it worked.

**Closed** 2024-12-01 16:03 UTC
